module TreeSitterManager
  module Themes
    def abscs_abscs : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#fffade", bg: "#060606")
      t.set("attribute", "#e97451")
      t.set("attribute.builtin", "#ed722e")
      t.set("boolean", "#01a0f5")
      t.set("character", "#50c16e")
      t.set("character.special", "#9d9797")
      t.set_extended("comment", color: "#5c4d4d", italic: true)
      t.set("comment.error", "#ff0000")
      t.set("comment.hint", "#fbb13c")
      t.set("comment.note", "#ffcc66")
      t.set("comment.todo", "#ffffff")
      t.set("comment.warning", "#fbb13c")
      t.set("conceal", "#fffade")
      t.set("constant", "#ffcc66")
      t.set("constant.builtin", "#bd33a4")
      t.set("constant.macro", "#702963")
      t.set("constructor", "#01a0f5")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#ffffff")
      t.set("function.builtin", "#00bfff")
      t.set("function.macro", "#006b3c")
      t.set("function.method", "#8877b1")
      t.set("ibl.indent.char.1", "#111111")
      t.set("ibl.scope.char.1", "#777777")
      t.set("ibl.whitespace.char.1", "#373c45")
      t.set("keyword", "#e30022")
      t.set("keyword.exception", "#d68eb2")
      t.set("keyword.function", "#018ed5")
      t.set("keyword.operator", "#f92672")
      t.set("keyword.repeat", "#e30022")
      t.set("keyword.return", "#fc2929")
      t.set("label", "#888888")
      t.set("markup", "#ed722e")
      t.set("markup.heading", "#ffff99")
      t.set_extended("markup.italic", color: "#cccccc", italic: true)
      t.set("markup.link", "#1d918b")
      t.set("markup.list", "#fc2929")
      t.set("markup.quote", "#bbbbbb")
      t.set_extended("markup.strong", color: "#e4717a", bold: true)
      t.set("module", "#ffffff")
      t.set("module.builtin", "#ed722e")
      t.set("number", "#ffcc66")
      t.set("number.float", "#d68eb2")
      t.set("operator", "#f92672")
      t.set("property", "#00cc99")
      t.set("punctuation", "#cccccc")
      t.set("punctuation.bracket", "#a3c1ad")
      t.set("punctuation.delimiter", "#c19a6b")
      t.set("punctuation.special", "#78866b")
      t.set("string", "#cf5c36")
      t.set("string.escape", "#ff0800")
      t.set("string.regexp", "#ff0800")
      t.set("string.special", "#9d9797")
      t.set("string.special.symbol", "#592720")
      t.set_extended("string.special.url", color: "#b31b1b", underline: true)
      t.set("tag", "#178c94")
      t.set("tag.builtin", "#ed722e")
      t.set("type", "#1d918b")
      t.set("type.builtin", "#fc2929")
      t.set("variable", "#00bfa4")
      t.set("variable.builtin", "#99badd")
      t.set("variable.member", "#05d2dd")
      t.set_extended("variable.parameter", color: "#7fbeeb", italic: true)
      t.set("variable.parameter.builtin", "#ed722e")
      t.resolve
    end
  end
end
