module TreeSitterManager
  module Themes
    def aurora_aurora : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#ddd0f4", bg: "#211c2f")
      t.set("annotation", "#4c77e4")
      t.set("attribute", "#7fdbca")
      t.set("attribute.builtin", "#ff6347")
      t.set("boolean", "#ff435b")
      t.set("character", "#ffce51")
      t.set("character.special", "#f92772")
      t.set("comment", "#6189bb")
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#e0e2ea", bold: true)
      t.set("comment.warning", "#fce094")
      t.set("conditional", "#ee82ee")
      t.set("constant", "#fbfcbf")
      t.set("constant.builtin", "#e73c50")
      t.set("constant.macro", "#f92772")
      t.set("constructor", "#6690c4")
      t.set("definition", "#ff5874")
      t.set("definition.usage", "#e6db74")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("emphasis", "#fbed7d")
      t.set("exception", "#ff5874")
      t.set("field", "#9e71cf")
      t.set("float", "#f92772")
      t.set("function", "#66d9ef")
      t.set("function.builtin", "#0fb9e0")
      t.set("function.macro", "#be9af7")
      t.set("ibl.indent.char.1", "#4f425e")
      t.set("ibl.scope.char.1", "#6f527e")
      t.set("ibl.whitespace.char.1", "#4f425e")
      t.set("identifier", "#dacfe4")
      t.set("include", "#d57cd5")
      t.set("keyword", "#c4a2ff")
      t.set("keyword.coroutine", "#f19bb6")
      t.set("keyword.function", "#0fb9e0")
      t.set("keyword.operator", "#fab1c2")
      t.set("keyword.return", "#b376b3")
      t.set("label", "#1aad16")
      t.set("literal", "#dacfe4")
      t.set("markup.environment", "#c33c4a")
      t.set("markup.environment.name", "#67d5b5")
      t.set("markup.heading", "#6c67ea")
      t.set("markup.link.label", "#f92772")
      t.set("markup.link.label.symbol", "#e7c3fb")
      t.set("markup.list", "#4c77e4")
      t.set_extended("markup.list.markdown", color: "#fd9720", bold: true)
      t.set("markup.math", "#ff6347")
      t.set("markup.raw", "#1abc9c")
      t.set("method", "#10aef8")
      t.set("method.call", "#66d9ef")
      t.set("module", "#a1efe4")
      t.set("module.builtin", "#ff6347")
      t.set("number", "#fd9720")
      t.set("number.float", "#f92772")
      t.set("operator", "#a1efe4")
      t.set("parameter", "#fbec9f")
      t.set("parameter.reference", "#a1efe4")
      t.set("property", "#9e71cf")
      t.set("punctuation", "#e0e2ea")
      t.set("punctuation.bracket", "#7aa6da")
      t.set("punctuation.delimiter", "#e7c3fb")
      t.set("punctuation.special", "#ff6347")
      t.set("punctuation.spectial", "#e7c547")
      t.set("repeat", "#ff7273")
      t.set("string", "#1abc9c")
      t.set("string.escape", "#a1efe4")
      t.set("string.regex", "#7fdbca")
      t.set("string.regexp", "#f19bb6")
      t.set("string.special", "#f19bb6")
      t.set("strong", "#dbc08a")
      t.set("structure", "#a1efe4")
      t.set("tag", "#addb67")
      t.set("tag.attribute", "#a1efe4")
      t.set("tag.builtin", "#ff6347")
      t.set("tag.delimiter", "#e0e2ea")
      t.set("text", "#ddd0f4")
      t.set("text.danger", "#dc143c")
      t.set("text.environment", "#c33c4a")
      t.set("text.environment.name", "#67d5b5")
      t.set("text.literal", "#1abc9c")
      t.set("text.math", "#ff6347")
      t.set("text.note", "#ff6347")
      t.set("text.reference", "#fbfcbf")
      t.set("text.title", "#6c67ea")
      t.set_extended("text.todo", color: "#e0e2ea", bold: true)
      t.set("title", "#ecc48d")
      t.set("type", "#67d5b5")
      t.set("type.builtin", "#ffce51")
      t.set("type.definition", "#66d9ef")
      t.set("type.qualifier", "#67d5b5")
      t.set("underline", "#ecc48d")
      t.set("variable", "#e7c3fb")
      t.set("variable.builtin", "#fd9720")
      t.set("variable.parameter.builtin", "#ff6347")
      t.resolve
    end
  end
end
