module TreeSitterManager
  module Themes
    def blue_moon_blue_moon : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#fbfbfb", bg: "#1b1e2b")
      t.set("attribute", "#b9a3eb")
      t.set("attribute.builtin", "#959dcb")
      t.set("boolean", "#b4b4b4")
      t.set_extended("character", color: "#b4c4b4", bold: true)
      t.set_extended("comment", color: "#676e96", italic: true)
      t.set("comment.error", "#d06178")
      t.set("comment.note", "#cfcfbf")
      t.set_extended("comment.todo", color: "#b9a3eb", bold: true)
      t.set_extended("comment.warning", color: "#b9a3eb", bold: true)
      t.set("constant", "#cfcfbf")
      t.set("constant.builtin", "#b4b4b4")
      t.set("constant.macro", "#cfcfbf")
      t.set("constructor", "#cfcfbf")
      t.set("function", "#b8bcf3")
      t.set("function.builtin", "#b9a3eb")
      t.set("function.call", "#b8bcf3")
      t.set("function.macro", "#b4b4b4")
      t.set("function.method", "#b8bcf3")
      t.set("function.method.call", "#b8bcf3")
      t.set("ibl.scope.char.1", "#676e96")
      t.set("keyword", "#959dcb")
      t.set_extended("keyword.conditional", color: "#959dcb", italic: true)
      t.set_extended("keyword.debug", color: "#89bbdd", italic: true)
      t.set("keyword.directive", "#cfcfbf")
      t.set("keyword.directive.define", "#b9a3eb")
      t.set_extended("keyword.exception", color: "#959dcb", italic: true)
      t.set("keyword.function", "#b8bcf3")
      t.set("keyword.import", "#89bbdd")
      t.set("keyword.operator", "#89ddff")
      t.set_extended("keyword.repeat", color: "#959dcb", italic: true)
      t.set("keyword.return", "#959dcb")
      t.set_extended("label", color: "#89bbdd", italic: true)
      t.set("markup", "#959dcb")
      t.set("markup.link", "#89ddff")
      t.set("markup.link.label", "#89ddff")
      t.set_extended("markup.link.url", color: "#b4c4b4", underline: true)
      t.set("markup.list", "#89ddff")
      t.set("module", "#cfcfbf")
      t.set("module.builtin", "#959dcb")
      t.set("number", "#b4b4b4")
      t.set("number.float", "#b4b4b4")
      t.set("operator", "#89ddff")
      t.set("property", "#b8bcf3")
      t.set("punctuation.bracket", "#89bbdd")
      t.set("punctuation.delimiter", "#ffffff")
      t.set("punctuation.special", "#89ddff")
      t.set("string", "#b4c4b4")
      t.set("string.escape", "#89bbdd")
      t.set("string.regexp", "#89bbdd")
      t.set("string.special.symbol", "#c2b0b0")
      t.set_extended("string.special.url", color: "#b4c4b4", underline: true)
      t.set("tag", "#b8bcf3")
      t.set("tag.attribute", "#b8bcf3")
      t.set("tag.builtin", "#959dcb")
      t.set("tag.delimiter", "#89ddff")
      t.set("type", "#cfcfbf")
      t.set("type.builtin", "#b4b4b4")
      t.set("type.definition", "#959dcb")
      t.set("type.qualifier", "#cfcfbf")
      t.set("variable.builtin", "#b4b4b4")
      t.set("variable.member", "#b8bcf3")
      t.set("variable.parameter", "#ffffff")
      t.set("variable.parameter.builtin", "#959dcb")
      t.resolve
    end
  end
end
