module TreeSitterManager
  module Themes
    def boo_boo : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#e1d9ea", bg: "#0f0f10")
      t.set("annotation", "#abb2bf")
      t.set("attribute", "#725478")
      t.set("attribute.builtin", "#654a96")
      t.set("attribute.typescript", "#61afef")
      t.set("boolean", "#b99ee7")
      t.set("character", "#d19a66")
      t.set("character.special", "#3f3442")
      t.set_extended("comment", color: "#5c6370", italic: true)
      t.set("comment.error", "#c988df")
      t.set("comment.note", "#e4dcec")
      t.set_extended("comment.todo", color: "#e86671", italic: true)
      t.set_extended("comment.todo.checked", color: "#98c379", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#e86671", italic: true)
      t.set("comment.warning", "#c0c0dd")
      t.set("conditional", "#53757e")
      t.set("constant", "#7d6c82")
      t.set("constant.builtin", "#4291ad")
      t.set("constant.macro", "#7d6c82")
      t.set("constructor", "#63b0b0")
      t.set("danger", "#abb2bf")
      t.set("diff.add", "#98c379")
      t.set("diff.delete", "#e86671")
      t.set("diff.delta", "#61afef")
      t.set("diff.minus", "#e86671")
      t.set("diff.plus", "#98c379")
      t.set("error", "#abb2bf")
      t.set("exception", "#c678dd")
      t.set("field", "#56b6c2")
      t.set("float", "#d19a66")
      t.set_extended("function", color: "#7da2a9", italic: true)
      t.set("function.builtin", "#3a7272")
      t.set_extended("function.call", color: "#4da2b3", italic: true)
      t.set("function.macro", "#7da2a9")
      t.set("function.method", "#61afef")
      t.set("ibl.indent.char.1", "#31353f")
      t.set("ibl.scope.char.1", "#5c6370")
      t.set("ibl.whitespace.char.1", "#5c6370")
      t.set("include", "#654a96")
      t.set_extended("keyword", color: "#684c9a", italic: true)
      t.set("keyword.conditional", "#c678dd")
      t.set("keyword.directive", "#c678dd")
      t.set("keyword.exception", "#c678dd")
      t.set_extended("keyword.function", color: "#684c9a", italic: true)
      t.set("keyword.import", "#c678dd")
      t.set_extended("keyword.operator", color: "#684c9a", italic: true)
      t.set("keyword.repeat", "#c678dd")
      t.set_extended("keyword.return", color: "#684c9a", italic: true)
      t.set("label", "#e86671")
      t.set("markup", "#654a96")
      t.set_extended("markup.emphasis", color: "#abb2bf", italic: true)
      t.set("markup.environment", "#abb2bf")
      t.set("markup.environment.name", "#abb2bf")
      t.set_extended("markup.heading", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#d19a66", bold: true)
      t.set("markup.link", "#61afef")
      t.set_extended("markup.link.url", color: "#56b6c2", underline: true)
      t.set("markup.list", "#e86671")
      t.set("markup.math", "#abb2bf")
      t.set("markup.raw", "#98c379")
      t.set_extended("markup.strike", color: "#abb2bf", strikethrough: true)
      t.set_extended("markup.strong", color: "#abb2bf", bold: true)
      t.set_extended("markup.underline", color: "#abb2bf", underline: true)
      t.set_extended("method", color: "#4da2b3", italic: true)
      t.set_extended("method.call", color: "#4da2b3", italic: true)
      t.set("module", "#e5c07b")
      t.set("module.builtin", "#654a96")
      t.set("namespace", "#a1b4b8")
      t.set("none", "#abb2bf")
      t.set("note", "#abb2bf")
      t.set("number", "#d19a66")
      t.set("number.float", "#d19a66")
      t.set("operator", "#abb2bf")
      t.set("parameter", "#a9d1df")
      t.set("parameter.reference", "#a9d1df")
      t.set("preproc", "#c678dd")
      t.set("property", "#56b6c2")
      t.set("punctuation", "#8f8fb7")
      t.set("punctuation.bracket", "#656568")
      t.set("punctuation.delimiter", "#61616c")
      t.set("punctuation.special", "#737f8d")
      t.set("repeat", "#53757e")
      t.set("storageclass.lifetime", "#e86671")
      t.set("string", "#daf3f3")
      t.set("string.escape", "#daf3f3")
      t.set("string.regex", "#daf3f3")
      t.set("string.regexp", "#d19a66")
      t.set("string.special", "#daf3f3")
      t.set("string.special.grammar", "#daf3f3")
      t.set("string.special.symbol", "#56b6c2")
      t.set("symbol.grammar.camel", "#56b6c2")
      t.set("symbol.grammar.lower", "#a9d1df")
      t.set("symbol.grammar.pascal", "#63b0b0")
      t.set("symbol.grammar.upper", "#7d6c82")
      t.set("tag", "#85c1c1")
      t.set("tag.attribute", "#738d8d")
      t.set("tag.builtin", "#654a96")
      t.set("tag.delimiter", "#3b4649")
      t.set("text", "#e4dcec")
      t.set("text.diff.add", "#98c379")
      t.set("text.diff.delete", "#e86671")
      t.set_extended("text.emphasis", color: "#abb2bf", italic: true)
      t.set("text.emphassis", "#e4dcec")
      t.set("text.environment", "#e4dcec")
      t.set("text.environment.name", "#e4dcec")
      t.set("text.literal", "#e4dcec")
      t.set("text.math", "#e4dcec")
      t.set("text.reference", "#e4dcec")
      t.set("text.strike", "#e4dcec")
      t.set("text.string", "#e4dcec")
      t.set_extended("text.strong", color: "#abb2bf", bold: true)
      t.set("text.title", "#e4dcec")
      t.set_extended("text.todo", color: "#d19a66", bold: true)
      t.set_extended("text.todo.checked", color: "#98c379", italic: true)
      t.set_extended("text.todo.unchecked", color: "#e86671", italic: true)
      t.set("text.underline", "#e4dcec")
      t.set("text.uri", "#488585")
      t.set("type", "#63b0b0")
      t.set("type.builtin", "#748a90")
      t.set("type.defintion", "#63b0b0")
      t.set("type.qualifier", "#63b0b0")
      t.set("variable", "#94c2d2")
      t.set("variable.builtin", "#3b6392")
      t.set("variable.member", "#56b6c2")
      t.set("variable.parameter", "#e86671")
      t.set("variable.parameter.builtin", "#654a96")
      t.set("warning", "#abb2bf")
      t.resolve
    end
  end
end
