module TreeSitterManager
  module Themes
    def catppuccin_latte : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#4c4f69", bg: "#eff1f5")
      t.set("attribute", "#fe640b")
      t.set("attribute.builtin", "#ea76cb")
      t.set("boolean", "#fe640b")
      t.set("character", "#179299")
      t.set("character.special", "#ea76cb")
      t.set_extended("comment", color: "#7c7f93", italic: true)
      t.set_extended("comment.documentation", color: "#7c7f93", italic: true)
      t.set("comment.error", "#eff1f5")
      t.set("comment.hint", "#eff1f5")
      t.set("comment.note", "#eff1f5")
      t.set("comment.todo", "#eff1f5")
      t.set("comment.warning", "#eff1f5")
      t.set("comment.warning.gitcommit", "#df8e1d")
      t.set_extended("conditional", color: "#8839ef", italic: true)
      t.set("constant", "#fe640b")
      t.set("constant.builtin", "#fe640b")
      t.set("constant.java", "#179299")
      t.set("constant.macro", "#8839ef")
      t.set("constructor", "#209fb5")
      t.set("constructor.lua", "#dd7878")
      t.set("constructor.tsx", "#7287fd")
      t.set("constructor.typescript", "#7287fd")
      t.set("define", "#ea76cb")
      t.set("diff.delta", "#1e66f5")
      t.set("diff.minus", "#d20f39")
      t.set("diff.plus", "#40a02b")
      t.set("error", "#d20f39")
      t.set("exception", "#8839ef")
      t.set("field", "#7287fd")
      t.set("float", "#fe640b")
      t.set("function", "#1e66f5")
      t.set("function.builtin", "#fe640b")
      t.set_extended("function.builtin.bash", color: "#d20f39", italic: true)
      t.set("function.call", "#1e66f5")
      t.set("function.macro", "#179299")
      t.set("function.method", "#1e66f5")
      t.set("function.method.call", "#1e66f5")
      t.set("function.method.call.php", "#1e66f5")
      t.set("function.method.php", "#1e66f5")
      t.set("ibl.indent.char.1", "#ccd0da")
      t.set("ibl.scope.char.1", "#4c4f69")
      t.set("ibl.whitespace.char.1", "#bcc0cc")
      t.set("include", "#8839ef")
      t.set("keyword", "#8839ef")
      t.set_extended("keyword.conditional", color: "#8839ef", italic: true)
      t.set("keyword.conditional.ternary", "#04a5e5")
      t.set("keyword.coroutine", "#8839ef")
      t.set("keyword.debug", "#8839ef")
      t.set("keyword.directive", "#ea76cb")
      t.set("keyword.directive.define", "#ea76cb")
      t.set("keyword.exception", "#8839ef")
      t.set("keyword.export", "#04a5e5")
      t.set("keyword.function", "#8839ef")
      t.set("keyword.import", "#8839ef")
      t.set("keyword.modifier", "#8839ef")
      t.set("keyword.operator", "#04a5e5")
      t.set("keyword.repeat", "#8839ef")
      t.set("keyword.return", "#8839ef")
      t.set("keyword.storage", "#8839ef")
      t.set("keyword.type", "#8839ef")
      t.set("label", "#209fb5")
      t.set("label.json", "#1e66f5")
      t.set("markup", "#4c4f69")
      t.set("markup.environment", "#ea76cb")
      t.set("markup.environment.name", "#1e66f5")
      t.set_extended("markup.heading", color: "#1e66f5", bold: true)
      t.set("markup.heading.1.markdown", "#d20f39")
      t.set("markup.heading.2.markdown", "#fe640b")
      t.set("markup.heading.3.markdown", "#df8e1d")
      t.set("markup.heading.4.markdown", "#40a02b")
      t.set("markup.heading.5.markdown", "#209fb5")
      t.set("markup.heading.6.markdown", "#7287fd")
      t.set_extended("markup.italic", color: "#e64553", italic: true)
      t.set_extended("markup.link", color: "#7287fd", bold: true)
      t.set("markup.link.label", "#209fb5")
      t.set_extended("markup.link.url", color: "#dc8a78", underline: true, italic: true)
      t.set("markup.list", "#ea76cb")
      t.set("markup.list.checked", "#40a02b")
      t.set("markup.list.unchecked", "#8c8fa1")
      t.set("markup.math", "#1e66f5")
      t.set_extended("markup.quote", color: "#e64553", bold: true)
      t.set("markup.raw", "#179299")
      t.set_extended("markup.strikethrough", color: "#4c4f69", strikethrough: true)
      t.set_extended("markup.strong", color: "#e64553", bold: true)
      t.set("method", "#1e66f5")
      t.set("method.call", "#1e66f5")
      t.set("method.call.php", "#1e66f5")
      t.set("method.php", "#1e66f5")
      t.set_extended("module", color: "#7287fd", italic: true)
      t.set("module.builtin", "#ea76cb")
      t.set_extended("namespace", color: "#7287fd", italic: true)
      t.set("number", "#fe640b")
      t.set("number.css", "#fe640b")
      t.set("number.float", "#fe640b")
      t.set("operator", "#04a5e5")
      t.set("parameter", "#e64553")
      t.set("preproc", "#ea76cb")
      t.set("property", "#7287fd")
      t.set("property.class.css", "#df8e1d")
      t.set("property.cpp", "#4c4f69")
      t.set("property.css", "#7287fd")
      t.set("property.id.css", "#1e66f5")
      t.set("property.toml", "#1e66f5")
      t.set("property.typescript", "#7287fd")
      t.set("punctuation", "#7c7f93")
      t.set("punctuation.bracket", "#7c7f93")
      t.set("punctuation.delimiter", "#7c7f93")
      t.set("punctuation.special", "#ea76cb")
      t.set("repeat", "#8839ef")
      t.set("storageclass", "#8839ef")
      t.set("string", "#40a02b")
      t.set("string.documentation", "#179299")
      t.set("string.escape", "#ea76cb")
      t.set("string.plain.css", "#fe640b")
      t.set("string.regex", "#fe640b")
      t.set("string.regexp", "#fe640b")
      t.set("string.special", "#ea76cb")
      t.set("string.special.path", "#ea76cb")
      t.set("string.special.path.gitignore", "#4c4f69")
      t.set("string.special.symbol", "#dd7878")
      t.set("string.special.symbol.ruby", "#dd7878")
      t.set_extended("string.special.url", color: "#dc8a78", underline: true, italic: true)
      t.set("symbol", "#dd7878")
      t.set("symbol.ruby", "#dd7878")
      t.set("tag", "#8839ef")
      t.set_extended("tag.attribute", color: "#179299", italic: true)
      t.set_extended("tag.attribute.tsx", color: "#179299", italic: true)
      t.set("tag.builtin", "#ea76cb")
      t.set("tag.delimiter", "#04a5e5")
      t.set("text", "#4c4f69")
      t.set("text.danger", "#eff1f5")
      t.set("text.diff.add", "#40a02b")
      t.set("text.diff.delete", "#d20f39")
      t.set_extended("text.emphasis", color: "#e64553", italic: true)
      t.set("text.environment", "#ea76cb")
      t.set("text.environment.name", "#1e66f5")
      t.set("text.literal", "#179299")
      t.set("text.math", "#1e66f5")
      t.set("text.note", "#eff1f5")
      t.set_extended("text.reference", color: "#7287fd", bold: true)
      t.set_extended("text.strike", color: "#4c4f69", strikethrough: true)
      t.set_extended("text.strong", color: "#e64553", bold: true)
      t.set_extended("text.title", color: "#1e66f5", bold: true)
      t.set("text.title.1.markdown", "#d20f39")
      t.set("text.title.2.markdown", "#fe640b")
      t.set("text.title.3.markdown", "#df8e1d")
      t.set("text.title.4.markdown", "#40a02b")
      t.set("text.title.5.markdown", "#209fb5")
      t.set("text.title.6.markdown", "#7287fd")
      t.set("text.todo", "#eff1f5")
      t.set("text.todo.checked", "#40a02b")
      t.set("text.todo.unchecked", "#8c8fa1")
      t.set("text.warning", "#eff1f5")
      t.set("type", "#df8e1d")
      t.set("type.builtin", "#df8e1d")
      t.set("type.builtin.c", "#df8e1d")
      t.set("type.builtin.cpp", "#df8e1d")
      t.set("type.css", "#7287fd")
      t.set("type.definition", "#df8e1d")
      t.set("type.qualifier", "#8839ef")
      t.set("type.tag.css", "#8839ef")
      t.set("variable", "#4c4f69")
      t.set("variable.builtin", "#d20f39")
      t.set("variable.member", "#7287fd")
      t.set("variable.parameter", "#e64553")
      t.set("variable.parameter.builtin", "#ea76cb")
      t.resolve
    end

    def catppuccin_mocha : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#cdd6f4", bg: "#eff1f5")
      t.set("attribute", "#fab387")
      t.set("attribute.builtin", "#f5c2e7")
      t.set("boolean", "#fab387")
      t.set("character", "#94e2d5")
      t.set("character.special", "#f5c2e7")
      t.set_extended("comment", color: "#9399b2", italic: true)
      t.set_extended("comment.documentation", color: "#9399b2", italic: true)
      t.set("comment.error", "#1e1e2e")
      t.set("comment.hint", "#1e1e2e")
      t.set("comment.note", "#1e1e2e")
      t.set("comment.todo", "#1e1e2e")
      t.set("comment.warning", "#1e1e2e")
      t.set("comment.warning.gitcommit", "#f9e2af")
      t.set_extended("conditional", color: "#cba6f7", italic: true)
      t.set("constant", "#fab387")
      t.set("constant.builtin", "#fab387")
      t.set("constant.java", "#94e2d5")
      t.set("constant.macro", "#cba6f7")
      t.set("constructor", "#74c7ec")
      t.set("constructor.lua", "#f2cdcd")
      t.set("constructor.tsx", "#b4befe")
      t.set("constructor.typescript", "#b4befe")
      t.set("define", "#f5c2e7")
      t.set("diff.delta", "#89b4fa")
      t.set("diff.minus", "#f38ba8")
      t.set("diff.plus", "#a6e3a1")
      t.set("error", "#f38ba8")
      t.set("exception", "#cba6f7")
      t.set("field", "#b4befe")
      t.set("float", "#fab387")
      t.set("function", "#89b4fa")
      t.set("function.builtin", "#fab387")
      t.set_extended("function.builtin.bash", color: "#f38ba8", italic: true)
      t.set("function.call", "#89b4fa")
      t.set("function.macro", "#94e2d5")
      t.set("function.method", "#89b4fa")
      t.set("function.method.call", "#89b4fa")
      t.set("function.method.call.php", "#89b4fa")
      t.set("function.method.php", "#89b4fa")
      t.set("ibl.indent.char.1", "#313244")
      t.set("ibl.scope.char.1", "#cdd6f4")
      t.set("ibl.whitespace.char.1", "#45475a")
      t.set("include", "#cba6f7")
      t.set("keyword", "#cba6f7")
      t.set_extended("keyword.conditional", color: "#cba6f7", italic: true)
      t.set("keyword.conditional.ternary", "#89dceb")
      t.set("keyword.coroutine", "#cba6f7")
      t.set("keyword.debug", "#cba6f7")
      t.set("keyword.directive", "#f5c2e7")
      t.set("keyword.directive.define", "#f5c2e7")
      t.set("keyword.exception", "#cba6f7")
      t.set("keyword.export", "#89dceb")
      t.set("keyword.function", "#cba6f7")
      t.set("keyword.import", "#cba6f7")
      t.set("keyword.modifier", "#cba6f7")
      t.set("keyword.operator", "#89dceb")
      t.set("keyword.repeat", "#cba6f7")
      t.set("keyword.return", "#cba6f7")
      t.set("keyword.storage", "#cba6f7")
      t.set("keyword.type", "#cba6f7")
      t.set("label", "#74c7ec")
      t.set("label.json", "#89b4fa")
      t.set("markup", "#cdd6f4")
      t.set("markup.environment", "#f5c2e7")
      t.set("markup.environment.name", "#89b4fa")
      t.set_extended("markup.heading", color: "#89b4fa", bold: true)
      t.set("markup.heading.1.markdown", "#f38ba8")
      t.set("markup.heading.2.markdown", "#fab387")
      t.set("markup.heading.3.markdown", "#f9e2af")
      t.set("markup.heading.4.markdown", "#a6e3a1")
      t.set("markup.heading.5.markdown", "#74c7ec")
      t.set("markup.heading.6.markdown", "#b4befe")
      t.set_extended("markup.italic", color: "#eba0ac", italic: true)
      t.set_extended("markup.link", color: "#b4befe", bold: true)
      t.set("markup.link.label", "#74c7ec")
      t.set_extended("markup.link.url", color: "#f5e0dc", underline: true, italic: true)
      t.set("markup.list", "#f5c2e7")
      t.set("markup.list.checked", "#a6e3a1")
      t.set("markup.list.unchecked", "#7f849c")
      t.set("markup.math", "#89b4fa")
      t.set_extended("markup.quote", color: "#eba0ac", bold: true)
      t.set("markup.raw", "#94e2d5")
      t.set_extended("markup.strikethrough", color: "#cdd6f4", strikethrough: true)
      t.set_extended("markup.strong", color: "#eba0ac", bold: true)
      t.set("method", "#89b4fa")
      t.set("method.call", "#89b4fa")
      t.set("method.call.php", "#89b4fa")
      t.set("method.php", "#89b4fa")
      t.set_extended("module", color: "#b4befe", italic: true)
      t.set("module.builtin", "#f5c2e7")
      t.set_extended("namespace", color: "#b4befe", italic: true)
      t.set("number", "#fab387")
      t.set("number.css", "#fab387")
      t.set("number.float", "#fab387")
      t.set("operator", "#89dceb")
      t.set("parameter", "#eba0ac")
      t.set("preproc", "#f5c2e7")
      t.set("property", "#b4befe")
      t.set("property.class.css", "#f9e2af")
      t.set("property.cpp", "#cdd6f4")
      t.set("property.css", "#b4befe")
      t.set("property.id.css", "#89b4fa")
      t.set("property.toml", "#89b4fa")
      t.set("property.typescript", "#b4befe")
      t.set("punctuation", "#9399b2")
      t.set("punctuation.bracket", "#9399b2")
      t.set("punctuation.delimiter", "#9399b2")
      t.set("punctuation.special", "#f5c2e7")
      t.set("repeat", "#cba6f7")
      t.set("storageclass", "#cba6f7")
      t.set("string", "#a6e3a1")
      t.set("string.documentation", "#94e2d5")
      t.set("string.escape", "#f5c2e7")
      t.set("string.plain.css", "#fab387")
      t.set("string.regex", "#fab387")
      t.set("string.regexp", "#fab387")
      t.set("string.special", "#f5c2e7")
      t.set("string.special.path", "#f5c2e7")
      t.set("string.special.path.gitignore", "#cdd6f4")
      t.set("string.special.symbol", "#f2cdcd")
      t.set("string.special.symbol.ruby", "#f2cdcd")
      t.set_extended("string.special.url", color: "#f5e0dc", underline: true, italic: true)
      t.set("symbol", "#f2cdcd")
      t.set("symbol.ruby", "#f2cdcd")
      t.set("tag", "#cba6f7")
      t.set_extended("tag.attribute", color: "#94e2d5", italic: true)
      t.set_extended("tag.attribute.tsx", color: "#94e2d5", italic: true)
      t.set("tag.builtin", "#f5c2e7")
      t.set("tag.delimiter", "#89dceb")
      t.set("text", "#cdd6f4")
      t.set("text.danger", "#1e1e2e")
      t.set("text.diff.add", "#a6e3a1")
      t.set("text.diff.delete", "#f38ba8")
      t.set_extended("text.emphasis", color: "#eba0ac", italic: true)
      t.set("text.environment", "#f5c2e7")
      t.set("text.environment.name", "#89b4fa")
      t.set("text.literal", "#94e2d5")
      t.set("text.math", "#89b4fa")
      t.set("text.note", "#1e1e2e")
      t.set_extended("text.reference", color: "#b4befe", bold: true)
      t.set_extended("text.strike", color: "#cdd6f4", strikethrough: true)
      t.set_extended("text.strong", color: "#eba0ac", bold: true)
      t.set_extended("text.title", color: "#89b4fa", bold: true)
      t.set("text.title.1.markdown", "#f38ba8")
      t.set("text.title.2.markdown", "#fab387")
      t.set("text.title.3.markdown", "#f9e2af")
      t.set("text.title.4.markdown", "#a6e3a1")
      t.set("text.title.5.markdown", "#74c7ec")
      t.set("text.title.6.markdown", "#b4befe")
      t.set("text.todo", "#1e1e2e")
      t.set("text.todo.checked", "#a6e3a1")
      t.set("text.todo.unchecked", "#7f849c")
      t.set("text.warning", "#1e1e2e")
      t.set("type", "#f9e2af")
      t.set("type.builtin", "#f9e2af")
      t.set("type.builtin.c", "#f9e2af")
      t.set("type.builtin.cpp", "#f9e2af")
      t.set("type.css", "#b4befe")
      t.set("type.definition", "#f9e2af")
      t.set("type.qualifier", "#cba6f7")
      t.set("type.tag.css", "#cba6f7")
      t.set("variable", "#cdd6f4")
      t.set("variable.builtin", "#f38ba8")
      t.set("variable.member", "#b4befe")
      t.set("variable.parameter", "#eba0ac")
      t.set("variable.parameter.builtin", "#f5c2e7")
      t.resolve
    end

    def catppuccin_frappe : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c6d0f5", bg: "#1e1e2e")
      t.set("attribute", "#ef9f76")
      t.set("attribute.builtin", "#f4b8e4")
      t.set("boolean", "#ef9f76")
      t.set("character", "#81c8be")
      t.set("character.special", "#f4b8e4")
      t.set_extended("comment", color: "#949cbb", italic: true)
      t.set_extended("comment.documentation", color: "#949cbb", italic: true)
      t.set("comment.error", "#303446")
      t.set("comment.hint", "#303446")
      t.set("comment.note", "#303446")
      t.set("comment.todo", "#303446")
      t.set("comment.warning", "#303446")
      t.set("comment.warning.gitcommit", "#e5c890")
      t.set_extended("conditional", color: "#ca9ee6", italic: true)
      t.set("constant", "#ef9f76")
      t.set("constant.builtin", "#ef9f76")
      t.set("constant.java", "#81c8be")
      t.set("constant.macro", "#ca9ee6")
      t.set("constructor", "#85c1dc")
      t.set("constructor.lua", "#eebebe")
      t.set("constructor.tsx", "#babbf1")
      t.set("constructor.typescript", "#babbf1")
      t.set("define", "#f4b8e4")
      t.set("diff.delta", "#8caaee")
      t.set("diff.minus", "#e78284")
      t.set("diff.plus", "#a6d189")
      t.set("error", "#e78284")
      t.set("exception", "#ca9ee6")
      t.set("field", "#babbf1")
      t.set("float", "#ef9f76")
      t.set("function", "#8caaee")
      t.set("function.builtin", "#ef9f76")
      t.set_extended("function.builtin.bash", color: "#e78284", italic: true)
      t.set("function.call", "#8caaee")
      t.set("function.macro", "#81c8be")
      t.set("function.method", "#8caaee")
      t.set("function.method.call", "#8caaee")
      t.set("function.method.call.php", "#8caaee")
      t.set("function.method.php", "#8caaee")
      t.set("ibl.indent.char.1", "#414559")
      t.set("ibl.scope.char.1", "#c6d0f5")
      t.set("ibl.whitespace.char.1", "#51576d")
      t.set("include", "#ca9ee6")
      t.set("keyword", "#ca9ee6")
      t.set_extended("keyword.conditional", color: "#ca9ee6", italic: true)
      t.set("keyword.conditional.ternary", "#99d1db")
      t.set("keyword.coroutine", "#ca9ee6")
      t.set("keyword.debug", "#ca9ee6")
      t.set("keyword.directive", "#f4b8e4")
      t.set("keyword.directive.define", "#f4b8e4")
      t.set("keyword.exception", "#ca9ee6")
      t.set("keyword.export", "#99d1db")
      t.set("keyword.function", "#ca9ee6")
      t.set("keyword.import", "#ca9ee6")
      t.set("keyword.modifier", "#ca9ee6")
      t.set("keyword.operator", "#99d1db")
      t.set("keyword.repeat", "#ca9ee6")
      t.set("keyword.return", "#ca9ee6")
      t.set("keyword.storage", "#ca9ee6")
      t.set("keyword.type", "#ca9ee6")
      t.set("label", "#85c1dc")
      t.set("label.json", "#8caaee")
      t.set("markup", "#c6d0f5")
      t.set("markup.environment", "#f4b8e4")
      t.set("markup.environment.name", "#8caaee")
      t.set_extended("markup.heading", color: "#8caaee", bold: true)
      t.set("markup.heading.1.markdown", "#e78284")
      t.set("markup.heading.2.markdown", "#ef9f76")
      t.set("markup.heading.3.markdown", "#e5c890")
      t.set("markup.heading.4.markdown", "#a6d189")
      t.set("markup.heading.5.markdown", "#85c1dc")
      t.set("markup.heading.6.markdown", "#babbf1")
      t.set_extended("markup.italic", color: "#ea999c", italic: true)
      t.set_extended("markup.link", color: "#babbf1", bold: true)
      t.set("markup.link.label", "#85c1dc")
      t.set_extended("markup.link.url", color: "#f2d5cf", underline: true, italic: true)
      t.set("markup.list", "#f4b8e4")
      t.set("markup.list.checked", "#a6d189")
      t.set("markup.list.unchecked", "#838ba7")
      t.set("markup.math", "#8caaee")
      t.set_extended("markup.quote", color: "#ea999c", bold: true)
      t.set("markup.raw", "#81c8be")
      t.set_extended("markup.strikethrough", color: "#c6d0f5", strikethrough: true)
      t.set_extended("markup.strong", color: "#ea999c", bold: true)
      t.set("method", "#8caaee")
      t.set("method.call", "#8caaee")
      t.set("method.call.php", "#8caaee")
      t.set("method.php", "#8caaee")
      t.set_extended("module", color: "#babbf1", italic: true)
      t.set("module.builtin", "#f4b8e4")
      t.set_extended("namespace", color: "#babbf1", italic: true)
      t.set("number", "#ef9f76")
      t.set("number.css", "#ef9f76")
      t.set("number.float", "#ef9f76")
      t.set("operator", "#99d1db")
      t.set("parameter", "#ea999c")
      t.set("preproc", "#f4b8e4")
      t.set("property", "#babbf1")
      t.set("property.class.css", "#e5c890")
      t.set("property.cpp", "#c6d0f5")
      t.set("property.css", "#babbf1")
      t.set("property.id.css", "#8caaee")
      t.set("property.toml", "#8caaee")
      t.set("property.typescript", "#babbf1")
      t.set("punctuation", "#949cbb")
      t.set("punctuation.bracket", "#949cbb")
      t.set("punctuation.delimiter", "#949cbb")
      t.set("punctuation.special", "#f4b8e4")
      t.set("repeat", "#ca9ee6")
      t.set("storageclass", "#ca9ee6")
      t.set("string", "#a6d189")
      t.set("string.documentation", "#81c8be")
      t.set("string.escape", "#f4b8e4")
      t.set("string.plain.css", "#ef9f76")
      t.set("string.regex", "#ef9f76")
      t.set("string.regexp", "#ef9f76")
      t.set("string.special", "#f4b8e4")
      t.set("string.special.path", "#f4b8e4")
      t.set("string.special.path.gitignore", "#c6d0f5")
      t.set("string.special.symbol", "#eebebe")
      t.set("string.special.symbol.ruby", "#eebebe")
      t.set_extended("string.special.url", color: "#f2d5cf", underline: true, italic: true)
      t.set("symbol", "#eebebe")
      t.set("symbol.ruby", "#eebebe")
      t.set("tag", "#ca9ee6")
      t.set_extended("tag.attribute", color: "#81c8be", italic: true)
      t.set_extended("tag.attribute.tsx", color: "#81c8be", italic: true)
      t.set("tag.builtin", "#f4b8e4")
      t.set("tag.delimiter", "#99d1db")
      t.set("text", "#c6d0f5")
      t.set("text.danger", "#303446")
      t.set("text.diff.add", "#a6d189")
      t.set("text.diff.delete", "#e78284")
      t.set_extended("text.emphasis", color: "#ea999c", italic: true)
      t.set("text.environment", "#f4b8e4")
      t.set("text.environment.name", "#8caaee")
      t.set("text.literal", "#81c8be")
      t.set("text.math", "#8caaee")
      t.set("text.note", "#303446")
      t.set_extended("text.reference", color: "#babbf1", bold: true)
      t.set_extended("text.strike", color: "#c6d0f5", strikethrough: true)
      t.set_extended("text.strong", color: "#ea999c", bold: true)
      t.set_extended("text.title", color: "#8caaee", bold: true)
      t.set("text.title.1.markdown", "#e78284")
      t.set("text.title.2.markdown", "#ef9f76")
      t.set("text.title.3.markdown", "#e5c890")
      t.set("text.title.4.markdown", "#a6d189")
      t.set("text.title.5.markdown", "#85c1dc")
      t.set("text.title.6.markdown", "#babbf1")
      t.set("text.todo", "#303446")
      t.set("text.todo.checked", "#a6d189")
      t.set("text.todo.unchecked", "#838ba7")
      t.set("text.warning", "#303446")
      t.set("type", "#e5c890")
      t.set("type.builtin", "#e5c890")
      t.set("type.builtin.c", "#e5c890")
      t.set("type.builtin.cpp", "#e5c890")
      t.set("type.css", "#babbf1")
      t.set("type.definition", "#e5c890")
      t.set("type.qualifier", "#ca9ee6")
      t.set("type.tag.css", "#ca9ee6")
      t.set("variable", "#c6d0f5")
      t.set("variable.builtin", "#e78284")
      t.set("variable.member", "#babbf1")
      t.set("variable.parameter", "#ea999c")
      t.set("variable.parameter.builtin", "#f4b8e4")
      t.resolve
    end

    def catppuccin_macchiato : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#cad3f5", bg: "#303446")
      t.set("attribute", "#f5a97f")
      t.set("attribute.builtin", "#f5bde6")
      t.set("boolean", "#f5a97f")
      t.set("character", "#8bd5ca")
      t.set("character.special", "#f5bde6")
      t.set_extended("comment", color: "#939ab7", italic: true)
      t.set_extended("comment.documentation", color: "#939ab7", italic: true)
      t.set("comment.error", "#24273a")
      t.set("comment.hint", "#24273a")
      t.set("comment.note", "#24273a")
      t.set("comment.todo", "#24273a")
      t.set("comment.warning", "#24273a")
      t.set("comment.warning.gitcommit", "#eed49f")
      t.set_extended("conditional", color: "#c6a0f6", italic: true)
      t.set("constant", "#f5a97f")
      t.set("constant.builtin", "#f5a97f")
      t.set("constant.java", "#8bd5ca")
      t.set("constant.macro", "#c6a0f6")
      t.set("constructor", "#7dc4e4")
      t.set("constructor.lua", "#f0c6c6")
      t.set("constructor.tsx", "#b7bdf8")
      t.set("constructor.typescript", "#b7bdf8")
      t.set("define", "#f5bde6")
      t.set("diff.delta", "#8aadf4")
      t.set("diff.minus", "#ed8796")
      t.set("diff.plus", "#a6da95")
      t.set("error", "#ed8796")
      t.set("exception", "#c6a0f6")
      t.set("field", "#b7bdf8")
      t.set("float", "#f5a97f")
      t.set("function", "#8aadf4")
      t.set("function.builtin", "#f5a97f")
      t.set_extended("function.builtin.bash", color: "#ed8796", italic: true)
      t.set("function.call", "#8aadf4")
      t.set("function.macro", "#8bd5ca")
      t.set("function.method", "#8aadf4")
      t.set("function.method.call", "#8aadf4")
      t.set("function.method.call.php", "#8aadf4")
      t.set("function.method.php", "#8aadf4")
      t.set("ibl.indent.char.1", "#363a4f")
      t.set("ibl.scope.char.1", "#cad3f5")
      t.set("ibl.whitespace.char.1", "#494d64")
      t.set("include", "#c6a0f6")
      t.set("keyword", "#c6a0f6")
      t.set_extended("keyword.conditional", color: "#c6a0f6", italic: true)
      t.set("keyword.conditional.ternary", "#91d7e3")
      t.set("keyword.coroutine", "#c6a0f6")
      t.set("keyword.debug", "#c6a0f6")
      t.set("keyword.directive", "#f5bde6")
      t.set("keyword.directive.define", "#f5bde6")
      t.set("keyword.exception", "#c6a0f6")
      t.set("keyword.export", "#91d7e3")
      t.set("keyword.function", "#c6a0f6")
      t.set("keyword.import", "#c6a0f6")
      t.set("keyword.modifier", "#c6a0f6")
      t.set("keyword.operator", "#91d7e3")
      t.set("keyword.repeat", "#c6a0f6")
      t.set("keyword.return", "#c6a0f6")
      t.set("keyword.storage", "#c6a0f6")
      t.set("keyword.type", "#c6a0f6")
      t.set("label", "#7dc4e4")
      t.set("label.json", "#8aadf4")
      t.set("markup", "#cad3f5")
      t.set("markup.environment", "#f5bde6")
      t.set("markup.environment.name", "#8aadf4")
      t.set_extended("markup.heading", color: "#8aadf4", bold: true)
      t.set("markup.heading.1.markdown", "#ed8796")
      t.set("markup.heading.2.markdown", "#f5a97f")
      t.set("markup.heading.3.markdown", "#eed49f")
      t.set("markup.heading.4.markdown", "#a6da95")
      t.set("markup.heading.5.markdown", "#7dc4e4")
      t.set("markup.heading.6.markdown", "#b7bdf8")
      t.set_extended("markup.italic", color: "#ee99a0", italic: true)
      t.set_extended("markup.link", color: "#b7bdf8", bold: true)
      t.set("markup.link.label", "#7dc4e4")
      t.set_extended("markup.link.url", color: "#f4dbd6", underline: true, italic: true)
      t.set("markup.list", "#f5bde6")
      t.set("markup.list.checked", "#a6da95")
      t.set("markup.list.unchecked", "#8087a2")
      t.set("markup.math", "#8aadf4")
      t.set_extended("markup.quote", color: "#ee99a0", bold: true)
      t.set("markup.raw", "#8bd5ca")
      t.set_extended("markup.strikethrough", color: "#cad3f5", strikethrough: true)
      t.set_extended("markup.strong", color: "#ee99a0", bold: true)
      t.set("method", "#8aadf4")
      t.set("method.call", "#8aadf4")
      t.set("method.call.php", "#8aadf4")
      t.set("method.php", "#8aadf4")
      t.set_extended("module", color: "#b7bdf8", italic: true)
      t.set("module.builtin", "#f5bde6")
      t.set_extended("namespace", color: "#b7bdf8", italic: true)
      t.set("number", "#f5a97f")
      t.set("number.css", "#f5a97f")
      t.set("number.float", "#f5a97f")
      t.set("operator", "#91d7e3")
      t.set("parameter", "#ee99a0")
      t.set("preproc", "#f5bde6")
      t.set("property", "#b7bdf8")
      t.set("property.class.css", "#eed49f")
      t.set("property.cpp", "#cad3f5")
      t.set("property.css", "#b7bdf8")
      t.set("property.id.css", "#8aadf4")
      t.set("property.toml", "#8aadf4")
      t.set("property.typescript", "#b7bdf8")
      t.set("punctuation", "#939ab7")
      t.set("punctuation.bracket", "#939ab7")
      t.set("punctuation.delimiter", "#939ab7")
      t.set("punctuation.special", "#f5bde6")
      t.set("repeat", "#c6a0f6")
      t.set("storageclass", "#c6a0f6")
      t.set("string", "#a6da95")
      t.set("string.documentation", "#8bd5ca")
      t.set("string.escape", "#f5bde6")
      t.set("string.plain.css", "#f5a97f")
      t.set("string.regex", "#f5a97f")
      t.set("string.regexp", "#f5a97f")
      t.set("string.special", "#f5bde6")
      t.set("string.special.path", "#f5bde6")
      t.set("string.special.path.gitignore", "#cad3f5")
      t.set("string.special.symbol", "#f0c6c6")
      t.set("string.special.symbol.ruby", "#f0c6c6")
      t.set_extended("string.special.url", color: "#f4dbd6", underline: true, italic: true)
      t.set("symbol", "#f0c6c6")
      t.set("symbol.ruby", "#f0c6c6")
      t.set("tag", "#c6a0f6")
      t.set_extended("tag.attribute", color: "#8bd5ca", italic: true)
      t.set_extended("tag.attribute.tsx", color: "#8bd5ca", italic: true)
      t.set("tag.builtin", "#f5bde6")
      t.set("tag.delimiter", "#91d7e3")
      t.set("text", "#cad3f5")
      t.set("text.danger", "#24273a")
      t.set("text.diff.add", "#a6da95")
      t.set("text.diff.delete", "#ed8796")
      t.set_extended("text.emphasis", color: "#ee99a0", italic: true)
      t.set("text.environment", "#f5bde6")
      t.set("text.environment.name", "#8aadf4")
      t.set("text.literal", "#8bd5ca")
      t.set("text.math", "#8aadf4")
      t.set("text.note", "#24273a")
      t.set_extended("text.reference", color: "#b7bdf8", bold: true)
      t.set_extended("text.strike", color: "#cad3f5", strikethrough: true)
      t.set_extended("text.strong", color: "#ee99a0", bold: true)
      t.set_extended("text.title", color: "#8aadf4", bold: true)
      t.set("text.title.1.markdown", "#ed8796")
      t.set("text.title.2.markdown", "#f5a97f")
      t.set("text.title.3.markdown", "#eed49f")
      t.set("text.title.4.markdown", "#a6da95")
      t.set("text.title.5.markdown", "#7dc4e4")
      t.set("text.title.6.markdown", "#b7bdf8")
      t.set("text.todo", "#24273a")
      t.set("text.todo.checked", "#a6da95")
      t.set("text.todo.unchecked", "#8087a2")
      t.set("text.warning", "#24273a")
      t.set("type", "#eed49f")
      t.set("type.builtin", "#eed49f")
      t.set("type.builtin.c", "#eed49f")
      t.set("type.builtin.cpp", "#eed49f")
      t.set("type.css", "#b7bdf8")
      t.set("type.definition", "#eed49f")
      t.set("type.qualifier", "#c6a0f6")
      t.set("type.tag.css", "#c6a0f6")
      t.set("variable", "#cad3f5")
      t.set("variable.builtin", "#ed8796")
      t.set("variable.member", "#b7bdf8")
      t.set("variable.parameter", "#ee99a0")
      t.set("variable.parameter.builtin", "#f5bde6")
      t.resolve
    end
  end
end
