module TreeSitterManager
  module Themes
    def darcula_darcula : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#a9b7c6", bg: "#2b2b2b")
      t.set("attribute", "#bbb529")
      t.set("attribute.builtin", "#bbb529")
      t.set_extended("boolean", color: "#9876aa", italic: true)
      t.set("character", "#6a8759")
      t.set("character.special", "#bbb529")
      t.set("comment", "#808080")
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#a8c023", italic: true)
      t.set("comment.warning", "#fce094")
      t.set_extended("constant", color: "#9876aa", italic: true)
      t.set("constant.builtin", "#bbb529")
      t.set("constructor", "#bbb529")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#ffc66d")
      t.set("function.builtin", "#bbb529")
      t.set("ibl.indent.char.1", "#606060")
      t.set("ibl.scope.char.1", "#606366")
      t.set("ibl.whitespace.char.1", "#606060")
      t.set("keyword", "#cc7832")
      t.set("label", "#cc7832")
      t.set("markup", "#bbb529")
      t.set("markup.heading", "#bbb529")
      t.set_extended("markup.link", color: "#a9b7c6", underline: true)
      t.set("module", "#cc7832")
      t.set("module.builtin", "#bbb529")
      t.set("number", "#6897bb")
      t.set("number.float", "#6897bb")
      t.set("operator", "#e0e2ea")
      t.set("property", "#a9b7c6")
      t.set("punctuation", "#cc7832")
      t.set("punctuation.special", "#bbb529")
      t.set("string", "#6a8759")
      t.set("string.escape", "#bbb529")
      t.set("string.regexp", "#bbb529")
      t.set("string.special", "#bbb529")
      t.set_extended("string.special.url", color: "#a9b7c6", underline: true)
      t.set("tag", "#cc7832")
      t.set("tag.builtin", "#bbb529")
      t.set("type", "#cc7832")
      t.set("type.builtin", "#bbb529")
      t.set("variable", "#e0e2ea")
      t.set("variable.builtin", "#bbb529")
      t.set("variable.parameter.builtin", "#bbb529")
      t.resolve
    end
  end
end
