module TreeSitterManager
  module Themes
    def dracula_dracula : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#f8f8f2", bg: "#282a36")
      t.set("annotation", "#f1fa8c")
      t.set_extended("attribute", color: "#50fa7b", italic: true)
      t.set("attribute.builtin", "#ff79c6")
      t.set("boolean", "#bd93f9")
      t.set("character", "#ff79c6")
      t.set("character.special", "#ff79c6")
      t.set("comment", "#6272a4")
      t.set("comment.error", "#ff5555")
      t.set("comment.note", "#8be9fd")
      t.set_extended("comment.todo", color: "#8be9fd", bold: true)
      t.set("comment.warning", "#ffb86c")
      t.set("constant", "#bd93f9")
      t.set("constant.builtin", "#bd93f9")
      t.set("constant.macro", "#ff79c6")
      t.set("constructor", "#8be9fd")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("exception", "#bd93f9")
      t.set("field", "#ffb86c")
      t.set("funcion.macro", "#50fa7b")
      t.set("function", "#50fa7b")
      t.set("function.builtin", "#8be9fd")
      t.set("ibl.indent.char.1", "#424450")
      t.set("ibl.scope.char.1", "#6272a4")
      t.set("ibl.whitespace.char.1", "#424450")
      t.set("keyword", "#ff79c6")
      t.set("keyword.function", "#ff79c6")
      t.set("keyword.operator", "#ff79c6")
      t.set_extended("label", color: "#bd93f9", italic: true)
      t.set("markup", "#ff79c6")
      t.set("markup.heading", "#f1fa8c")
      t.set_extended("markup.link", color: "#f8f8f2", underline: true)
      t.set("markup.link.label", "#ff79c6")
      t.set("markup.link.uri", "#f1fa8c")
      t.set("markup.list", "#ff79c6")
      t.set("markup.raw", "#f1fa8c")
      t.set_extended("markup.strikethrough", color: "#f8f8f2", strikethrough: true)
      t.set_extended("markup.strong", color: "#f8f8f2", bold: true)
      t.set_extended("markup.underline", color: "#f8f8f2", underline: true)
      t.set("module", "#ff79c6")
      t.set("module.builtin", "#ff79c6")
      t.set("namespace", "#ff79c6")
      t.set("number", "#bd93f9")
      t.set("number.float", "#bd93f9")
      t.set("operator", "#ff79c6")
      t.set_extended("parameter", color: "#ffb86c", italic: true)
      t.set("parameter.reference", "#ffb86c")
      t.set("property", "#f8f8f2")
      t.set("punctuation", "#f8f8f2")
      t.set("punctuation.bracket", "#f8f8f2")
      t.set("punctuation.delimiter", "#f8f8f2")
      t.set("punctuation.special", "#ff79c6")
      t.set("string", "#f1fa8c")
      t.set("string.escape", "#ff79c6")
      t.set("string.regex", "#ff79c6")
      t.set("string.regexp", "#ff79c6")
      t.set("string.special", "#ff79c6")
      t.set("string.special.symbol", "#bd93f9")
      t.set_extended("string.special.url", color: "#f8f8f2", underline: true)
      t.set("symbol", "#bd93f9")
      t.set("tag", "#8be9fd")
      t.set_extended("tag.attribute", color: "#50fa7b", italic: true)
      t.set("tag.builtin", "#ff79c6")
      t.set("tag.delimiter", "#f8f8f2")
      t.set("text", "#f8f8f2")
      t.set("text.diff.add", "#50fa7b")
      t.set_extended("text.diff.delete", color: "#ff5555", bg: "#21222c")
      t.set("text.emphasis", "#f8f8f2")
      t.set("text.literal", "#f1fa8c")
      t.set_extended("text.strong", color: "#f8f8f2", bold: true)
      t.set("text.title", "#f1fa8c")
      t.set_extended("text.underline", color: "#f8f8f2", underline: true)
      t.set("text.uri", "#f1fa8c")
      t.set_extended("type", color: "#8be9fd", italic: true)
      t.set("type.builtin", "#ff79c6")
      t.set("variable", "#f8f8f2")
      t.set_extended("variable.builtin", color: "#bd93f9", italic: true)
      t.set("variable.member", "#ffb86c")
      t.set_extended("variable.parameter", color: "#ffb86c", italic: true)
      t.set("variable.parameter.builtin", "#ff79c6")
      t.resolve
    end
  end
end
