module TreeSitterManager
  module Themes
    def everblush_everblush : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#dadada", bg: "#141b1e")
      t.set("attribute", "#67b0e8")
      t.set("attribute.builtin", "#6cbfbf")
      t.set("boolean", "#6cbfbf")
      t.set("character", "#67b0e8")
      t.set("character.special", "#dadada")
      t.set_extended("comment", color: "#404749", italic: true)
      t.set("comment.error", "#e57474")
      t.set("comment.note", "#67b0e8")
      t.set("comment.todo", "#e57474")
      t.set("comment.warning", "#e5c76b")
      t.set("conditional", "#e57474")
      t.set("constant", "#6cbfbf")
      t.set("constant.builtin", "#67b0e8")
      t.set("constant.macro", "#e5c76b")
      t.set("constructor", "#67b0e8")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("exception", "#2d3437")
      t.set("field", "#e57474")
      t.set("float", "#2d3437")
      t.set("function", "#e57474")
      t.set("function.builtin", "#67cbe7")
      t.set("function.macro", "#8ccf7e")
      t.set("ibl.indent.char.1", "#e57474")
      t.set("ibl.scope.char.1", "#232a2d")
      t.set("ibl.whitespace.char.1", "#e57474")
      t.set("include", "#ef7e7e")
      t.set("keyword", "#c47fd5")
      t.set("keyword.function", "#67b0e8")
      t.set("keyword.operator", "#71baf2")
      t.set("keyword.return", "#67b0e8")
      t.set("label", "#67b0e8")
      t.set("markup", "#6cbfbf")
      t.set_extended("markup.heading", color: "#67b0e8", bold: true)
      t.set("markup.link", "#e5c76b")
      t.set("method", "#71baf2")
      t.set("module", "#6cbfbf")
      t.set("module.builtin", "#6cbfbf")
      t.set("namespace", "#ef7e7e")
      t.set("number", "#e5c76b")
      t.set("number.float", "#c47fd5")
      t.set("operator", "#b3b9b8")
      t.set("parameter", "#e57474")
      t.set("parameter.reference", "#ef7e7e")
      t.set("property", "#e57474")
      t.set("punctuation", "#dadada")
      t.set("punctuation.bracket", "#b3b9b8")
      t.set("punctuation.delimiter", "#b3b9b8")
      t.set("punctuation.special", "#b3b9b8")
      t.set("repeat", "#f4d67a")
      t.set("string", "#8ccf7e")
      t.set("string.escape", "#67b0e8")
      t.set("string.regex", "#8ccf7e")
      t.set("string.regexp", "#67b0e8")
      t.set("string.special", "#67b0e8")
      t.set("string.special.url", "#e5c76b")
      t.set("symbol", "#e57474")
      t.set("tag", "#67b0e8")
      t.set("tag.attribute", "#e57474")
      t.set("tag.builtin", "#6cbfbf")
      t.set("tag.delimiter", "#b3b9b8")
      t.set("text", "#b3b9b8")
      t.set("text.danger", "#2d3437")
      t.set_extended("text.emphasis", color: "#b3b9b8", italic: true)
      t.set("text.environment.name", "#e5c76b")
      t.set("text.environtment", "#c47fd5")
      t.set_extended("text.literal", color: "#8ccf7e", italic: true)
      t.set("text.math", "#6cbfbf")
      t.set("text.note", "#2d3437")
      t.set("text.reference", "#6cbfbf")
      t.set_extended("text.strike", color: "#b3b9b8", strikethrough: true)
      t.set_extended("text.strong", color: "#b3b9b8", bold: true)
      t.set_extended("text.title", color: "#e5c76b", bold: true)
      t.set_extended("text.underline", color: "#c47fd5", underline: true)
      t.set_extended("text.uri", color: "#e5c76b", underline: true)
      t.set("text.warning", "#232a2d")
      t.set("type", "#e5c76b")
      t.set("type.builtin", "#e5c76b")
      t.set("variable", "#b3b9b8")
      t.set("variable.builtin", "#67b0e8")
      t.set("variable.parameter.builtin", "#6cbfbf")
      t.resolve
    end
  end
end
