module TreeSitterManager
  module Themes
    def everforest_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#ece1d7", bg: "#292522")
      t.set("attribute", "#85b695")
      t.set("attribute.builtin", "#ebc06d")
      t.set("boolean", "#cf9bc2")
      t.set("character", "#7f91b2")
      t.set("character.special", "#ebc06d")
      t.set_extended("comment", color: "#c1a78e", italic: true)
      t.set("comment.documentation", "#c1a78e")
      t.set_extended("comment.error", color: "#c1a78e", bold: true)
      t.set_extended("comment.note", color: "#c1a78e", bold: true)
      t.set_extended("comment.todo", color: "#c1a78e", bold: true)
      t.set_extended("comment.warning", color: "#c1a78e", bold: true)
      t.set("constant", "#ece1d7")
      t.set("constant.builtin", "#b380b0")
      t.set("constant.macro", "#b380b0")
      t.set("constructor", "#ebc06d")
      t.set("function", "#ebc06d")
      t.set("function.builtin", "#ebc06d")
      t.set("function.macro", "#ebc06d")
      t.set("ibl.indent.char.1", "#403a36")
      t.set("ibl.scope.char.1", "#867462")
      t.set("ibl.whitespace.char.1", "#403a36")
      t.set("keyword", "#e49b5d")
      t.set("keyword.directive", "#85b695")
      t.set("keyword.function", "#85b695")
      t.set("keyword.import", "#85b695")
      t.set("label", "#89b3b6")
      t.set("markup", "#ebc06d")
      t.set("markup.heading", "#e49b5d")
      t.set("markup.heading.2", "#ebc06d")
      t.set("markup.heading.3", "#85b695")
      t.set("markup.heading.4", "#89b3b6")
      t.set("markup.link.url", "#7f91b2")
      t.set("markup.list", "#8b7449")
      t.set_extended("markup.quote", color: "#c1a78e", italic: true)
      t.set("markup.raw", "#c1a78e")
      t.set("module", "#ece1d7")
      t.set("module.builtin", "#ece1d7")
      t.set("number", "#cf9bc2")
      t.set("number.float", "#cf9bc2")
      t.set("operator", "#d47766")
      t.set("property", "#ece1d7")
      t.set("punctuation", "#8b7449")
      t.set("punctuation.delimiter", "#bd8183")
      t.set("punctuation.special", "#ebc06d")
      t.set_extended("string", color: "#a3a9ce", italic: true)
      t.set("string.documentation", "#a3a9ce")
      t.set("string.escape", "#7f91b2")
      t.set("string.regexp", "#a3a9ce")
      t.set("string.special", "#89b3b6")
      t.set("string.special.path", "#7f91b2")
      t.set_extended("string.special.symbol", color: "#ece1d7", italic: true)
      t.set("string.special.url", "#7f91b2")
      t.set("tag", "#ebc06d")
      t.set("tag.attribute", "#89b3b6")
      t.set("tag.builtin", "#ebc06d")
      t.set("tag.delimiter", "#8b7449")
      t.set("type", "#7b9695")
      t.set("type.builtin", "#ebc06d")
      t.set("type.qualifier", "#e49b5d")
      t.set("variable", "#ece1d7")
      t.set_extended("variable.builtin", color: "#ece1d7", italic: true)
      t.set("variable.parameter.builtin", "#ebc06d")
      t.resolve
    end

    def everforest_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#54433a", bg: "#292522")
      t.set("attribute", "#3a684a")
      t.set("attribute.builtin", "#a06d00")
      t.set("boolean", "#904180")
      t.set("character", "#7892bd")
      t.set("character.special", "#a06d00")
      t.set_extended("comment", color: "#7d6658", italic: true)
      t.set("comment.documentation", "#7d6658")
      t.set_extended("comment.error", color: "#7d6658", bold: true)
      t.set_extended("comment.note", color: "#7d6658", bold: true)
      t.set_extended("comment.todo", color: "#7d6658", bold: true)
      t.set_extended("comment.warning", color: "#7d6658", bold: true)
      t.set("constant", "#54433a")
      t.set("constant.builtin", "#be79bb")
      t.set("constant.macro", "#be79bb")
      t.set("constructor", "#a06d00")
      t.set("function", "#a06d00")
      t.set("function.builtin", "#a06d00")
      t.set("function.macro", "#a06d00")
      t.set("ibl.indent.char.1", "#d9d3ce")
      t.set("ibl.scope.char.1", "#a98a78")
      t.set("ibl.whitespace.char.1", "#d9d3ce")
      t.set("keyword", "#bc5c00")
      t.set("keyword.directive", "#3a684a")
      t.set("keyword.function", "#3a684a")
      t.set("keyword.import", "#3a684a")
      t.set("label", "#3d6568")
      t.set("markup", "#a06d00")
      t.set("markup.heading", "#bc5c00")
      t.set("markup.heading.2", "#a06d00")
      t.set("markup.heading.3", "#3a684a")
      t.set("markup.heading.4", "#3d6568")
      t.set("markup.link.url", "#7892bd")
      t.set("markup.list", "#cca478")
      t.set_extended("markup.quote", color: "#7d6658", italic: true)
      t.set("markup.raw", "#7d6658")
      t.set("module", "#54433a")
      t.set("module.builtin", "#54433a")
      t.set("number", "#904180")
      t.set("number.float", "#904180")
      t.set("operator", "#bf0021")
      t.set("property", "#54433a")
      t.set("punctuation", "#cca478")
      t.set("punctuation.delimiter", "#c77b8b")
      t.set("punctuation.special", "#a06d00")
      t.set_extended("string", color: "#465aa4", italic: true)
      t.set("string.documentation", "#465aa4")
      t.set("string.escape", "#7892bd")
      t.set("string.regexp", "#465aa4")
      t.set("string.special", "#3d6568")
      t.set("string.special.path", "#7892bd")
      t.set_extended("string.special.symbol", color: "#54433a", italic: true)
      t.set("string.special.url", "#7892bd")
      t.set("tag", "#a06d00")
      t.set("tag.attribute", "#3d6568")
      t.set("tag.builtin", "#a06d00")
      t.set("tag.delimiter", "#cca478")
      t.set("type", "#739797")
      t.set("type.builtin", "#a06d00")
      t.set("type.qualifier", "#bc5c00")
      t.set("variable", "#54433a")
      t.set_extended("variable.builtin", color: "#54433a", italic: true)
      t.set("variable.parameter.builtin", "#a06d00")
      t.resolve
    end
  end
end
