module TreeSitterManager
  module Themes
    def falcon_falcon : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#b4b4b9", bg: "#020221")
      t.set("annotation", "#cfc1b2")
      t.set("attribute", "#cfc1b2")
      t.set("attribute.builtin", "#ff761a")
      t.set_extended("boolean", color: "#b4b4b9", italic: true)
      t.set("character", "#c8d0e3")
      t.set("character.special", "#ff761a")
      t.set_extended("comment", color: "#787882", italic: true)
      t.set("comment.error", "#9e1e00")
      t.set("comment.note", "#787882")
      t.set("comment.todo", "#020221")
      t.set("comment.warning", "#bc8f3f")
      t.set("conditional", "#ffc552")
      t.set_extended("constant", color: "#b4b4b9", bold: true)
      t.set_extended("constant.builtin", color: "#b4b4b9", italic: true)
      t.set("constant.macro", "#cfc1b2")
      t.set_extended("constructor", color: "#b4b4b9", bold: true)
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#ffc552")
      t.set("exception", "#ffc552")
      t.set("field", "#99a4bc")
      t.set("float", "#b4b4b9")
      t.set("function", "#ffc552")
      t.set("function.builtin", "#ff761a")
      t.set("function.macro", "#cfc1b2")
      t.set("ibl.indent.char.1", "#36363a")
      t.set("ibl.scope.char.1", "#57575e")
      t.set("ibl.whitespace.char.1", "#36363a")
      t.set("include", "#cfc1b2")
      t.set("keyword", "#ffc552")
      t.set("keyword.function", "#cfc1b2")
      t.set("keyword.operator", "#ff761a")
      t.set("keyword.return", "#ff761a")
      t.set("label", "#99a4bc")
      t.set("literal", "#c8d0e3")
      t.set("markup", "#ff761a")
      t.set("markup.heading", "#cfc1b2")
      t.set_extended("markup.link", color: "#99a4bc", underline: true)
      t.set("method", "#b4b4b9")
      t.set("module", "#dfdfe5")
      t.set("module.builtin", "#ff761a")
      t.set("namespace", "#cfc1b2")
      t.set("note", "#020221")
      t.set("number", "#b4b4b9")
      t.set("number.float", "#b4b4b9")
      t.set("operator", "#ff761a")
      t.set("parameter", "#99a4bc")
      t.set("parameter.reference", "#99a4bc")
      t.set("property", "#99a4bc")
      t.set("punctuation", "#dfdfe5")
      t.set("punctuation.bracket", "#dfdfe5")
      t.set("punctuation.delimiter", "#dfdfe5")
      t.set("punctuation.special", "#dfdfe5")
      t.set("repeat", "#99a4bc")
      t.set("string", "#c8d0e3")
      t.set("string.escape", "#ff761a")
      t.set("string.regex", "#c8d0e3")
      t.set("string.regexp", "#c8d0e3")
      t.set("string.special", "#c8d0e3")
      t.set_extended("string.special.url", color: "#99a4bc", underline: true)
      t.set("structure", "#dfdfe5")
      t.set("symbol", "#99a4bc")
      t.set("tag", "#ff761a")
      t.set("tag.attribute", "#b4b4b9")
      t.set("tag.builtin", "#ff761a")
      t.set("tag.delimiter", "#dfdfe5")
      t.set("title", "#cfc1b2")
      t.set("type", "#dfdfe5")
      t.set("type.builtin", "#dfdfe5")
      t.set_extended("uri", color: "#99a4bc", underline: true)
      t.set("variable", "#e0e2ea")
      t.set("variable.builtin", "#ff761a")
      t.set("variable.parameter.builtin", "#ff761a")
      t.set("warning", "#bc8f3f")
      t.resolve
    end
  end
end
