module TreeSitterManager
  module Themes
    def github_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#e6edf3", bg: "#30363d")
      t.set("attribute", "#79c0ff")
      t.set("attribute.builtin", "#e6edf3")
      t.set("boolean", "#79c0ff")
      t.set("character", "#a5d6ff")
      t.set("character.special", "#e6edf3")
      t.set("comment", "#8b949e")
      t.set("comment.error", "#30363d")
      t.set("comment.hint", "#30363d")
      t.set("comment.info", "#30363d")
      t.set("comment.note", "#2f81f7")
      t.set("comment.todo", "#30363d")
      t.set("comment.warning", "#30363d")
      t.set("conceal", "#8b949e")
      t.set("constant", "#79c0ff")
      t.set("constant.builtin", "#79c0ff")
      t.set("constant.builtin.rust", "#ffa657")
      t.set("constant.html", "#7ee787")
      t.set("constant.macro", "#ff7b72")
      t.set("constructor", "#ffa657")
      t.set("constructor.lua", "#e6edf3")
      t.set("diff.delta", "#d29922")
      t.set("diff.minus", "#f85149")
      t.set("diff.plus", "#3fb950")
      t.set("function", "#d2a8ff")
      t.set("function.builtin.bash", "#ff7b72")
      t.set("function.builtin.lua", "#79c0ff")
      t.set("function.builtin.make", "#79c0ff")
      t.set("function.call.bash", "#79c0ff")
      t.set("ibl.indent.char.1", "#484f58")
      t.set("ibl.scope.char.1", "#6e7681")
      t.set("ibl.whitespace.char.1", "#484f58")
      t.set("keyword", "#ff7b72")
      t.set("keyword.directive.rust", "#79c0ff")
      t.set("keyword.exception", "#79c0ff")
      t.set("keyword.function", "#ff7b72")
      t.set("keyword.operator", "#ff7b72")
      t.set("label", "#7ee787")
      t.set("label.ruby", "#79c0ff")
      t.set("label.vimdoc", "#ff7b72")
      t.set("markup", "#e6edf3")
      t.set("markup.environment", "#ff7b72")
      t.set("markup.environment.name", "#d2a8ff")
      t.set_extended("markup.heading", color: "#79c0ff", bold: true)
      t.set("markup.heading.html", "#e6edf3")
      t.set_extended("markup.italic", color: "#e6edf3", italic: true)
      t.set_extended("markup.link", color: "#e6edf3", underline: true)
      t.set("markup.link.label", "#e6edf3")
      t.set_extended("markup.link.uri", color: "#79c0ff", underline: true, italic: true)
      t.set("markup.list", "#79c0ff")
      t.set("markup.list.checked", "#3fb950")
      t.set("markup.list.luadoc", "#e6edf3")
      t.set("markup.list.unchecked", "#6e7681")
      t.set("markup.quote.markdown", "#7ee787")
      t.set_extended("markup.raw", color: "#e6edf3", italic: true)
      t.set_extended("markup.strikethrough", color: "#e6edf3", strikethrough: true)
      t.set_extended("markup.strong", color: "#e6edf3", bold: true)
      t.set("module", "#ff7b72")
      t.set("module.builtin", "#79c0ff")
      t.set("module.builtin.lua", "#79c0ff")
      t.set("module.c_sharp", "#ffa657")
      t.set("module.elixir", "#ffa657")
      t.set("number", "#79c0ff")
      t.set("number.float", "#79c0ff")
      t.set("operator", "#79c0ff")
      t.set("operator.bash", "#ff7b72")
      t.set("operator.lua", "#ff7b72")
      t.set("operator.luadoc", "#e6edf3")
      t.set("property", "#79c0ff")
      t.set("property.json", "#7ee787")
      t.set("property.lua", "#e6edf3")
      t.set("property.luadoc", "#e6edf3")
      t.set("property.scss", "#79c0ff")
      t.set("property.yaml", "#7ee787")
      t.set("punctuation", "#e6edf3")
      t.set("punctuation.bracket", "#e6edf3")
      t.set("punctuation.delimiter.bash", "#ff7b72")
      t.set("punctuation.delimiter.markdown", "#e6edf3")
      t.set("punctuation.delimiter.markdown_inline", "#e6edf3")
      t.set("punctuation.special", "#e6edf3")
      t.set("string", "#a5d6ff")
      t.set_extended("string.escape", color: "#a5d6ff", bold: true)
      t.set("string.regexp", "#a5d6ff")
      t.set("string.special", "#e6edf3")
      t.set("string.special.path.gitignore", "#d2a8ff")
      t.set("string.special.path.nix", "#a5d6ff")
      t.set("string.special.symbol", "#79c0ff")
      t.set("string.special.symbol.make", "#d2a8ff")
      t.set("string.special.symbol.ruby", "#79c0ff")
      t.set_extended("string.special.url", color: "#79c0ff", underline: true, italic: true)
      t.set("tag", "#7ee787")
      t.set("tag.attribute", "#79c0ff")
      t.set("tag.builtin", "#7ee787")
      t.set("type", "#ffa657")
      t.set("type.builtin", "#ff7b72")
      t.set("type.builtin.python", "#79c0ff")
      t.set("type.css", "#7ee787")
      t.set("type.qualifier", "#ff7b72")
      t.set("type.sql", "#e6edf3")
      t.set("variable", "#e6edf3")
      t.set("variable.builtin", "#79c0ff")
      t.set("variable.builtin.python", "#79c0ff")
      t.set("variable.member", "#79c0ff")
      t.set("variable.member.luadoc", "#e6edf3")
      t.set("variable.member.nix", "#79c0ff")
      t.set("variable.member.python", "#e6edf3")
      t.set("variable.member.sql", "#79c0ff")
      t.set("variable.parameter", "#e6edf3")
      t.set("variable.parameter.builtin", "#79c0ff")
      t.set("variable.parameter.nix", "#e6edf3")
      t.set("variable.parameter.vimdoc", "#ffa657")
      t.set("variable.scss", "#e6edf3")
      t.set("variable.sql", "#79c0ff")
      t.resolve
    end

    def github_dark_colorblind : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c9d1d9", bg: "#30363d")
      t.set("attribute", "#79c0ff")
      t.set("attribute.builtin", "#c9d1d9")
      t.set("boolean", "#79c0ff")
      t.set("character", "#a5d6ff")
      t.set("character.special", "#c9d1d9")
      t.set("comment", "#8b949e")
      t.set("comment.error", "#0d1117")
      t.set("comment.hint", "#0d1117")
      t.set("comment.info", "#0d1117")
      t.set("comment.note", "#58a6ff")
      t.set("comment.todo", "#0d1117")
      t.set("comment.warning", "#0d1117")
      t.set("conceal", "#8b949e")
      t.set("constant", "#79c0ff")
      t.set("constant.builtin", "#79c0ff")
      t.set("constant.builtin.rust", "#fdac54")
      t.set("constant.html", "#a5d6ff")
      t.set("constant.macro", "#ec8e2c")
      t.set("constructor", "#fdac54")
      t.set("constructor.lua", "#c9d1d9")
      t.set("diff.delta", "#d29922")
      t.set("diff.minus", "#d47616")
      t.set("diff.plus", "#58a6ff")
      t.set("function", "#d2a8ff")
      t.set("function.builtin.bash", "#ec8e2c")
      t.set("function.builtin.lua", "#79c0ff")
      t.set("function.builtin.make", "#79c0ff")
      t.set("function.call.bash", "#79c0ff")
      t.set("ibl.indent.char.1", "#161b22")
      t.set("ibl.scope.char.1", "#6e7681")
      t.set("ibl.whitespace.char.1", "#161b22")
      t.set("keyword", "#ec8e2c")
      t.set("keyword.directive.rust", "#79c0ff")
      t.set("keyword.exception", "#79c0ff")
      t.set("keyword.function", "#ec8e2c")
      t.set("keyword.operator", "#ec8e2c")
      t.set("label", "#a5d6ff")
      t.set("label.ruby", "#79c0ff")
      t.set("label.vimdoc", "#ec8e2c")
      t.set("markup", "#c9d1d9")
      t.set("markup.environment", "#ec8e2c")
      t.set("markup.environment.name", "#d2a8ff")
      t.set_extended("markup.heading", color: "#79c0ff", bold: true)
      t.set("markup.heading.html", "#c9d1d9")
      t.set_extended("markup.italic", color: "#c9d1d9", italic: true)
      t.set_extended("markup.link", color: "#c9d1d9", underline: true)
      t.set("markup.link.label", "#c9d1d9")
      t.set_extended("markup.link.uri", color: "#79c0ff", underline: true, italic: true)
      t.set("markup.list", "#79c0ff")
      t.set("markup.list.checked", "#58a6ff")
      t.set("markup.list.luadoc", "#c9d1d9")
      t.set("markup.list.unchecked", "#6e7681")
      t.set("markup.quote.markdown", "#a5d6ff")
      t.set_extended("markup.raw", color: "#c9d1d9", italic: true)
      t.set_extended("markup.strikethrough", color: "#c9d1d9", strikethrough: true)
      t.set_extended("markup.strong", color: "#c9d1d9", bold: true)
      t.set("module", "#ec8e2c")
      t.set("module.builtin", "#79c0ff")
      t.set("module.builtin.lua", "#79c0ff")
      t.set("module.c_sharp", "#fdac54")
      t.set("module.elixir", "#fdac54")
      t.set("number", "#79c0ff")
      t.set("number.float", "#79c0ff")
      t.set("operator", "#79c0ff")
      t.set("operator.bash", "#ec8e2c")
      t.set("operator.lua", "#ec8e2c")
      t.set("operator.luadoc", "#c9d1d9")
      t.set("property", "#79c0ff")
      t.set("property.json", "#a5d6ff")
      t.set("property.lua", "#c9d1d9")
      t.set("property.luadoc", "#c9d1d9")
      t.set("property.scss", "#79c0ff")
      t.set("property.yaml", "#a5d6ff")
      t.set("punctuation", "#c9d1d9")
      t.set("punctuation.bracket", "#c9d1d9")
      t.set("punctuation.delimiter.bash", "#ec8e2c")
      t.set("punctuation.delimiter.markdown", "#c9d1d9")
      t.set("punctuation.delimiter.markdown_inline", "#c9d1d9")
      t.set("punctuation.special", "#c9d1d9")
      t.set("string", "#a5d6ff")
      t.set_extended("string.escape", color: "#a5d6ff", bold: true)
      t.set("string.regexp", "#a5d6ff")
      t.set("string.special", "#c9d1d9")
      t.set("string.special.path.gitignore", "#d2a8ff")
      t.set("string.special.path.nix", "#a5d6ff")
      t.set("string.special.symbol", "#79c0ff")
      t.set("string.special.symbol.make", "#d2a8ff")
      t.set("string.special.symbol.ruby", "#79c0ff")
      t.set_extended("string.special.url", color: "#79c0ff", underline: true, italic: true)
      t.set("tag", "#a5d6ff")
      t.set("tag.attribute", "#79c0ff")
      t.set("tag.builtin", "#a5d6ff")
      t.set("type", "#fdac54")
      t.set("type.builtin", "#ec8e2c")
      t.set("type.builtin.python", "#79c0ff")
      t.set("type.css", "#a5d6ff")
      t.set("type.qualifier", "#ec8e2c")
      t.set("type.sql", "#c9d1d9")
      t.set("variable", "#c9d1d9")
      t.set("variable.builtin", "#79c0ff")
      t.set("variable.builtin.python", "#79c0ff")
      t.set("variable.member", "#79c0ff")
      t.set("variable.member.luadoc", "#c9d1d9")
      t.set("variable.member.nix", "#79c0ff")
      t.set("variable.member.python", "#c9d1d9")
      t.set("variable.member.sql", "#79c0ff")
      t.set("variable.parameter", "#c9d1d9")
      t.set("variable.parameter.builtin", "#79c0ff")
      t.set("variable.parameter.nix", "#c9d1d9")
      t.set("variable.parameter.vimdoc", "#fdac54")
      t.set("variable.scss", "#c9d1d9")
      t.set("variable.sql", "#79c0ff")
      t.resolve
    end

    def github_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#1f2328", bg: "#0d1117")
      t.set("attribute", "#0550ae")
      t.set("attribute.builtin", "#1f2328")
      t.set("boolean", "#0550ae")
      t.set("character", "#0a3069")
      t.set("character.special", "#1f2328")
      t.set("comment", "#57606a")
      t.set("comment.error", "#ffffff")
      t.set("comment.hint", "#ffffff")
      t.set("comment.info", "#ffffff")
      t.set("comment.note", "#0969da")
      t.set("comment.todo", "#ffffff")
      t.set("comment.warning", "#ffffff")
      t.set("conceal", "#6e7781")
      t.set("constant", "#0550ae")
      t.set("constant.builtin", "#0550ae")
      t.set("constant.builtin.rust", "#953800")
      t.set("constant.html", "#116329")
      t.set("constant.macro", "#cf222e")
      t.set("constructor", "#953800")
      t.set("constructor.lua", "#1f2328")
      t.set("diff.delta", "#9a6700")
      t.set("diff.minus", "#d1242f")
      t.set("diff.plus", "#1a7f37")
      t.set("function", "#6639ba")
      t.set("function.builtin.bash", "#cf222e")
      t.set("function.builtin.lua", "#0550ae")
      t.set("function.builtin.make", "#0550ae")
      t.set("function.call.bash", "#0550ae")
      t.set("ibl.indent.char.1", "#e7eaf0")
      t.set("ibl.scope.char.1", "#6e7781")
      t.set("ibl.whitespace.char.1", "#e7eaf0")
      t.set("keyword", "#cf222e")
      t.set("keyword.directive.rust", "#0550ae")
      t.set("keyword.exception", "#0550ae")
      t.set("keyword.function", "#cf222e")
      t.set("keyword.operator", "#cf222e")
      t.set("label", "#116329")
      t.set("label.ruby", "#0550ae")
      t.set("label.vimdoc", "#cf222e")
      t.set("markup", "#1f2328")
      t.set("markup.environment", "#cf222e")
      t.set("markup.environment.name", "#6639ba")
      t.set_extended("markup.heading", color: "#0550ae", bold: true)
      t.set("markup.heading.html", "#1f2328")
      t.set_extended("markup.italic", color: "#1f2328", italic: true)
      t.set_extended("markup.link", color: "#1f2328", underline: true)
      t.set("markup.link.label", "#1f2328")
      t.set_extended("markup.link.uri", color: "#0550ae", underline: true, italic: true)
      t.set("markup.list", "#0550ae")
      t.set("markup.list.checked", "#116329")
      t.set("markup.list.luadoc", "#1f2328")
      t.set("markup.list.unchecked", "#57606a")
      t.set("markup.quote.markdown", "#116329")
      t.set_extended("markup.raw", color: "#1f2328", italic: true)
      t.set_extended("markup.strikethrough", color: "#1f2328", strikethrough: true)
      t.set_extended("markup.strong", color: "#1f2328", bold: true)
      t.set("module", "#cf222e")
      t.set("module.builtin", "#0550ae")
      t.set("module.builtin.lua", "#0550ae")
      t.set("module.c_sharp", "#953800")
      t.set("module.elixir", "#953800")
      t.set("number", "#0550ae")
      t.set("number.float", "#0550ae")
      t.set("operator", "#0550ae")
      t.set("operator.bash", "#cf222e")
      t.set("operator.lua", "#cf222e")
      t.set("operator.luadoc", "#1f2328")
      t.set("property", "#0550ae")
      t.set("property.json", "#116329")
      t.set("property.lua", "#1f2328")
      t.set("property.luadoc", "#1f2328")
      t.set("property.scss", "#0550ae")
      t.set("property.yaml", "#116329")
      t.set("punctuation", "#1f2328")
      t.set("punctuation.bracket", "#1f2328")
      t.set("punctuation.delimiter.bash", "#cf222e")
      t.set("punctuation.delimiter.markdown", "#1f2328")
      t.set("punctuation.delimiter.markdown_inline", "#1f2328")
      t.set("punctuation.special", "#1f2328")
      t.set("string", "#0a3069")
      t.set_extended("string.escape", color: "#0a3069", bold: true)
      t.set("string.regexp", "#0a3069")
      t.set("string.special", "#1f2328")
      t.set("string.special.path.gitignore", "#6639ba")
      t.set("string.special.path.nix", "#0a3069")
      t.set("string.special.symbol", "#0550ae")
      t.set("string.special.symbol.make", "#6639ba")
      t.set("string.special.symbol.ruby", "#0550ae")
      t.set_extended("string.special.url", color: "#0550ae", underline: true, italic: true)
      t.set("tag", "#116329")
      t.set("tag.attribute", "#0550ae")
      t.set("tag.builtin", "#116329")
      t.set("type", "#953800")
      t.set("type.builtin", "#cf222e")
      t.set("type.builtin.python", "#0550ae")
      t.set("type.css", "#116329")
      t.set("type.qualifier", "#cf222e")
      t.set("type.sql", "#1f2328")
      t.set("variable", "#1f2328")
      t.set("variable.builtin", "#0550ae")
      t.set("variable.builtin.python", "#0550ae")
      t.set("variable.member", "#0550ae")
      t.set("variable.member.luadoc", "#1f2328")
      t.set("variable.member.nix", "#0550ae")
      t.set("variable.member.python", "#1f2328")
      t.set("variable.member.sql", "#0550ae")
      t.set("variable.parameter", "#1f2328")
      t.set("variable.parameter.builtin", "#0550ae")
      t.set("variable.parameter.nix", "#1f2328")
      t.set("variable.parameter.vimdoc", "#953800")
      t.set("variable.scss", "#1f2328")
      t.set("variable.sql", "#0550ae")
      t.resolve
    end

    def github_dark_dimmed : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#adbac7", bg: "#ffffff")
      t.set("attribute", "#6cb6ff")
      t.set("attribute.builtin", "#adbac7")
      t.set("boolean", "#6cb6ff")
      t.set("character", "#96d0ff")
      t.set("character.special", "#adbac7")
      t.set("comment", "#768390")
      t.set("comment.error", "#22272e")
      t.set("comment.hint", "#22272e")
      t.set("comment.info", "#22272e")
      t.set("comment.note", "#539bf5")
      t.set("comment.todo", "#22272e")
      t.set("comment.warning", "#22272e")
      t.set("conceal", "#768390")
      t.set("constant", "#6cb6ff")
      t.set("constant.builtin", "#6cb6ff")
      t.set("constant.builtin.rust", "#f69d50")
      t.set("constant.html", "#8ddb8c")
      t.set("constant.macro", "#f47067")
      t.set("constructor", "#f69d50")
      t.set("constructor.lua", "#adbac7")
      t.set("diff.delta", "#c69026")
      t.set("diff.minus", "#e5534b")
      t.set("diff.plus", "#57ab5a")
      t.set("function", "#dcbdfb")
      t.set("function.builtin.bash", "#f47067")
      t.set("function.builtin.lua", "#6cb6ff")
      t.set("function.builtin.make", "#6cb6ff")
      t.set("function.call.bash", "#6cb6ff")
      t.set("ibl.indent.char.1", "#30363d")
      t.set("ibl.scope.char.1", "#636e7b")
      t.set("ibl.whitespace.char.1", "#30363d")
      t.set("keyword", "#f47067")
      t.set("keyword.directive.rust", "#6cb6ff")
      t.set("keyword.exception", "#6cb6ff")
      t.set("keyword.function", "#f47067")
      t.set("keyword.operator", "#f47067")
      t.set("label", "#8ddb8c")
      t.set("label.ruby", "#6cb6ff")
      t.set("label.vimdoc", "#f47067")
      t.set("markup", "#adbac7")
      t.set("markup.environment", "#f47067")
      t.set("markup.environment.name", "#dcbdfb")
      t.set_extended("markup.heading", color: "#6cb6ff", bold: true)
      t.set("markup.heading.html", "#adbac7")
      t.set_extended("markup.italic", color: "#adbac7", italic: true)
      t.set_extended("markup.link", color: "#adbac7", underline: true)
      t.set("markup.link.label", "#adbac7")
      t.set_extended("markup.link.uri", color: "#6cb6ff", underline: true, italic: true)
      t.set("markup.list", "#6cb6ff")
      t.set("markup.list.checked", "#57ab5a")
      t.set("markup.list.luadoc", "#adbac7")
      t.set("markup.list.unchecked", "#636e7b")
      t.set("markup.quote.markdown", "#8ddb8c")
      t.set_extended("markup.raw", color: "#adbac7", italic: true)
      t.set_extended("markup.strikethrough", color: "#adbac7", strikethrough: true)
      t.set_extended("markup.strong", color: "#adbac7", bold: true)
      t.set("module", "#f47067")
      t.set("module.builtin", "#6cb6ff")
      t.set("module.builtin.lua", "#6cb6ff")
      t.set("module.c_sharp", "#f69d50")
      t.set("module.elixir", "#f69d50")
      t.set("number", "#6cb6ff")
      t.set("number.float", "#6cb6ff")
      t.set("operator", "#6cb6ff")
      t.set("operator.bash", "#f47067")
      t.set("operator.lua", "#f47067")
      t.set("operator.luadoc", "#adbac7")
      t.set("property", "#6cb6ff")
      t.set("property.json", "#8ddb8c")
      t.set("property.lua", "#adbac7")
      t.set("property.luadoc", "#adbac7")
      t.set("property.scss", "#6cb6ff")
      t.set("property.yaml", "#8ddb8c")
      t.set("punctuation", "#adbac7")
      t.set("punctuation.bracket", "#adbac7")
      t.set("punctuation.delimiter.bash", "#f47067")
      t.set("punctuation.delimiter.markdown", "#adbac7")
      t.set("punctuation.delimiter.markdown_inline", "#adbac7")
      t.set("punctuation.special", "#adbac7")
      t.set("string", "#96d0ff")
      t.set_extended("string.escape", color: "#96d0ff", bold: true)
      t.set("string.regexp", "#96d0ff")
      t.set("string.special", "#adbac7")
      t.set("string.special.path.gitignore", "#dcbdfb")
      t.set("string.special.path.nix", "#96d0ff")
      t.set("string.special.symbol", "#6cb6ff")
      t.set("string.special.symbol.make", "#dcbdfb")
      t.set("string.special.symbol.ruby", "#6cb6ff")
      t.set_extended("string.special.url", color: "#6cb6ff", underline: true, italic: true)
      t.set("tag", "#8ddb8c")
      t.set("tag.attribute", "#6cb6ff")
      t.set("tag.builtin", "#8ddb8c")
      t.set("type", "#f69d50")
      t.set("type.builtin", "#f47067")
      t.set("type.builtin.python", "#6cb6ff")
      t.set("type.css", "#8ddb8c")
      t.set("type.qualifier", "#f47067")
      t.set("type.sql", "#adbac7")
      t.set("variable", "#adbac7")
      t.set("variable.builtin", "#6cb6ff")
      t.set("variable.builtin.python", "#6cb6ff")
      t.set("variable.member", "#6cb6ff")
      t.set("variable.member.luadoc", "#adbac7")
      t.set("variable.member.nix", "#6cb6ff")
      t.set("variable.member.python", "#adbac7")
      t.set("variable.member.sql", "#6cb6ff")
      t.set("variable.parameter", "#adbac7")
      t.set("variable.parameter.builtin", "#6cb6ff")
      t.set("variable.parameter.nix", "#adbac7")
      t.set("variable.parameter.vimdoc", "#f69d50")
      t.set("variable.scss", "#adbac7")
      t.set("variable.sql", "#6cb6ff")
      t.resolve
    end

    def github_dark_default : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#e6edf3", bg: "#22272e")
      t.set("attribute", "#79c0ff")
      t.set("attribute.builtin", "#e6edf3")
      t.set("boolean", "#79c0ff")
      t.set("character", "#a5d6ff")
      t.set("character.special", "#e6edf3")
      t.set("comment", "#8b949e")
      t.set("comment.error", "#0d1117")
      t.set("comment.hint", "#0d1117")
      t.set("comment.info", "#0d1117")
      t.set("comment.note", "#2f81f7")
      t.set("comment.todo", "#0d1117")
      t.set("comment.warning", "#0d1117")
      t.set("conceal", "#8b949e")
      t.set("constant", "#79c0ff")
      t.set("constant.builtin", "#79c0ff")
      t.set("constant.builtin.rust", "#ffa657")
      t.set("constant.html", "#7ee787")
      t.set("constant.macro", "#ff7b72")
      t.set("constructor", "#ffa657")
      t.set("constructor.lua", "#e6edf3")
      t.set("diff.delta", "#d29922")
      t.set("diff.minus", "#f85149")
      t.set("diff.plus", "#3fb950")
      t.set("function", "#d2a8ff")
      t.set("function.builtin.bash", "#ff7b72")
      t.set("function.builtin.lua", "#79c0ff")
      t.set("function.builtin.make", "#79c0ff")
      t.set("function.call.bash", "#79c0ff")
      t.set("ibl.indent.char.1", "#484f58")
      t.set("ibl.scope.char.1", "#6e7681")
      t.set("ibl.whitespace.char.1", "#484f58")
      t.set("keyword", "#ff7b72")
      t.set("keyword.directive.rust", "#79c0ff")
      t.set("keyword.exception", "#79c0ff")
      t.set("keyword.function", "#ff7b72")
      t.set("keyword.operator", "#ff7b72")
      t.set("label", "#7ee787")
      t.set("label.ruby", "#79c0ff")
      t.set("label.vimdoc", "#ff7b72")
      t.set("markup", "#e6edf3")
      t.set("markup.environment", "#ff7b72")
      t.set("markup.environment.name", "#d2a8ff")
      t.set_extended("markup.heading", color: "#79c0ff", bold: true)
      t.set("markup.heading.html", "#e6edf3")
      t.set_extended("markup.italic", color: "#e6edf3", italic: true)
      t.set_extended("markup.link", color: "#e6edf3", underline: true)
      t.set("markup.link.label", "#e6edf3")
      t.set_extended("markup.link.uri", color: "#79c0ff", underline: true, italic: true)
      t.set("markup.list", "#79c0ff")
      t.set("markup.list.checked", "#3fb950")
      t.set("markup.list.luadoc", "#e6edf3")
      t.set("markup.list.unchecked", "#6e7681")
      t.set("markup.quote.markdown", "#7ee787")
      t.set_extended("markup.raw", color: "#e6edf3", italic: true)
      t.set_extended("markup.strikethrough", color: "#e6edf3", strikethrough: true)
      t.set_extended("markup.strong", color: "#e6edf3", bold: true)
      t.set("module", "#ff7b72")
      t.set("module.builtin", "#79c0ff")
      t.set("module.builtin.lua", "#79c0ff")
      t.set("module.c_sharp", "#ffa657")
      t.set("module.elixir", "#ffa657")
      t.set("number", "#79c0ff")
      t.set("number.float", "#79c0ff")
      t.set("operator", "#79c0ff")
      t.set("operator.bash", "#ff7b72")
      t.set("operator.lua", "#ff7b72")
      t.set("operator.luadoc", "#e6edf3")
      t.set("property", "#79c0ff")
      t.set("property.json", "#7ee787")
      t.set("property.lua", "#e6edf3")
      t.set("property.luadoc", "#e6edf3")
      t.set("property.scss", "#79c0ff")
      t.set("property.yaml", "#7ee787")
      t.set("punctuation", "#e6edf3")
      t.set("punctuation.bracket", "#e6edf3")
      t.set("punctuation.delimiter.bash", "#ff7b72")
      t.set("punctuation.delimiter.markdown", "#e6edf3")
      t.set("punctuation.delimiter.markdown_inline", "#e6edf3")
      t.set("punctuation.special", "#e6edf3")
      t.set("string", "#a5d6ff")
      t.set_extended("string.escape", color: "#a5d6ff", bold: true)
      t.set("string.regexp", "#a5d6ff")
      t.set("string.special", "#e6edf3")
      t.set("string.special.path.gitignore", "#d2a8ff")
      t.set("string.special.path.nix", "#a5d6ff")
      t.set("string.special.symbol", "#79c0ff")
      t.set("string.special.symbol.make", "#d2a8ff")
      t.set("string.special.symbol.ruby", "#79c0ff")
      t.set_extended("string.special.url", color: "#79c0ff", underline: true, italic: true)
      t.set("tag", "#7ee787")
      t.set("tag.attribute", "#79c0ff")
      t.set("tag.builtin", "#7ee787")
      t.set("type", "#ffa657")
      t.set("type.builtin", "#ff7b72")
      t.set("type.builtin.python", "#79c0ff")
      t.set("type.css", "#7ee787")
      t.set("type.qualifier", "#ff7b72")
      t.set("type.sql", "#e6edf3")
      t.set("variable", "#e6edf3")
      t.set("variable.builtin", "#79c0ff")
      t.set("variable.builtin.python", "#79c0ff")
      t.set("variable.member", "#79c0ff")
      t.set("variable.member.luadoc", "#e6edf3")
      t.set("variable.member.nix", "#79c0ff")
      t.set("variable.member.python", "#e6edf3")
      t.set("variable.member.sql", "#79c0ff")
      t.set("variable.parameter", "#e6edf3")
      t.set("variable.parameter.builtin", "#79c0ff")
      t.set("variable.parameter.nix", "#e6edf3")
      t.set("variable.parameter.vimdoc", "#ffa657")
      t.set("variable.scss", "#e6edf3")
      t.set("variable.sql", "#79c0ff")
      t.resolve
    end

    def github_light_default : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#1f2328", bg: "#0d1117")
      t.set("attribute", "#0550ae")
      t.set("attribute.builtin", "#1f2328")
      t.set("boolean", "#0550ae")
      t.set("character", "#0a3069")
      t.set("character.special", "#1f2328")
      t.set("comment", "#57606a")
      t.set("comment.error", "#ffffff")
      t.set("comment.hint", "#ffffff")
      t.set("comment.info", "#ffffff")
      t.set("comment.note", "#0969da")
      t.set("comment.todo", "#ffffff")
      t.set("comment.warning", "#ffffff")
      t.set("conceal", "#6e7781")
      t.set("constant", "#0550ae")
      t.set("constant.builtin", "#0550ae")
      t.set("constant.builtin.rust", "#953800")
      t.set("constant.html", "#116329")
      t.set("constant.macro", "#cf222e")
      t.set("constructor", "#953800")
      t.set("constructor.lua", "#1f2328")
      t.set("diff.delta", "#9a6700")
      t.set("diff.minus", "#d1242f")
      t.set("diff.plus", "#1a7f37")
      t.set("function", "#6639ba")
      t.set("function.builtin.bash", "#cf222e")
      t.set("function.builtin.lua", "#0550ae")
      t.set("function.builtin.make", "#0550ae")
      t.set("function.call.bash", "#0550ae")
      t.set("ibl.indent.char.1", "#e7eaf0")
      t.set("ibl.scope.char.1", "#6e7781")
      t.set("ibl.whitespace.char.1", "#e7eaf0")
      t.set("keyword", "#cf222e")
      t.set("keyword.directive.rust", "#0550ae")
      t.set("keyword.exception", "#0550ae")
      t.set("keyword.function", "#cf222e")
      t.set("keyword.operator", "#cf222e")
      t.set("label", "#116329")
      t.set("label.ruby", "#0550ae")
      t.set("label.vimdoc", "#cf222e")
      t.set("markup", "#1f2328")
      t.set("markup.environment", "#cf222e")
      t.set("markup.environment.name", "#6639ba")
      t.set_extended("markup.heading", color: "#0550ae", bold: true)
      t.set("markup.heading.html", "#1f2328")
      t.set_extended("markup.italic", color: "#1f2328", italic: true)
      t.set_extended("markup.link", color: "#1f2328", underline: true)
      t.set("markup.link.label", "#1f2328")
      t.set_extended("markup.link.uri", color: "#0550ae", underline: true, italic: true)
      t.set("markup.list", "#0550ae")
      t.set("markup.list.checked", "#116329")
      t.set("markup.list.luadoc", "#1f2328")
      t.set("markup.list.unchecked", "#57606a")
      t.set("markup.quote.markdown", "#116329")
      t.set_extended("markup.raw", color: "#1f2328", italic: true)
      t.set_extended("markup.strikethrough", color: "#1f2328", strikethrough: true)
      t.set_extended("markup.strong", color: "#1f2328", bold: true)
      t.set("module", "#cf222e")
      t.set("module.builtin", "#0550ae")
      t.set("module.builtin.lua", "#0550ae")
      t.set("module.c_sharp", "#953800")
      t.set("module.elixir", "#953800")
      t.set("number", "#0550ae")
      t.set("number.float", "#0550ae")
      t.set("operator", "#0550ae")
      t.set("operator.bash", "#cf222e")
      t.set("operator.lua", "#cf222e")
      t.set("operator.luadoc", "#1f2328")
      t.set("property", "#0550ae")
      t.set("property.json", "#116329")
      t.set("property.lua", "#1f2328")
      t.set("property.luadoc", "#1f2328")
      t.set("property.scss", "#0550ae")
      t.set("property.yaml", "#116329")
      t.set("punctuation", "#1f2328")
      t.set("punctuation.bracket", "#1f2328")
      t.set("punctuation.delimiter.bash", "#cf222e")
      t.set("punctuation.delimiter.markdown", "#1f2328")
      t.set("punctuation.delimiter.markdown_inline", "#1f2328")
      t.set("punctuation.special", "#1f2328")
      t.set("string", "#0a3069")
      t.set_extended("string.escape", color: "#0a3069", bold: true)
      t.set("string.regexp", "#0a3069")
      t.set("string.special", "#1f2328")
      t.set("string.special.path.gitignore", "#6639ba")
      t.set("string.special.path.nix", "#0a3069")
      t.set("string.special.symbol", "#0550ae")
      t.set("string.special.symbol.make", "#6639ba")
      t.set("string.special.symbol.ruby", "#0550ae")
      t.set_extended("string.special.url", color: "#0550ae", underline: true, italic: true)
      t.set("tag", "#116329")
      t.set("tag.attribute", "#0550ae")
      t.set("tag.builtin", "#116329")
      t.set("type", "#953800")
      t.set("type.builtin", "#cf222e")
      t.set("type.builtin.python", "#0550ae")
      t.set("type.css", "#116329")
      t.set("type.qualifier", "#cf222e")
      t.set("type.sql", "#1f2328")
      t.set("variable", "#1f2328")
      t.set("variable.builtin", "#0550ae")
      t.set("variable.builtin.python", "#0550ae")
      t.set("variable.member", "#0550ae")
      t.set("variable.member.luadoc", "#1f2328")
      t.set("variable.member.nix", "#0550ae")
      t.set("variable.member.python", "#1f2328")
      t.set("variable.member.sql", "#0550ae")
      t.set("variable.parameter", "#1f2328")
      t.set("variable.parameter.builtin", "#0550ae")
      t.set("variable.parameter.nix", "#1f2328")
      t.set("variable.parameter.vimdoc", "#953800")
      t.set("variable.scss", "#1f2328")
      t.set("variable.sql", "#0550ae")
      t.resolve
    end

    def github_dark_tritanopia : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c9d1d9", bg: "#ffffff")
      t.set("attribute", "#79c0ff")
      t.set("attribute.builtin", "#c9d1d9")
      t.set("boolean", "#79c0ff")
      t.set("character", "#a5d6ff")
      t.set("character.special", "#c9d1d9")
      t.set("comment", "#8b949e")
      t.set("comment.error", "#0d1117")
      t.set("comment.hint", "#0d1117")
      t.set("comment.info", "#0d1117")
      t.set("comment.note", "#58a6ff")
      t.set("comment.todo", "#0d1117")
      t.set("comment.warning", "#0d1117")
      t.set("conceal", "#8b949e")
      t.set("constant", "#79c0ff")
      t.set("constant.builtin", "#79c0ff")
      t.set("constant.builtin.rust", "#ffa198")
      t.set("constant.html", "#a5d6ff")
      t.set("constant.macro", "#ff7b72")
      t.set("constructor", "#ffa198")
      t.set("constructor.lua", "#c9d1d9")
      t.set("diff.delta", "#d29922")
      t.set("diff.minus", "#f85149")
      t.set("diff.plus", "#58a6ff")
      t.set("function", "#d2a8ff")
      t.set("function.builtin.bash", "#ff7b72")
      t.set("function.builtin.lua", "#79c0ff")
      t.set("function.builtin.make", "#79c0ff")
      t.set("function.call.bash", "#79c0ff")
      t.set("ibl.indent.char.1", "#484f58")
      t.set("ibl.scope.char.1", "#6e7681")
      t.set("ibl.whitespace.char.1", "#484f58")
      t.set("keyword", "#ff7b72")
      t.set("keyword.directive.rust", "#79c0ff")
      t.set("keyword.exception", "#79c0ff")
      t.set("keyword.function", "#ff7b72")
      t.set("keyword.operator", "#ff7b72")
      t.set("label", "#a5d6ff")
      t.set("label.ruby", "#79c0ff")
      t.set("label.vimdoc", "#ff7b72")
      t.set("markup", "#c9d1d9")
      t.set("markup.environment", "#ff7b72")
      t.set("markup.environment.name", "#d2a8ff")
      t.set_extended("markup.heading", color: "#79c0ff", bold: true)
      t.set("markup.heading.html", "#c9d1d9")
      t.set_extended("markup.italic", color: "#c9d1d9", italic: true)
      t.set_extended("markup.link", color: "#c9d1d9", underline: true)
      t.set("markup.link.label", "#c9d1d9")
      t.set_extended("markup.link.uri", color: "#79c0ff", underline: true, italic: true)
      t.set("markup.list", "#79c0ff")
      t.set("markup.list.checked", "#58a6ff")
      t.set("markup.list.luadoc", "#c9d1d9")
      t.set("markup.list.unchecked", "#6e7681")
      t.set("markup.quote.markdown", "#a5d6ff")
      t.set_extended("markup.raw", color: "#c9d1d9", italic: true)
      t.set_extended("markup.strikethrough", color: "#c9d1d9", strikethrough: true)
      t.set_extended("markup.strong", color: "#c9d1d9", bold: true)
      t.set("module", "#ff7b72")
      t.set("module.builtin", "#79c0ff")
      t.set("module.builtin.lua", "#79c0ff")
      t.set("module.c_sharp", "#ffa198")
      t.set("module.elixir", "#ffa198")
      t.set("number", "#79c0ff")
      t.set("number.float", "#79c0ff")
      t.set("operator", "#79c0ff")
      t.set("operator.bash", "#ff7b72")
      t.set("operator.lua", "#ff7b72")
      t.set("operator.luadoc", "#c9d1d9")
      t.set("property", "#79c0ff")
      t.set("property.json", "#a5d6ff")
      t.set("property.lua", "#c9d1d9")
      t.set("property.luadoc", "#c9d1d9")
      t.set("property.scss", "#79c0ff")
      t.set("property.yaml", "#a5d6ff")
      t.set("punctuation", "#c9d1d9")
      t.set("punctuation.bracket", "#c9d1d9")
      t.set("punctuation.delimiter.bash", "#ff7b72")
      t.set("punctuation.delimiter.markdown", "#c9d1d9")
      t.set("punctuation.delimiter.markdown_inline", "#c9d1d9")
      t.set("punctuation.special", "#c9d1d9")
      t.set("string", "#a5d6ff")
      t.set_extended("string.escape", color: "#a5d6ff", bold: true)
      t.set("string.regexp", "#a5d6ff")
      t.set("string.special", "#c9d1d9")
      t.set("string.special.path.gitignore", "#d2a8ff")
      t.set("string.special.path.nix", "#a5d6ff")
      t.set("string.special.symbol", "#79c0ff")
      t.set("string.special.symbol.make", "#d2a8ff")
      t.set("string.special.symbol.ruby", "#79c0ff")
      t.set_extended("string.special.url", color: "#79c0ff", underline: true, italic: true)
      t.set("tag", "#a5d6ff")
      t.set("tag.attribute", "#79c0ff")
      t.set("tag.builtin", "#a5d6ff")
      t.set("type", "#ffa198")
      t.set("type.builtin", "#ff7b72")
      t.set("type.builtin.python", "#79c0ff")
      t.set("type.css", "#a5d6ff")
      t.set("type.qualifier", "#ff7b72")
      t.set("type.sql", "#c9d1d9")
      t.set("variable", "#c9d1d9")
      t.set("variable.builtin", "#79c0ff")
      t.set("variable.builtin.python", "#79c0ff")
      t.set("variable.member", "#79c0ff")
      t.set("variable.member.luadoc", "#c9d1d9")
      t.set("variable.member.nix", "#79c0ff")
      t.set("variable.member.python", "#c9d1d9")
      t.set("variable.member.sql", "#79c0ff")
      t.set("variable.parameter", "#c9d1d9")
      t.set("variable.parameter.builtin", "#79c0ff")
      t.set("variable.parameter.nix", "#c9d1d9")
      t.set("variable.parameter.vimdoc", "#ffa198")
      t.set("variable.scss", "#c9d1d9")
      t.set("variable.sql", "#79c0ff")
      t.resolve
    end

    def github_light_colorblind : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#1b1f24", bg: "#0d1117")
      t.set("attribute", "#0550ae")
      t.set("attribute.builtin", "#1b1f24")
      t.set("boolean", "#0550ae")
      t.set("character", "#0a3069")
      t.set("character.special", "#1b1f24")
      t.set("comment", "#57606a")
      t.set("comment.error", "#ffffff")
      t.set("comment.hint", "#ffffff")
      t.set("comment.info", "#ffffff")
      t.set("comment.note", "#0969da")
      t.set("comment.todo", "#ffffff")
      t.set("comment.warning", "#ffffff")
      t.set("conceal", "#6e7781")
      t.set("constant", "#0550ae")
      t.set("constant.builtin", "#0550ae")
      t.set("constant.builtin.rust", "#8a4600")
      t.set("constant.html", "#0550ae")
      t.set("constant.macro", "#b35900")
      t.set("constructor", "#8a4600")
      t.set("constructor.lua", "#1b1f24")
      t.set("diff.delta", "#9a6700")
      t.set("diff.minus", "#d1242f")
      t.set("diff.plus", "#0969da")
      t.set("function", "#6639ba")
      t.set("function.builtin.bash", "#b35900")
      t.set("function.builtin.lua", "#0550ae")
      t.set("function.builtin.make", "#0550ae")
      t.set("function.call.bash", "#0550ae")
      t.set("ibl.indent.char.1", "#e7eaf0")
      t.set("ibl.scope.char.1", "#6e7781")
      t.set("ibl.whitespace.char.1", "#e7eaf0")
      t.set("keyword", "#b35900")
      t.set("keyword.directive.rust", "#0550ae")
      t.set("keyword.exception", "#0550ae")
      t.set("keyword.function", "#b35900")
      t.set("keyword.operator", "#b35900")
      t.set("label", "#0550ae")
      t.set("label.ruby", "#0550ae")
      t.set("label.vimdoc", "#b35900")
      t.set("markup", "#1b1f24")
      t.set("markup.environment", "#b35900")
      t.set("markup.environment.name", "#6639ba")
      t.set_extended("markup.heading", color: "#0550ae", bold: true)
      t.set("markup.heading.html", "#1b1f24")
      t.set_extended("markup.italic", color: "#1b1f24", italic: true)
      t.set_extended("markup.link", color: "#1b1f24", underline: true)
      t.set("markup.link.label", "#1b1f24")
      t.set_extended("markup.link.uri", color: "#0550ae", underline: true, italic: true)
      t.set("markup.list", "#0550ae")
      t.set("markup.list.checked", "#0550ae")
      t.set("markup.list.luadoc", "#1b1f24")
      t.set("markup.list.unchecked", "#57606a")
      t.set("markup.quote.markdown", "#0550ae")
      t.set_extended("markup.raw", color: "#1b1f24", italic: true)
      t.set_extended("markup.strikethrough", color: "#1b1f24", strikethrough: true)
      t.set_extended("markup.strong", color: "#1b1f24", bold: true)
      t.set("module", "#b35900")
      t.set("module.builtin", "#0550ae")
      t.set("module.builtin.lua", "#0550ae")
      t.set("module.c_sharp", "#8a4600")
      t.set("module.elixir", "#8a4600")
      t.set("number", "#0550ae")
      t.set("number.float", "#0550ae")
      t.set("operator", "#0550ae")
      t.set("operator.bash", "#b35900")
      t.set("operator.lua", "#b35900")
      t.set("operator.luadoc", "#1b1f24")
      t.set("property", "#0550ae")
      t.set("property.json", "#0550ae")
      t.set("property.lua", "#1b1f24")
      t.set("property.luadoc", "#1b1f24")
      t.set("property.scss", "#0550ae")
      t.set("property.yaml", "#0550ae")
      t.set("punctuation", "#1b1f24")
      t.set("punctuation.bracket", "#1b1f24")
      t.set("punctuation.delimiter.bash", "#b35900")
      t.set("punctuation.delimiter.markdown", "#1b1f24")
      t.set("punctuation.delimiter.markdown_inline", "#1b1f24")
      t.set("punctuation.special", "#1b1f24")
      t.set("string", "#0a3069")
      t.set_extended("string.escape", color: "#0a3069", bold: true)
      t.set("string.regexp", "#0a3069")
      t.set("string.special", "#1b1f24")
      t.set("string.special.path.gitignore", "#6639ba")
      t.set("string.special.path.nix", "#0a3069")
      t.set("string.special.symbol", "#0550ae")
      t.set("string.special.symbol.make", "#6639ba")
      t.set("string.special.symbol.ruby", "#0550ae")
      t.set_extended("string.special.url", color: "#0550ae", underline: true, italic: true)
      t.set("tag", "#0550ae")
      t.set("tag.attribute", "#0550ae")
      t.set("tag.builtin", "#0550ae")
      t.set("type", "#8a4600")
      t.set("type.builtin", "#b35900")
      t.set("type.builtin.python", "#0550ae")
      t.set("type.css", "#0550ae")
      t.set("type.qualifier", "#b35900")
      t.set("type.sql", "#1b1f24")
      t.set("variable", "#1b1f24")
      t.set("variable.builtin", "#0550ae")
      t.set("variable.builtin.python", "#0550ae")
      t.set("variable.member", "#0550ae")
      t.set("variable.member.luadoc", "#1b1f24")
      t.set("variable.member.nix", "#0550ae")
      t.set("variable.member.python", "#1b1f24")
      t.set("variable.member.sql", "#0550ae")
      t.set("variable.parameter", "#1b1f24")
      t.set("variable.parameter.builtin", "#0550ae")
      t.set("variable.parameter.nix", "#1b1f24")
      t.set("variable.parameter.vimdoc", "#8a4600")
      t.set("variable.scss", "#1b1f24")
      t.set("variable.sql", "#0550ae")
      t.resolve
    end

    def github_light_tritanopia : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#1b1f24", bg: "#ffffff")
      t.set("attribute", "#0550ae")
      t.set("attribute.builtin", "#1b1f24")
      t.set("boolean", "#0550ae")
      t.set("character", "#0a3069")
      t.set("character.special", "#1b1f24")
      t.set("comment", "#57606a")
      t.set("comment.error", "#ffffff")
      t.set("comment.hint", "#ffffff")
      t.set("comment.info", "#ffffff")
      t.set("comment.note", "#0969da")
      t.set("comment.todo", "#ffffff")
      t.set("comment.warning", "#ffffff")
      t.set("conceal", "#6e7781")
      t.set("constant", "#0550ae")
      t.set("constant.builtin", "#0550ae")
      t.set("constant.builtin.rust", "#a40e26")
      t.set("constant.html", "#0550ae")
      t.set("constant.macro", "#cf222e")
      t.set("constructor", "#a40e26")
      t.set("constructor.lua", "#1b1f24")
      t.set("diff.delta", "#9a6700")
      t.set("diff.minus", "#d1242f")
      t.set("diff.plus", "#0969da")
      t.set("function", "#6639ba")
      t.set("function.builtin.bash", "#cf222e")
      t.set("function.builtin.lua", "#0550ae")
      t.set("function.builtin.make", "#0550ae")
      t.set("function.call.bash", "#0550ae")
      t.set("ibl.indent.char.1", "#eaeef2")
      t.set("ibl.scope.char.1", "#6e7781")
      t.set("ibl.whitespace.char.1", "#eaeef2")
      t.set("keyword", "#cf222e")
      t.set("keyword.directive.rust", "#0550ae")
      t.set("keyword.exception", "#0550ae")
      t.set("keyword.function", "#cf222e")
      t.set("keyword.operator", "#cf222e")
      t.set("label", "#0550ae")
      t.set("label.ruby", "#0550ae")
      t.set("label.vimdoc", "#cf222e")
      t.set("markup", "#1b1f24")
      t.set("markup.environment", "#cf222e")
      t.set("markup.environment.name", "#6639ba")
      t.set_extended("markup.heading", color: "#0550ae", bold: true)
      t.set("markup.heading.html", "#1b1f24")
      t.set_extended("markup.italic", color: "#1b1f24", italic: true)
      t.set_extended("markup.link", color: "#1b1f24", underline: true)
      t.set("markup.link.label", "#1b1f24")
      t.set_extended("markup.link.uri", color: "#0550ae", underline: true, italic: true)
      t.set("markup.list", "#0550ae")
      t.set("markup.list.checked", "#0550ae")
      t.set("markup.list.luadoc", "#1b1f24")
      t.set("markup.list.unchecked", "#57606a")
      t.set("markup.quote.markdown", "#0550ae")
      t.set_extended("markup.raw", color: "#1b1f24", italic: true)
      t.set_extended("markup.strikethrough", color: "#1b1f24", strikethrough: true)
      t.set_extended("markup.strong", color: "#1b1f24", bold: true)
      t.set("module", "#cf222e")
      t.set("module.builtin", "#0550ae")
      t.set("module.builtin.lua", "#0550ae")
      t.set("module.c_sharp", "#a40e26")
      t.set("module.elixir", "#a40e26")
      t.set("number", "#0550ae")
      t.set("number.float", "#0550ae")
      t.set("operator", "#0550ae")
      t.set("operator.bash", "#cf222e")
      t.set("operator.lua", "#cf222e")
      t.set("operator.luadoc", "#1b1f24")
      t.set("property", "#0550ae")
      t.set("property.json", "#0550ae")
      t.set("property.lua", "#1b1f24")
      t.set("property.luadoc", "#1b1f24")
      t.set("property.scss", "#0550ae")
      t.set("property.yaml", "#0550ae")
      t.set("punctuation", "#1b1f24")
      t.set("punctuation.bracket", "#1b1f24")
      t.set("punctuation.delimiter.bash", "#cf222e")
      t.set("punctuation.delimiter.markdown", "#1b1f24")
      t.set("punctuation.delimiter.markdown_inline", "#1b1f24")
      t.set("punctuation.special", "#1b1f24")
      t.set("string", "#0a3069")
      t.set_extended("string.escape", color: "#0a3069", bold: true)
      t.set("string.regexp", "#0a3069")
      t.set("string.special", "#1b1f24")
      t.set("string.special.path.gitignore", "#6639ba")
      t.set("string.special.path.nix", "#0a3069")
      t.set("string.special.symbol", "#0550ae")
      t.set("string.special.symbol.make", "#6639ba")
      t.set("string.special.symbol.ruby", "#0550ae")
      t.set_extended("string.special.url", color: "#0550ae", underline: true, italic: true)
      t.set("tag", "#0550ae")
      t.set("tag.attribute", "#0550ae")
      t.set("tag.builtin", "#0550ae")
      t.set("type", "#a40e26")
      t.set("type.builtin", "#cf222e")
      t.set("type.builtin.python", "#0550ae")
      t.set("type.css", "#0550ae")
      t.set("type.qualifier", "#cf222e")
      t.set("type.sql", "#1b1f24")
      t.set("variable", "#1b1f24")
      t.set("variable.builtin", "#0550ae")
      t.set("variable.builtin.python", "#0550ae")
      t.set("variable.member", "#0550ae")
      t.set("variable.member.luadoc", "#1b1f24")
      t.set("variable.member.nix", "#0550ae")
      t.set("variable.member.python", "#1b1f24")
      t.set("variable.member.sql", "#0550ae")
      t.set("variable.parameter", "#1b1f24")
      t.set("variable.parameter.builtin", "#0550ae")
      t.set("variable.parameter.nix", "#1b1f24")
      t.set("variable.parameter.vimdoc", "#a40e26")
      t.set("variable.scss", "#1b1f24")
      t.set("variable.sql", "#0550ae")
      t.resolve
    end

    def github_dark_high_contrast : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#f0f3f6", bg: "#ffffff")
      t.set("attribute", "#91cbff")
      t.set("attribute.builtin", "#f0f3f6")
      t.set("boolean", "#91cbff")
      t.set("character", "#addcff")
      t.set("character.special", "#f0f3f6")
      t.set("comment", "#bdc4cc")
      t.set("comment.error", "#0a0c10")
      t.set("comment.hint", "#0a0c10")
      t.set("comment.info", "#0a0c10")
      t.set("comment.note", "#409eff")
      t.set("comment.todo", "#0a0c10")
      t.set("comment.warning", "#0a0c10")
      t.set("conceal", "#bdc4cc")
      t.set("constant", "#91cbff")
      t.set("constant.builtin", "#91cbff")
      t.set("constant.builtin.rust", "#ffb757")
      t.set("constant.html", "#72f088")
      t.set("constant.macro", "#ff9492")
      t.set("constructor", "#ffb757")
      t.set("constructor.lua", "#f0f3f6")
      t.set("diff.delta", "#e09b13")
      t.set("diff.minus", "#ff6a69")
      t.set("diff.plus", "#09b43a")
      t.set("function", "#dbb7ff")
      t.set("function.builtin.bash", "#ff9492")
      t.set("function.builtin.lua", "#91cbff")
      t.set("function.builtin.make", "#91cbff")
      t.set("function.call.bash", "#91cbff")
      t.set("ibl.indent.char.1", "#212327")
      t.set("ibl.scope.char.1", "#9ea7b3")
      t.set("ibl.whitespace.char.1", "#212327")
      t.set("keyword", "#ff9492")
      t.set("keyword.directive.rust", "#91cbff")
      t.set("keyword.exception", "#91cbff")
      t.set("keyword.function", "#ff9492")
      t.set("keyword.operator", "#ff9492")
      t.set("label", "#72f088")
      t.set("label.ruby", "#91cbff")
      t.set("label.vimdoc", "#ff9492")
      t.set("markup", "#f0f3f6")
      t.set("markup.environment", "#ff9492")
      t.set("markup.environment.name", "#dbb7ff")
      t.set_extended("markup.heading", color: "#91cbff", bold: true)
      t.set("markup.heading.html", "#f0f3f6")
      t.set_extended("markup.italic", color: "#f0f3f6", italic: true)
      t.set_extended("markup.link", color: "#f0f3f6", underline: true)
      t.set("markup.link.label", "#f0f3f6")
      t.set_extended("markup.link.uri", color: "#91cbff", underline: true, italic: true)
      t.set("markup.list", "#91cbff")
      t.set("markup.list.checked", "#26cd4d")
      t.set("markup.list.luadoc", "#f0f3f6")
      t.set("markup.list.unchecked", "#9ea7b3")
      t.set("markup.quote.markdown", "#72f088")
      t.set_extended("markup.raw", color: "#f0f3f6", italic: true)
      t.set_extended("markup.strikethrough", color: "#f0f3f6", strikethrough: true)
      t.set_extended("markup.strong", color: "#f0f3f6", bold: true)
      t.set("module", "#ff9492")
      t.set("module.builtin", "#91cbff")
      t.set("module.builtin.lua", "#91cbff")
      t.set("module.c_sharp", "#ffb757")
      t.set("module.elixir", "#ffb757")
      t.set("number", "#91cbff")
      t.set("number.float", "#91cbff")
      t.set("operator", "#91cbff")
      t.set("operator.bash", "#ff9492")
      t.set("operator.lua", "#ff9492")
      t.set("operator.luadoc", "#f0f3f6")
      t.set("property", "#91cbff")
      t.set("property.json", "#72f088")
      t.set("property.lua", "#f0f3f6")
      t.set("property.luadoc", "#f0f3f6")
      t.set("property.scss", "#91cbff")
      t.set("property.yaml", "#72f088")
      t.set("punctuation", "#f0f3f6")
      t.set("punctuation.bracket", "#f0f3f6")
      t.set("punctuation.delimiter.bash", "#ff9492")
      t.set("punctuation.delimiter.markdown", "#f0f3f6")
      t.set("punctuation.delimiter.markdown_inline", "#f0f3f6")
      t.set("punctuation.special", "#f0f3f6")
      t.set("string", "#addcff")
      t.set_extended("string.escape", color: "#addcff", bold: true)
      t.set("string.regexp", "#addcff")
      t.set("string.special", "#f0f3f6")
      t.set("string.special.path.gitignore", "#dbb7ff")
      t.set("string.special.path.nix", "#addcff")
      t.set("string.special.symbol", "#91cbff")
      t.set("string.special.symbol.make", "#dbb7ff")
      t.set("string.special.symbol.ruby", "#91cbff")
      t.set_extended("string.special.url", color: "#91cbff", underline: true, italic: true)
      t.set("tag", "#72f088")
      t.set("tag.attribute", "#91cbff")
      t.set("tag.builtin", "#72f088")
      t.set("type", "#ffb757")
      t.set("type.builtin", "#ff9492")
      t.set("type.builtin.python", "#91cbff")
      t.set("type.css", "#72f088")
      t.set("type.qualifier", "#ff9492")
      t.set("type.sql", "#f0f3f6")
      t.set("variable", "#f0f3f6")
      t.set("variable.builtin", "#91cbff")
      t.set("variable.builtin.python", "#91cbff")
      t.set("variable.member", "#91cbff")
      t.set("variable.member.luadoc", "#f0f3f6")
      t.set("variable.member.nix", "#91cbff")
      t.set("variable.member.python", "#f0f3f6")
      t.set("variable.member.sql", "#91cbff")
      t.set("variable.parameter", "#f0f3f6")
      t.set("variable.parameter.builtin", "#91cbff")
      t.set("variable.parameter.nix", "#f0f3f6")
      t.set("variable.parameter.vimdoc", "#ffb757")
      t.set("variable.scss", "#f0f3f6")
      t.set("variable.sql", "#91cbff")
      t.resolve
    end

    def github_light_high_contrast : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#010409", bg: "#0a0c10")
      t.set("attribute", "#023b95")
      t.set("attribute.builtin", "#010409")
      t.set("boolean", "#023b95")
      t.set("character", "#032563")
      t.set("character.special", "#010409")
      t.set("comment", "#4b535d")
      t.set("comment.error", "#ffffff")
      t.set("comment.hint", "#ffffff")
      t.set("comment.info", "#ffffff")
      t.set("comment.note", "#0349b4")
      t.set("comment.todo", "#ffffff")
      t.set("comment.warning", "#ffffff")
      t.set("conceal", "#20252c")
      t.set("constant", "#023b95")
      t.set("constant.builtin", "#023b95")
      t.set("constant.builtin.rust", "#702c00")
      t.set("constant.html", "#024c1a")
      t.set("constant.macro", "#a0111f")
      t.set("constructor", "#702c00")
      t.set("constructor.lua", "#010409")
      t.set("diff.delta", "#744500")
      t.set("diff.minus", "#d1242f")
      t.set("diff.plus", "#055d20")
      t.set("function", "#512598")
      t.set("function.builtin.bash", "#a0111f")
      t.set("function.builtin.lua", "#023b95")
      t.set("function.builtin.make", "#023b95")
      t.set("function.call.bash", "#023b95")
      t.set("ibl.indent.char.1", "#e7ecf0")
      t.set("ibl.scope.char.1", "#66707b")
      t.set("ibl.whitespace.char.1", "#e7ecf0")
      t.set("keyword", "#a0111f")
      t.set("keyword.directive.rust", "#023b95")
      t.set("keyword.exception", "#023b95")
      t.set("keyword.function", "#a0111f")
      t.set("keyword.operator", "#a0111f")
      t.set("label", "#024c1a")
      t.set("label.ruby", "#023b95")
      t.set("label.vimdoc", "#a0111f")
      t.set("markup", "#010409")
      t.set("markup.environment", "#a0111f")
      t.set("markup.environment.name", "#512598")
      t.set_extended("markup.heading", color: "#023b95", bold: true)
      t.set("markup.heading.html", "#010409")
      t.set_extended("markup.italic", color: "#010409", italic: true)
      t.set_extended("markup.link", color: "#010409", underline: true)
      t.set("markup.link.label", "#010409")
      t.set_extended("markup.link.uri", color: "#023b95", underline: true, italic: true)
      t.set("markup.list", "#023b95")
      t.set("markup.list.checked", "#024c1a")
      t.set("markup.list.luadoc", "#010409")
      t.set("markup.list.unchecked", "#4b535d")
      t.set("markup.quote.markdown", "#024c1a")
      t.set_extended("markup.raw", color: "#010409", italic: true)
      t.set_extended("markup.strikethrough", color: "#010409", strikethrough: true)
      t.set_extended("markup.strong", color: "#010409", bold: true)
      t.set("module", "#a0111f")
      t.set("module.builtin", "#023b95")
      t.set("module.builtin.lua", "#023b95")
      t.set("module.c_sharp", "#702c00")
      t.set("module.elixir", "#702c00")
      t.set("number", "#023b95")
      t.set("number.float", "#023b95")
      t.set("operator", "#023b95")
      t.set("operator.bash", "#a0111f")
      t.set("operator.lua", "#a0111f")
      t.set("operator.luadoc", "#010409")
      t.set("property", "#023b95")
      t.set("property.json", "#024c1a")
      t.set("property.lua", "#010409")
      t.set("property.luadoc", "#010409")
      t.set("property.scss", "#023b95")
      t.set("property.yaml", "#024c1a")
      t.set("punctuation", "#010409")
      t.set("punctuation.bracket", "#010409")
      t.set("punctuation.delimiter.bash", "#a0111f")
      t.set("punctuation.delimiter.markdown", "#010409")
      t.set("punctuation.delimiter.markdown_inline", "#010409")
      t.set("punctuation.special", "#010409")
      t.set("string", "#032563")
      t.set_extended("string.escape", color: "#032563", bold: true)
      t.set("string.regexp", "#032563")
      t.set("string.special", "#010409")
      t.set("string.special.path.gitignore", "#512598")
      t.set("string.special.path.nix", "#032563")
      t.set("string.special.symbol", "#023b95")
      t.set("string.special.symbol.make", "#512598")
      t.set("string.special.symbol.ruby", "#023b95")
      t.set_extended("string.special.url", color: "#023b95", underline: true, italic: true)
      t.set("tag", "#024c1a")
      t.set("tag.attribute", "#023b95")
      t.set("tag.builtin", "#024c1a")
      t.set("type", "#702c00")
      t.set("type.builtin", "#a0111f")
      t.set("type.builtin.python", "#023b95")
      t.set("type.css", "#024c1a")
      t.set("type.qualifier", "#a0111f")
      t.set("type.sql", "#010409")
      t.set("variable", "#010409")
      t.set("variable.builtin", "#023b95")
      t.set("variable.builtin.python", "#023b95")
      t.set("variable.member", "#023b95")
      t.set("variable.member.luadoc", "#010409")
      t.set("variable.member.nix", "#023b95")
      t.set("variable.member.python", "#010409")
      t.set("variable.member.sql", "#023b95")
      t.set("variable.parameter", "#010409")
      t.set("variable.parameter.builtin", "#023b95")
      t.set("variable.parameter.nix", "#010409")
      t.set("variable.parameter.vimdoc", "#702c00")
      t.set("variable.scss", "#010409")
      t.set("variable.sql", "#023b95")
      t.resolve
    end
  end
end
