module TreeSitterManager
  module Themes
    def gruvbox_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#ebdbb2", bg: "#282828")
      t.set("attribute", "#8ec07c")
      t.set("attribute.builtin", "#fe8019")
      t.set("boolean", "#d3869b")
      t.set("character", "#d3869b")
      t.set("character.special", "#fe8019")
      t.set_extended("comment", color: "#928374", italic: true)
      t.set("comment.error", "#282828")
      t.set("comment.note", "#fe8019")
      t.set("comment.todo", "#282828")
      t.set_extended("comment.warning", color: "#fb4934", bold: true)
      t.set("conditional", "#fb4934")
      t.set("constant", "#d3869b")
      t.set("constant.builtin", "#fe8019")
      t.set("constant.macro", "#8ec07c")
      t.set("constructor", "#fe8019")
      t.set("debug", "#fe8019")
      t.set("define", "#8ec07c")
      t.set("exception", "#fb4934")
      t.set("field", "#83a598")
      t.set("float", "#d3869b")
      t.set_extended("function", color: "#b8bb26", bold: true)
      t.set("function.builtin", "#fe8019")
      t.set_extended("function.call", color: "#b8bb26", bold: true)
      t.set("function.macro", "#8ec07c")
      t.set_extended("function.method", color: "#b8bb26", bold: true)
      t.set("ibl.indent.char.1", "#504945")
      t.set("ibl.scope.char.1", "#7c6f64")
      t.set("ibl.whitespace.char.1", "#504945")
      t.set("include", "#8ec07c")
      t.set("keyword", "#fb4934")
      t.set("keyword.conditional", "#fb4934")
      t.set("keyword.debug", "#fe8019")
      t.set("keyword.directive", "#8ec07c")
      t.set("keyword.directive.define", "#8ec07c")
      t.set("keyword.exception", "#fb4934")
      t.set("keyword.function", "#fb4934")
      t.set("keyword.import", "#8ec07c")
      t.set("keyword.operator", "#fb4934")
      t.set("keyword.repeat", "#fb4934")
      t.set("keyword.return", "#fb4934")
      t.set("keyword.storage", "#fe8019")
      t.set("label", "#fb4934")
      t.set("macro", "#8ec07c")
      t.set("markup", "#ebdbb2")
      t.set("markup.environment", "#8ec07c")
      t.set("markup.environment.name", "#fabd2f")
      t.set_extended("markup.heading", color: "#b8bb26", bold: true)
      t.set_extended("markup.link", color: "#83a598", underline: true)
      t.set("markup.link.label", "#fe8019")
      t.set("markup.list", "#fe8019")
      t.set("markup.list.checked", "#b8bb26")
      t.set("markup.list.unchecked", "#928374")
      t.set("markup.math", "#fe8019")
      t.set_extended("markup.raw", color: "#b8bb26", italic: true)
      t.set_extended("method", color: "#b8bb26", bold: true)
      t.set_extended("method.call", color: "#b8bb26", bold: true)
      t.set("module", "#ebdbb2")
      t.set("module.builtin", "#fe8019")
      t.set("namespace", "#ebdbb2")
      t.set("number", "#d3869b")
      t.set("number.float", "#d3869b")
      t.set("operator", "#fe8019")
      t.set("parameter", "#83a598")
      t.set("preproc", "#8ec07c")
      t.set("property", "#83a598")
      t.set("punctuation", "#fe8019")
      t.set("punctuation.bracket", "#fe8019")
      t.set("punctuation.delimiter", "#fe8019")
      t.set("punctuation.special", "#fe8019")
      t.set("repeat", "#fb4934")
      t.set("storageclass", "#fe8019")
      t.set_extended("string", color: "#b8bb26", italic: true)
      t.set("string.escape", "#fe8019")
      t.set_extended("string.regex", color: "#b8bb26", italic: true)
      t.set_extended("string.regexp", color: "#b8bb26", italic: true)
      t.set("string.special", "#fe8019")
      t.set_extended("string.special.path", color: "#83a598", underline: true)
      t.set("string.special.symbol", "#83a598")
      t.set_extended("string.special.url", color: "#83a598", underline: true)
      t.set("structure", "#8ec07c")
      t.set("symbol", "#83a598")
      t.set("tag", "#fe8019")
      t.set("tag.attribute", "#83a598")
      t.set("tag.builtin", "#fe8019")
      t.set("tag.delimiter", "#fe8019")
      t.set("text", "#ebdbb2")
      t.set("text.danger", "#282828")
      t.set("text.danger.comment", "#fbf1c7")
      t.set("text.environment", "#8ec07c")
      t.set("text.environment.name", "#fabd2f")
      t.set_extended("text.literal", color: "#b8bb26", italic: true)
      t.set("text.math", "#fe8019")
      t.set("text.note", "#fe8019")
      t.set_extended("text.note.comment", color: "#d3869b", bold: true)
      t.set("text.reference", "#d3869b")
      t.set_extended("text.title", color: "#b8bb26", bold: true)
      t.set("text.todo", "#282828")
      t.set("text.todo.checked", "#b8bb26")
      t.set("text.todo.unchecked", "#928374")
      t.set_extended("text.uri", color: "#83a598", underline: true)
      t.set_extended("text.warning", color: "#fb4934", bold: true)
      t.set("type", "#fabd2f")
      t.set("type.builtin", "#fabd2f")
      t.set("type.definition", "#fabd2f")
      t.set("type.qualifier", "#fabd2f")
      t.set("variable", "#ebdbb2")
      t.set("variable.builtin", "#fe8019")
      t.set("variable.member", "#83a598")
      t.set("variable.parameter", "#83a598")
      t.set("variable.parameter.builtin", "#fe8019")
      t.resolve
    end

    def gruvbox_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#3c3836", bg: "#282828")
      t.set("attribute", "#427b58")
      t.set("attribute.builtin", "#af3a03")
      t.set("boolean", "#8f3f71")
      t.set("character", "#8f3f71")
      t.set("character.special", "#af3a03")
      t.set_extended("comment", color: "#928374", italic: true)
      t.set("comment.error", "#fbf1c7")
      t.set("comment.note", "#af3a03")
      t.set("comment.todo", "#fbf1c7")
      t.set_extended("comment.warning", color: "#9d0006", bold: true)
      t.set("conditional", "#9d0006")
      t.set("constant", "#8f3f71")
      t.set("constant.builtin", "#af3a03")
      t.set("constant.macro", "#427b58")
      t.set("constructor", "#af3a03")
      t.set("debug", "#af3a03")
      t.set("define", "#427b58")
      t.set("exception", "#9d0006")
      t.set("field", "#076678")
      t.set("float", "#8f3f71")
      t.set_extended("function", color: "#79740e", bold: true)
      t.set("function.builtin", "#af3a03")
      t.set_extended("function.call", color: "#79740e", bold: true)
      t.set("function.macro", "#427b58")
      t.set_extended("function.method", color: "#79740e", bold: true)
      t.set("ibl.indent.char.1", "#d5c4a1")
      t.set("ibl.scope.char.1", "#a89984")
      t.set("ibl.whitespace.char.1", "#d5c4a1")
      t.set("include", "#427b58")
      t.set("keyword", "#9d0006")
      t.set("keyword.conditional", "#9d0006")
      t.set("keyword.debug", "#af3a03")
      t.set("keyword.directive", "#427b58")
      t.set("keyword.directive.define", "#427b58")
      t.set("keyword.exception", "#9d0006")
      t.set("keyword.function", "#9d0006")
      t.set("keyword.import", "#427b58")
      t.set("keyword.operator", "#9d0006")
      t.set("keyword.repeat", "#9d0006")
      t.set("keyword.return", "#9d0006")
      t.set("keyword.storage", "#af3a03")
      t.set("label", "#9d0006")
      t.set("macro", "#427b58")
      t.set("markup", "#3c3836")
      t.set("markup.environment", "#427b58")
      t.set("markup.environment.name", "#b57614")
      t.set_extended("markup.heading", color: "#79740e", bold: true)
      t.set_extended("markup.link", color: "#076678", underline: true)
      t.set("markup.link.label", "#af3a03")
      t.set("markup.list", "#af3a03")
      t.set("markup.list.checked", "#79740e")
      t.set("markup.list.unchecked", "#928374")
      t.set("markup.math", "#af3a03")
      t.set_extended("markup.raw", color: "#79740e", italic: true)
      t.set_extended("method", color: "#79740e", bold: true)
      t.set_extended("method.call", color: "#79740e", bold: true)
      t.set("module", "#3c3836")
      t.set("module.builtin", "#af3a03")
      t.set("namespace", "#3c3836")
      t.set("number", "#8f3f71")
      t.set("number.float", "#8f3f71")
      t.set("operator", "#af3a03")
      t.set("parameter", "#076678")
      t.set("preproc", "#427b58")
      t.set("property", "#076678")
      t.set("punctuation", "#af3a03")
      t.set("punctuation.bracket", "#af3a03")
      t.set("punctuation.delimiter", "#af3a03")
      t.set("punctuation.special", "#af3a03")
      t.set("repeat", "#9d0006")
      t.set("storageclass", "#af3a03")
      t.set_extended("string", color: "#79740e", italic: true)
      t.set("string.escape", "#af3a03")
      t.set_extended("string.regex", color: "#79740e", italic: true)
      t.set_extended("string.regexp", color: "#79740e", italic: true)
      t.set("string.special", "#af3a03")
      t.set_extended("string.special.path", color: "#076678", underline: true)
      t.set("string.special.symbol", "#076678")
      t.set_extended("string.special.url", color: "#076678", underline: true)
      t.set("structure", "#427b58")
      t.set("symbol", "#076678")
      t.set("tag", "#af3a03")
      t.set("tag.attribute", "#076678")
      t.set("tag.builtin", "#af3a03")
      t.set("tag.delimiter", "#af3a03")
      t.set("text", "#3c3836")
      t.set("text.danger", "#fbf1c7")
      t.set("text.danger.comment", "#282828")
      t.set("text.environment", "#427b58")
      t.set("text.environment.name", "#b57614")
      t.set_extended("text.literal", color: "#79740e", italic: true)
      t.set("text.math", "#af3a03")
      t.set("text.note", "#af3a03")
      t.set_extended("text.note.comment", color: "#8f3f71", bold: true)
      t.set("text.reference", "#8f3f71")
      t.set_extended("text.title", color: "#79740e", bold: true)
      t.set("text.todo", "#fbf1c7")
      t.set("text.todo.checked", "#79740e")
      t.set("text.todo.unchecked", "#928374")
      t.set_extended("text.uri", color: "#076678", underline: true)
      t.set_extended("text.warning", color: "#9d0006", bold: true)
      t.set("type", "#b57614")
      t.set("type.builtin", "#b57614")
      t.set("type.definition", "#b57614")
      t.set("type.qualifier", "#b57614")
      t.set("variable", "#3c3836")
      t.set("variable.builtin", "#af3a03")
      t.set("variable.member", "#076678")
      t.set("variable.parameter", "#076678")
      t.set("variable.parameter.builtin", "#af3a03")
      t.resolve
    end
  end
end
