module TreeSitterManager
  module Themes
    def melange_melange : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#ece1d7", bg: "#292522")
      t.set("attribute", "#85b695")
      t.set("attribute.builtin", "#ebc06d")
      t.set("boolean", "#cf9bc2")
      t.set("character", "#7f91b2")
      t.set("character.special", "#ebc06d")
      t.set_extended("comment", color: "#c1a78e", italic: true)
      t.set("comment.documentation", "#c1a78e")
      t.set_extended("comment.error", color: "#c1a78e", bold: true)
      t.set_extended("comment.note", color: "#c1a78e", bold: true)
      t.set_extended("comment.todo", color: "#c1a78e", bold: true)
      t.set_extended("comment.warning", color: "#c1a78e", bold: true)
      t.set("constant", "#ece1d7")
      t.set("constant.builtin", "#b380b0")
      t.set("constant.macro", "#b380b0")
      t.set("constructor", "#ebc06d")
      t.set("function", "#ebc06d")
      t.set("function.builtin", "#ebc06d")
      t.set("function.macro", "#ebc06d")
      t.set("ibl.indent.char.1", "#403a36")
      t.set("ibl.scope.char.1", "#867462")
      t.set("ibl.whitespace.char.1", "#403a36")
      t.set("keyword", "#e49b5d")
      t.set("keyword.directive", "#85b695")
      t.set("keyword.function", "#85b695")
      t.set("keyword.import", "#85b695")
      t.set("label", "#89b3b6")
      t.set("markup", "#ebc06d")
      t.set("markup.heading", "#e49b5d")
      t.set("markup.heading.2", "#ebc06d")
      t.set("markup.heading.3", "#85b695")
      t.set("markup.heading.4", "#89b3b6")
      t.set("markup.link.url", "#7f91b2")
      t.set("markup.list", "#8b7449")
      t.set_extended("markup.quote", color: "#c1a78e", italic: true)
      t.set("markup.raw", "#c1a78e")
      t.set("module", "#ece1d7")
      t.set("module.builtin", "#ece1d7")
      t.set("number", "#cf9bc2")
      t.set("number.float", "#cf9bc2")
      t.set("operator", "#d47766")
      t.set("property", "#ece1d7")
      t.set("punctuation", "#8b7449")
      t.set("punctuation.delimiter", "#bd8183")
      t.set("punctuation.special", "#ebc06d")
      t.set_extended("string", color: "#a3a9ce", italic: true)
      t.set("string.documentation", "#a3a9ce")
      t.set("string.escape", "#7f91b2")
      t.set("string.regexp", "#a3a9ce")
      t.set("string.special", "#89b3b6")
      t.set("string.special.path", "#7f91b2")
      t.set_extended("string.special.symbol", color: "#ece1d7", italic: true)
      t.set("string.special.url", "#7f91b2")
      t.set("tag", "#ebc06d")
      t.set("tag.attribute", "#89b3b6")
      t.set("tag.builtin", "#ebc06d")
      t.set("tag.delimiter", "#8b7449")
      t.set("type", "#7b9695")
      t.set("type.builtin", "#ebc06d")
      t.set("type.qualifier", "#e49b5d")
      t.set("variable", "#ece1d7")
      t.set_extended("variable.builtin", color: "#ece1d7", italic: true)
      t.set("variable.parameter.builtin", "#ebc06d")
      t.resolve
    end
  end
end
