module TreeSitterManager
  module Themes
    def minimal_minimal : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#dfe0ea", bg: "#191b20")
      t.set("attribute", "#e85a84")
      t.set("attribute.builtin", "#515669")
      t.set("boolean", "#e0828d")
      t.set("character", "#e9d26c")
      t.set("character.special", "#e9d26c")
      t.set_extended("comment", color: "#4d5264", italic: true)
      t.set("comment.error", "#d95555")
      t.set("comment.note", "#e9d26c")
      t.set_extended("comment.todo", color: "#e9d26c", bold: true)
      t.set("comment.warning", "#e39a65")
      t.set("constant", "#d895c7")
      t.set("constant.builtin", "#515669")
      t.set("constructor", "#515669")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#94dd8e")
      t.set("function.builtin", "#515669")
      t.set("ibl.indent.char.1", "#606978")
      t.set("ibl.scope.char.1", "#555b6c")
      t.set("ibl.whitespace.char.1", "#606978")
      t.set("keyword", "#e85a84")
      t.set("label", "#e85a84")
      t.set("markup", "#515669")
      t.set_extended("markup.heading", color: "#515669", bold: true)
      t.set("module", "#94dd8e")
      t.set("module.builtin", "#515669")
      t.set("number", "#e0828d")
      t.set("number.float", "#e0828d")
      t.set("operator", "#dfe0ea")
      t.set("property", "#cfd0d7")
      t.set("punctuation", "#515669")
      t.set("punctuation.special", "#515669")
      t.set("string", "#e9d26c")
      t.set("string.escape", "#e9d26c")
      t.set("string.regexp", "#e9d26c")
      t.set("string.special", "#e9d26c")
      t.set("tag", "#515669")
      t.set("tag.builtin", "#515669")
      t.set("type", "#7eb7e6")
      t.set("type.builtin", "#515669")
      t.set("variable", "#e0e2ea")
      t.set("variable.builtin", "#515669")
      t.set("variable.parameter.builtin", "#515669")
      t.resolve
    end
  end
end
