module TreeSitterManager
  module Themes
    def monokai_monokai : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#f8f8f0", bg: "#26292c")
      t.set("annotation", "#a6e22e")
      t.set("attribute", "#a6e22e")
      t.set("attribute.builtin", "#f8f8f0")
      t.set("boolean", "#ae81ff")
      t.set("character", "#e6db74")
      t.set("character.special", "#ae81ff")
      t.set_extended("comment", color: "#9ca0a4", italic: true)
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#fd971f")
      t.set("comment.warning", "#fce094")
      t.set("conceal", "#8f908a")
      t.set("conditional", "#f92672")
      t.set("conditional.ternary", "#f92672")
      t.set("constant", "#66d9ef")
      t.set("constant.builtin", "#ae81ff")
      t.set("constant.macro", "#ae81ff")
      t.set("constructor", "#66d9ef")
      t.set("debug", "#f92672")
      t.set("define", "#66d9ef")
      t.set("definition", "#a6e22e")
      t.set("definition.associated", "#a6e22e")
      t.set("definition.constant", "#a6e22e")
      t.set("definition.enum", "#a6e22e")
      t.set("definition.field", "#a6e22e")
      t.set("definition.function", "#a6e22e")
      t.set("definition.import", "#f8f8f0")
      t.set("definition.macro", "#a6e22e")
      t.set("definition.method", "#a6e22e")
      t.set("definition.namespace", "#f8f8f0")
      t.set("definition.parameter", "#fd971f")
      t.set("definition.type", "#a6e22e")
      t.set("definition.var", "#a6e22e")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#e95678")
      t.set("exception", "#f92672")
      t.set("field", "#f8f8f0")
      t.set("float", "#ae81ff")
      t.set_extended("function", color: "#a6e22e", italic: true)
      t.set("function.builtin", "#66d9ef")
      t.set("function.call", "#f8f8f0")
      t.set_extended("function.macro", color: "#a6e22e", italic: true)
      t.set("ibl.indent.char.1", "#4d5154")
      t.set("ibl.scope.char.1", "#4d5154")
      t.set("ibl.whitespace.char.1", "#4d5154")
      t.set_extended("include", color: "#66d9ef", italic: true)
      t.set_extended("keyword", color: "#f92672", italic: true)
      t.set_extended("keyword.function", color: "#66d9ef", italic: true)
      t.set("keyword.operator", "#f92672")
      t.set("keyword.return", "#f92672")
      t.set("label", "#f92672")
      t.set("markup", "#f8f8f0")
      t.set_extended("markup.heading", color: "#e6db74", bold: true)
      t.set("math", "#e6db74")
      t.set("method", "#a6e22e")
      t.set("method.call", "#f8f8f0")
      t.set("module", "#66d9ef")
      t.set("module.builtin", "#f8f8f0")
      t.set("namespace", "#ae81ff")
      t.set("number", "#ae81ff")
      t.set("number.float", "#ae81ff")
      t.set("operator", "#f92672")
      t.set("parameter", "#fd971f")
      t.set("parameter.reference", "#f8f8f0")
      t.set("preproc", "#a6e22e")
      t.set("property", "#f8f8f0")
      t.set("punctuation", "#f8f8f0")
      t.set("punctuation.bracket", "#f8f8f0")
      t.set("punctuation.delimiter", "#f8f8f0")
      t.set("punctuation.special", "#f92672")
      t.set("reference", "#f8f8f0")
      t.set("repeat", "#f92672")
      t.set("scope", "#f8f8f0")
      t.set("storageclass", "#66d9ef")
      t.set("storageclass.lifetime", "#66d9ef")
      t.set("strike", "#8f908a")
      t.set("string", "#e6db74")
      t.set("string.escape", "#ae81ff")
      t.set("string.regex", "#ae81ff")
      t.set("string.regexp", "#ae81ff")
      t.set("string.special", "#ae81ff")
      t.set("symbol", "#ae81ff")
      t.set("tag", "#f92672")
      t.set("tag.attribute", "#a6e22e")
      t.set("tag.builtin", "#f8f8f0")
      t.set("tag.delimiter", "#f8f8f0")
      t.set("text", "#a6e22e")
      t.set_extended("text.danger", color: "#e95678", bold: true)
      t.set("text.diff.add", "#3d5213")
      t.set("text.diff.delete", "#4a0f23")
      t.set("text.environment", "#ae81ff")
      t.set("text.environment.name", "#66d9ef")
      t.set("text.literal", "#e6db74")
      t.set("text.math", "#e6db74")
      t.set_extended("text.note", color: "#66d9ef", bold: true)
      t.set("text.quote", "#8f908a")
      t.set_extended("text.reference", color: "#fd971f", italic: true)
      t.set("text.strike", "#8f908a")
      t.set_extended("text.title", color: "#e6db74", bold: true)
      t.set("text.todo", "#66d9ef")
      t.set_extended("text.uri", color: "#66d9ef", underline: true)
      t.set_extended("text.warning", color: "#e6db74", bold: true)
      t.set("todo", "#66d9ef")
      t.set("type", "#66d9ef")
      t.set("type.builtin", "#66d9ef")
      t.set("type.definition", "#66d9ef")
      t.set("type.qualifier", "#f92672")
      t.set_extended("uri", color: "#66d9ef", underline: true)
      t.set("variable", "#f8f8f0")
      t.set("variable.builtin", "#fd971f")
      t.set("variable.parameter.builtin", "#f8f8f0")
      t.resolve
    end

    def monokai_ristretto : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#fff1f3", bg: "#26292c")
      t.set("annotation", "#adda78")
      t.set("attribute", "#adda78")
      t.set("attribute.builtin", "#fff1f3")
      t.set("boolean", "#a8a9eb")
      t.set("character", "#f9cc6c")
      t.set("character.special", "#a8a9eb")
      t.set_extended("comment", color: "#8c8384", italic: true)
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#f38d70")
      t.set("comment.warning", "#fce094")
      t.set("conceal", "#72696a")
      t.set("conditional", "#ff6188")
      t.set("conditional.ternary", "#ff6188")
      t.set("constant", "#85dacc")
      t.set("constant.builtin", "#a8a9eb")
      t.set("constant.macro", "#a8a9eb")
      t.set("constructor", "#85dacc")
      t.set("debug", "#ff6188")
      t.set("define", "#85dacc")
      t.set("definition", "#adda78")
      t.set("definition.associated", "#adda78")
      t.set("definition.constant", "#adda78")
      t.set("definition.enum", "#adda78")
      t.set("definition.field", "#adda78")
      t.set("definition.function", "#adda78")
      t.set("definition.import", "#fff1f3")
      t.set("definition.macro", "#adda78")
      t.set("definition.method", "#adda78")
      t.set("definition.namespace", "#fff1f3")
      t.set("definition.parameter", "#f38d70")
      t.set("definition.type", "#adda78")
      t.set("definition.var", "#adda78")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#fd6883")
      t.set("exception", "#ff6188")
      t.set("field", "#fff1f3")
      t.set("float", "#a8a9eb")
      t.set_extended("function", color: "#adda78", italic: true)
      t.set("function.builtin", "#85dacc")
      t.set("function.call", "#fff1f3")
      t.set_extended("function.macro", color: "#adda78", italic: true)
      t.set("ibl.indent.char.1", "#72696a")
      t.set("ibl.scope.char.1", "#72696a")
      t.set("ibl.whitespace.char.1", "#72696a")
      t.set_extended("include", color: "#85dacc", italic: true)
      t.set_extended("keyword", color: "#ff6188", italic: true)
      t.set_extended("keyword.function", color: "#85dacc", italic: true)
      t.set("keyword.operator", "#ff6188")
      t.set("keyword.return", "#ff6188")
      t.set("label", "#ff6188")
      t.set("markup", "#fff1f3")
      t.set_extended("markup.heading", color: "#f9cc6c", bold: true)
      t.set("math", "#f9cc6c")
      t.set("method", "#adda78")
      t.set("method.call", "#fff1f3")
      t.set("module", "#85dacc")
      t.set("module.builtin", "#fff1f3")
      t.set("namespace", "#a8a9eb")
      t.set("number", "#a8a9eb")
      t.set("number.float", "#a8a9eb")
      t.set("operator", "#ff6188")
      t.set("parameter", "#f38d70")
      t.set("parameter.reference", "#fff1f3")
      t.set("preproc", "#adda78")
      t.set("property", "#fff1f3")
      t.set("punctuation", "#fff1f3")
      t.set("punctuation.bracket", "#fff1f3")
      t.set("punctuation.delimiter", "#fff1f3")
      t.set("punctuation.special", "#ff6188")
      t.set("reference", "#fff1f3")
      t.set("repeat", "#ff6188")
      t.set("scope", "#fff1f3")
      t.set("storageclass", "#85dacc")
      t.set("storageclass.lifetime", "#85dacc")
      t.set("strike", "#72696a")
      t.set("string", "#f9cc6c")
      t.set("string.escape", "#a8a9eb")
      t.set("string.regex", "#a8a9eb")
      t.set("string.regexp", "#a8a9eb")
      t.set("string.special", "#a8a9eb")
      t.set("symbol", "#a8a9eb")
      t.set("tag", "#ff6188")
      t.set("tag.attribute", "#adda78")
      t.set("tag.builtin", "#fff1f3")
      t.set("tag.delimiter", "#fff1f3")
      t.set("text", "#adda78")
      t.set_extended("text.danger", color: "#fd6883", bold: true)
      t.set("text.diff.add", "#527728")
      t.set("text.diff.delete", "#842335")
      t.set("text.environment", "#a8a9eb")
      t.set("text.environment.name", "#85dacc")
      t.set("text.literal", "#f9cc6c")
      t.set("text.math", "#f9cc6c")
      t.set_extended("text.note", color: "#85dacc", bold: true)
      t.set("text.quote", "#72696a")
      t.set_extended("text.reference", color: "#f38d70", italic: true)
      t.set("text.strike", "#72696a")
      t.set_extended("text.title", color: "#f9cc6c", bold: true)
      t.set("text.todo", "#85dacc")
      t.set_extended("text.uri", color: "#85dacc", underline: true)
      t.set_extended("text.warning", color: "#f9cc6c", bold: true)
      t.set("todo", "#85dacc")
      t.set("type", "#85dacc")
      t.set("type.builtin", "#85dacc")
      t.set("type.definition", "#85dacc")
      t.set("type.qualifier", "#ff6188")
      t.set_extended("uri", color: "#85dacc", underline: true)
      t.set("variable", "#fff1f3")
      t.set("variable.builtin", "#f38d70")
      t.set("variable.parameter.builtin", "#fff1f3")
      t.resolve
    end

    def monokai_soda : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#f6f6ec", bg: "#2c2525")
      t.set("annotation", "#97e023")
      t.set("attribute", "#97e023")
      t.set("attribute.builtin", "#f6f6ec")
      t.set("boolean", "#9c64fe")
      t.set("character", "#dfd561")
      t.set("character.special", "#9c64fe")
      t.set_extended("comment", color: "#72696a", italic: true)
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#fa8419")
      t.set("comment.warning", "#fce094")
      t.set("conceal", "#72696a")
      t.set("conditional", "#f3005f")
      t.set("conditional.ternary", "#f3005f")
      t.set("constant", "#78dce8")
      t.set("constant.builtin", "#9c64fe")
      t.set("constant.macro", "#9c64fe")
      t.set("constructor", "#78dce8")
      t.set("debug", "#f3005f")
      t.set("define", "#78dce8")
      t.set("definition", "#97e023")
      t.set("definition.associated", "#97e023")
      t.set("definition.constant", "#97e023")
      t.set("definition.enum", "#97e023")
      t.set("definition.field", "#97e023")
      t.set("definition.function", "#97e023")
      t.set("definition.import", "#f6f6ec")
      t.set("definition.macro", "#97e023")
      t.set("definition.method", "#97e023")
      t.set("definition.namespace", "#f6f6ec")
      t.set("definition.parameter", "#fa8419")
      t.set("definition.type", "#97e023")
      t.set("definition.var", "#97e023")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#f3005f")
      t.set("exception", "#f3005f")
      t.set("field", "#f6f6ec")
      t.set("float", "#9c64fe")
      t.set_extended("function", color: "#97e023", italic: true)
      t.set("function.builtin", "#78dce8")
      t.set("function.call", "#f6f6ec")
      t.set_extended("function.macro", color: "#97e023", italic: true)
      t.set("ibl.indent.char.1", "#4d5154")
      t.set("ibl.scope.char.1", "#4d5154")
      t.set("ibl.whitespace.char.1", "#4d5154")
      t.set_extended("include", color: "#78dce8", italic: true)
      t.set_extended("keyword", color: "#f3005f", italic: true)
      t.set_extended("keyword.function", color: "#78dce8", italic: true)
      t.set("keyword.operator", "#f3005f")
      t.set("keyword.return", "#f3005f")
      t.set("label", "#f3005f")
      t.set("markup", "#f6f6ec")
      t.set_extended("markup.heading", color: "#dfd561", bold: true)
      t.set("math", "#dfd561")
      t.set("method", "#97e023")
      t.set("method.call", "#f6f6ec")
      t.set("module", "#78dce8")
      t.set("module.builtin", "#f6f6ec")
      t.set("namespace", "#9c64fe")
      t.set("number", "#9c64fe")
      t.set("number.float", "#9c64fe")
      t.set("operator", "#f3005f")
      t.set("parameter", "#fa8419")
      t.set("parameter.reference", "#f6f6ec")
      t.set("preproc", "#97e023")
      t.set("property", "#f6f6ec")
      t.set("punctuation", "#f6f6ec")
      t.set("punctuation.bracket", "#f6f6ec")
      t.set("punctuation.delimiter", "#f6f6ec")
      t.set("punctuation.special", "#f3005f")
      t.set("reference", "#f6f6ec")
      t.set("repeat", "#f3005f")
      t.set("scope", "#f6f6ec")
      t.set("storageclass", "#78dce8")
      t.set("storageclass.lifetime", "#78dce8")
      t.set("strike", "#72696a")
      t.set("string", "#dfd561")
      t.set("string.escape", "#9c64fe")
      t.set("string.regex", "#9c64fe")
      t.set("string.regexp", "#9c64fe")
      t.set("string.special", "#9c64fe")
      t.set("symbol", "#9c64fe")
      t.set("tag", "#f3005f")
      t.set("tag.attribute", "#97e023")
      t.set("tag.builtin", "#f6f6ec")
      t.set("tag.delimiter", "#f6f6ec")
      t.set("text", "#97e023")
      t.set_extended("text.danger", color: "#f3005f", bold: true)
      t.set("text.diff.add", "#3d5213")
      t.set("text.diff.delete", "#4a0f23")
      t.set("text.environment", "#9c64fe")
      t.set("text.environment.name", "#78dce8")
      t.set("text.literal", "#dfd561")
      t.set("text.math", "#dfd561")
      t.set_extended("text.note", color: "#78dce8", bold: true)
      t.set("text.quote", "#72696a")
      t.set_extended("text.reference", color: "#fa8419", italic: true)
      t.set("text.strike", "#72696a")
      t.set_extended("text.title", color: "#dfd561", bold: true)
      t.set("text.todo", "#78dce8")
      t.set_extended("text.uri", color: "#78dce8", underline: true)
      t.set_extended("text.warning", color: "#dfd561", bold: true)
      t.set("todo", "#78dce8")
      t.set("type", "#78dce8")
      t.set("type.builtin", "#78dce8")
      t.set("type.definition", "#78dce8")
      t.set("type.qualifier", "#f3005f")
      t.set_extended("uri", color: "#78dce8", underline: true)
      t.set("variable", "#f6f6ec")
      t.set("variable.builtin", "#fa8419")
      t.set("variable.parameter.builtin", "#f6f6ec")
      t.resolve
    end

    def monokai_pro : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#fff1f3", bg: "#26292c")
      t.set("annotation", "#a9dc76")
      t.set("attribute", "#a9dc76")
      t.set("attribute.builtin", "#fff1f3")
      t.set("boolean", "#ab9df2")
      t.set("character", "#ffd866")
      t.set("character.special", "#ab9df2")
      t.set_extended("comment", color: "#72696a", italic: true)
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#fc9867")
      t.set("comment.warning", "#fce094")
      t.set("conceal", "#72696a")
      t.set("conditional", "#ff6188")
      t.set("conditional.ternary", "#ff6188")
      t.set("constant", "#78dce8")
      t.set("constant.builtin", "#ab9df2")
      t.set("constant.macro", "#ab9df2")
      t.set("constructor", "#78dce8")
      t.set("debug", "#ff6188")
      t.set("define", "#78dce8")
      t.set("definition", "#a9dc76")
      t.set("definition.associated", "#a9dc76")
      t.set("definition.constant", "#a9dc76")
      t.set("definition.enum", "#a9dc76")
      t.set("definition.field", "#a9dc76")
      t.set("definition.function", "#a9dc76")
      t.set("definition.import", "#fff1f3")
      t.set("definition.macro", "#a9dc76")
      t.set("definition.method", "#a9dc76")
      t.set("definition.namespace", "#fff1f3")
      t.set("definition.parameter", "#fc9867")
      t.set("definition.type", "#a9dc76")
      t.set("definition.var", "#a9dc76")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#fd6883")
      t.set("exception", "#ff6188")
      t.set("field", "#fff1f3")
      t.set("float", "#ab9df2")
      t.set_extended("function", color: "#a9dc76", italic: true)
      t.set("function.builtin", "#78dce8")
      t.set("function.call", "#fff1f3")
      t.set_extended("function.macro", color: "#a9dc76", italic: true)
      t.set("ibl.indent.char.1", "#4d5154")
      t.set("ibl.scope.char.1", "#4d5154")
      t.set("ibl.whitespace.char.1", "#4d5154")
      t.set_extended("include", color: "#78dce8", italic: true)
      t.set_extended("keyword", color: "#ff6188", italic: true)
      t.set_extended("keyword.function", color: "#78dce8", italic: true)
      t.set("keyword.operator", "#ff6188")
      t.set("keyword.return", "#ff6188")
      t.set("label", "#ff6188")
      t.set("markup", "#fff1f3")
      t.set_extended("markup.heading", color: "#ffd866", bold: true)
      t.set("math", "#ffd866")
      t.set("method", "#a9dc76")
      t.set("method.call", "#fff1f3")
      t.set("module", "#78dce8")
      t.set("module.builtin", "#fff1f3")
      t.set("namespace", "#ab9df2")
      t.set("number", "#ab9df2")
      t.set("number.float", "#ab9df2")
      t.set("operator", "#ff6188")
      t.set("parameter", "#fc9867")
      t.set("parameter.reference", "#fff1f3")
      t.set("preproc", "#a9dc76")
      t.set("property", "#fff1f3")
      t.set("punctuation", "#fff1f3")
      t.set("punctuation.bracket", "#fff1f3")
      t.set("punctuation.delimiter", "#fff1f3")
      t.set("punctuation.special", "#ff6188")
      t.set("reference", "#fff1f3")
      t.set("repeat", "#ff6188")
      t.set("scope", "#fff1f3")
      t.set("storageclass", "#78dce8")
      t.set("storageclass.lifetime", "#78dce8")
      t.set("strike", "#72696a")
      t.set("string", "#ffd866")
      t.set("string.escape", "#ab9df2")
      t.set("string.regex", "#ab9df2")
      t.set("string.regexp", "#ab9df2")
      t.set("string.special", "#ab9df2")
      t.set("symbol", "#ab9df2")
      t.set("tag", "#ff6188")
      t.set("tag.attribute", "#a9dc76")
      t.set("tag.builtin", "#fff1f3")
      t.set("tag.delimiter", "#fff1f3")
      t.set("text", "#a9dc76")
      t.set_extended("text.danger", color: "#fd6883", bold: true)
      t.set("text.diff.add", "#3d5213")
      t.set("text.diff.delete", "#4a0f23")
      t.set("text.environment", "#ab9df2")
      t.set("text.environment.name", "#78dce8")
      t.set("text.literal", "#ffd866")
      t.set("text.math", "#ffd866")
      t.set_extended("text.note", color: "#78dce8", bold: true)
      t.set("text.quote", "#72696a")
      t.set_extended("text.reference", color: "#fc9867", italic: true)
      t.set("text.strike", "#72696a")
      t.set_extended("text.title", color: "#ffd866", bold: true)
      t.set("text.todo", "#78dce8")
      t.set_extended("text.uri", color: "#78dce8", underline: true)
      t.set_extended("text.warning", color: "#ffd866", bold: true)
      t.set("todo", "#78dce8")
      t.set("type", "#78dce8")
      t.set("type.builtin", "#78dce8")
      t.set("type.definition", "#78dce8")
      t.set("type.qualifier", "#ff6188")
      t.set_extended("uri", color: "#78dce8", underline: true)
      t.set("variable", "#fff1f3")
      t.set("variable.builtin", "#fc9867")
      t.set("variable.parameter.builtin", "#fff1f3")
      t.resolve
    end
  end
end
