module TreeSitterManager
  module Themes
    def moonfly_moonfly : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c6c6c6", bg: "#080808")
      t.set("attribute", "#74b2ff")
      t.set("attribute.bind.html", "#74b2ff")
      t.set("attribute.builtin", "#e65e72")
      t.set("attribute.directive.value.html", "#adadf3")
      t.set("attribute.on.html", "#36c692")
      t.set("attribute.zig", "#cf87e8")
      t.set("boolean", "#e65e72")
      t.set("character", "#ae81ff")
      t.set("character.special", "#e65e72")
      t.set("character.special.vim", "#74b2ff")
      t.set_extended("comment", color: "#949494", italic: true)
      t.set("comment.error", "#ff5454")
      t.set("comment.note", "#949494")
      t.set("comment.ok", "#8cc85f")
      t.set("comment.todo", "#e3c78a")
      t.set("comment.warning", "#e3c78a")
      t.set("conditional", "#cf87e8")
      t.set("constant", "#79dac8")
      t.set("constant.builtin", "#8cc85f")
      t.set("constant.macro", "#cf87e8")
      t.set("constructor", "#36c692")
      t.set("define", "#e65e72")
      t.set("diff.minus", "#626262")
      t.set("error", "#ff5454")
      t.set("exception", "#cf87e8")
      t.set("field", "#adadf3")
      t.set("field.yaml", "#80a0ff")
      t.set("function", "#74b2ff")
      t.set("function.builtin", "#74b2ff")
      t.set("function.call", "#74b2ff")
      t.set("function.macro", "#79dac8")
      t.set("function.macro.vim", "#74b2ff")
      t.set("function.method", "#74b2ff")
      t.set("function.method.call", "#74b2ff")
      t.set("ibl.indent.char.1", "#262626")
      t.set("ibl.scope.char.1", "#cf87e8")
      t.set("ibl.whitespace.char.1", "#262626")
      t.set("include", "#e65e72")
      t.set("include.rust", "#cf87e8")
      t.set("keyword", "#cf87e8")
      t.set("keyword.conditional", "#cf87e8")
      t.set("keyword.directive", "#e65e72")
      t.set("keyword.directive.define", "#e65e72")
      t.set("keyword.exception", "#cf87e8")
      t.set("keyword.gitcommit", "#74b2ff")
      t.set("keyword.import", "#e65e72")
      t.set("keyword.import.bash", "#cf87e8")
      t.set("keyword.import.rust", "#cf87e8")
      t.set("keyword.operator", "#cf87e8")
      t.set("keyword.repeat", "#cf87e8")
      t.set("keyword.storage", "#cf87e8")
      t.set("keyword.storage.rust", "#cf87e8")
      t.set("label", "#79dac8")
      t.set("markup", "#e65e72")
      t.set("markup.environment", "#cf87e8")
      t.set("markup.environment.name", "#36c692")
      t.set("markup.heading", "#cf87e8")
      t.set("markup.heading.1.markdown", "#36c692")
      t.set("markup.heading.1.vimdoc", "#80a0ff")
      t.set("markup.heading.2.markdown", "#adadf3")
      t.set("markup.heading.2.vimdoc", "#80a0ff")
      t.set("markup.heading.3.markdown", "#79dac8")
      t.set("markup.heading.4.markdown", "#de935f")
      t.set("markup.heading.5.markdown", "#74b2ff")
      t.set("markup.heading.6.markdown", "#cf87e8")
      t.set("markup.heading.help", "#74b2ff")
      t.set("markup.heading.markdown", "#74b2ff")
      t.set_extended("markup.italic", color: "#e196a2", italic: true)
      t.set("markup.link", "#8cc85f")
      t.set("markup.link.gitcommit", "#80a0ff")
      t.set("markup.link.label", "#8cc85f")
      t.set_extended("markup.link.url", color: "#ae81ff", underline: true)
      t.set_extended("markup.link.url.astro", color: "#cf87e8", italic: true)
      t.set("markup.link.url.gitcommit", "#36c692")
      t.set_extended("markup.link.url.html", color: "#cf87e8", italic: true)
      t.set_extended("markup.link.url.svelte", color: "#cf87e8", italic: true)
      t.set_extended("markup.link.url.vue", color: "#cf87e8", italic: true)
      t.set("markup.list", "#e65e72")
      t.set("markup.list.checked", "#79dac8")
      t.set("markup.list.latex", "#ae81ff")
      t.set("markup.list.unchecked", "#80a0ff")
      t.set("markup.math", "#74b2ff")
      t.set("markup.quote", "#949494")
      t.set("markup.raw", "#c6c684")
      t.set("markup.raw.vimdoc", "#e196a2")
      t.set("markup.strong", "#e196a2")
      t.set("method", "#74b2ff")
      t.set("module", "#79dac8")
      t.set("module.builtin", "#8cc85f")
      t.set("namespace", "#79dac8")
      t.set("namespace.builtin", "#8cc85f")
      t.set("namespace.latex", "#adadf3")
      t.set("number", "#de935f")
      t.set("number.float", "#de935f")
      t.set("operator", "#e65e72")
      t.set("parameter", "#e196a2")
      t.set("parameter.bash", "#79dac8")
      t.set("parameter.builtin", "#e196a2")
      t.set("preproc", "#e65e72")
      t.set("property", "#adadf3")
      t.set("punctuation", "#c6c6c6")
      t.set("punctuation.delimiter.astro", "#e65e72")
      t.set("punctuation.delimiter.css", "#e65e72")
      t.set("punctuation.delimiter.rust", "#e65e72")
      t.set("punctuation.delimiter.scss", "#e65e72")
      t.set("punctuation.delimiter.yaml", "#e65e72")
      t.set("punctuation.special", "#e65e72")
      t.set("repeat", "#cf87e8")
      t.set("storageclass", "#cf87e8")
      t.set("storageclass.rust", "#cf87e8")
      t.set("string", "#c6c684")
      t.set("string.documentation", "#79dac8")
      t.set("string.escape", "#e65e72")
      t.set("string.json", "#85dc85")
      t.set("string.regex", "#79dac8")
      t.set("string.regexp", "#79dac8")
      t.set("string.special", "#e65e72")
      t.set("string.special.path", "#e196a2")
      t.set("string.special.symbol", "#ae81ff")
      t.set("string.special.url", "#ae81ff")
      t.set("symbol", "#ae81ff")
      t.set("tag", "#80a0ff")
      t.set("tag.attribute", "#79dac8")
      t.set("tag.builtin", "#80a0ff")
      t.set("tag.delimiter", "#8cc85f")
      t.set("tag.javascript", "#36c692")
      t.set("tag.jsx", "#36c692")
      t.set("tag.tsx", "#36c692")
      t.set("tag.typescript", "#36c692")
      t.set("text.danger", "#ff5454")
      t.set("text.diff.delete", "#626262")
      t.set_extended("text.emphasis", color: "#e196a2", italic: true)
      t.set("text.environment", "#cf87e8")
      t.set("text.environment.name", "#36c692")
      t.set("text.literal", "#c6c684")
      t.set("text.literal.vimdoc", "#e196a2")
      t.set("text.math", "#74b2ff")
      t.set("text.note", "#949494")
      t.set("text.reference", "#8cc85f")
      t.set("text.reference.gitcommit", "#80a0ff")
      t.set("text.reference.markdown_inline", "#8cc85f")
      t.set("text.strong", "#e196a2")
      t.set("text.title", "#cf87e8")
      t.set("text.title.1.markdown", "#36c692")
      t.set("text.title.1.marker.markdown", "#e65e72")
      t.set("text.title.1.vimdoc", "#80a0ff")
      t.set("text.title.2.markdown", "#adadf3")
      t.set("text.title.2.marker.markdown", "#e65e72")
      t.set("text.title.2.vimdoc", "#80a0ff")
      t.set("text.title.3.markdown", "#79dac8")
      t.set("text.title.3.marker.markdown", "#e65e72")
      t.set("text.title.4.markdown", "#de935f")
      t.set("text.title.4.marker.markdown", "#e65e72")
      t.set("text.title.5.markdown", "#74b2ff")
      t.set("text.title.5.marker.markdown", "#e65e72")
      t.set("text.title.6.markdown", "#cf87e8")
      t.set("text.title.6.marker.markdown", "#e65e72")
      t.set("text.title.help", "#74b2ff")
      t.set("text.title.markdown", "#74b2ff")
      t.set("text.todo", "#e3c78a")
      t.set_extended("text.uri", color: "#ae81ff", underline: true)
      t.set_extended("text.uri.astro", color: "#cf87e8", italic: true)
      t.set("text.uri.gitcommit", "#36c692")
      t.set_extended("text.uri.html", color: "#cf87e8", italic: true)
      t.set_extended("text.uri.svelte", color: "#cf87e8", italic: true)
      t.set_extended("text.uri.vue", color: "#cf87e8", italic: true)
      t.set("text.warning", "#e3c78a")
      t.set("type", "#36c692")
      t.set("type.builtin", "#36c692")
      t.set("type.qualifier", "#cf87e8")
      t.set("variable", "#c6c6c6")
      t.set("variable.builtin", "#8cc85f")
      t.set("variable.builtin.vim", "#36c692")
      t.set("variable.member", "#adadf3")
      t.set("variable.member.ruby", "#79dac8")
      t.set("variable.member.yaml", "#80a0ff")
      t.set("variable.parameter", "#e196a2")
      t.set("variable.parameter.bash", "#79dac8")
      t.set("variable.parameter.builtin", "#e65e72")
      t.set("variable.scss", "#79dac8")
      t.set("variable.vim", "#79dac8")
      t.resolve
    end
  end
end
