module TreeSitterManager
  module Themes
    def moonlight_moonlight : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#e4f3fa", bg: "#212337")
      t.set("attribute", "#b994f1")
      t.set("attribute.builtin", "#ff757f")
      t.set("boolean", "#f67f81")
      t.set("character", "#f67f81")
      t.set("character.special", "#ecb2f0")
      t.set("comment", "#7486d6")
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#ffc777", italic: true, bold: true)
      t.set("comment.warning", "#fce094")
      t.set("constant", "#ffc777")
      t.set("constant.builtin", "#ff757f")
      t.set("constructor", "#ff757f")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#04d1f9")
      t.set("function.builtin", "#ff757f")
      t.set("ibl.indent.char.1", "#515772")
      t.set("ibl.scope.char.1", "#596399")
      t.set("ibl.whitespace.char.1", "#515772")
      t.set("keyword", "#b4a4f4")
      t.set("label", "#b4a4f4")
      t.set("markup", "#ff757f")
      t.set_extended("markup.heading", color: "#2df4c0", bold: true)
      t.set_extended("markup.link", color: "#80cbc4", underline: true)
      t.set("module.builtin", "#ff757f")
      t.set("number", "#f67f81")
      t.set("number.float", "#f67f81")
      t.set("operator", "#b994f1")
      t.set("property", "#a6dbff")
      t.set("punctuation", "#b994f1")
      t.set("punctuation.special", "#ff757f")
      t.set_extended("string", color: "#2df4c0", italic: true)
      t.set("string.escape", "#ecb2f0")
      t.set("string.regexp", "#ecb2f0")
      t.set("string.special", "#ecb2f0")
      t.set_extended("string.special.url", color: "#80cbc4", underline: true)
      t.set("tag", "#ff757f")
      t.set("tag.builtin", "#ff757f")
      t.set("type", "#b4a4f4")
      t.set("type.builtin", "#ff757f")
      t.set("variable", "#e0e2ea")
      t.set("variable.builtin", "#ff757f")
      t.set("variable.parameter.builtin", "#ff757f")
      t.resolve
    end
  end
end
