module TreeSitterManager
  module Themes
    def neon_default : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c5cdd9", bg: "#2b2d37")
      t.set("attribute", "#6cb6eb")
      t.set_extended("attribute.builtin", color: "#6cb6eb", italic: true)
      t.set("character", "#da8548")
      t.set("character.special", "#da8548")
      t.set_extended("comment", color: "#7e8294", italic: true)
      t.set("comment.error", "#ec7279")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#4db5bd", italic: true, bold: true)
      t.set("comment.warning", "#fce094")
      t.set("constant", "#a9a1e1")
      t.set_extended("constant.builtin", color: "#6cb6eb", italic: true)
      t.set_extended("constructor", color: "#6cb6eb", italic: true)
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#6cb6eb")
      t.set_extended("function.builtin", color: "#6cb6eb", italic: true)
      t.set("ibl.indent.char.1", "#3a3e4e")
      t.set("ibl.scope.char.1", "#676e95")
      t.set("ibl.whitespace.char.1", "#3a3e4e")
      t.set("keyword", "#6cb6eb")
      t.set("label", "#4db5bd")
      t.set_extended("markup", color: "#6cb6eb", italic: true)
      t.set("markup.heading", "#4db5bd")
      t.set_extended("markup.link", color: "#4db5bd", underline: true)
      t.set("module", "#da8548")
      t.set_extended("module.builtin", color: "#6cb6eb", italic: true)
      t.set("number", "#ec7279")
      t.set("number.float", "#ec7279")
      t.set("operator", "#6cb6eb")
      t.set("property", "#6cb6eb")
      t.set("punctuation", "#ecbe7b")
      t.set_extended("punctuation.special", color: "#6cb6eb", italic: true)
      t.set("string", "#a0c980")
      t.set("string.escape", "#da8548")
      t.set("string.regexp", "#da8548")
      t.set("string.special", "#da8548")
      t.set_extended("string.special.url", color: "#4db5bd", underline: true)
      t.set("tag", "#ec7279")
      t.set_extended("tag.builtin", color: "#6cb6eb", italic: true)
      t.set("type", "#4db5bd")
      t.set_extended("type.builtin", color: "#6cb6eb", italic: true)
      t.set("variable", "#e0e2ea")
      t.set_extended("variable.builtin", color: "#6cb6eb", italic: true)
      t.set_extended("variable.parameter.builtin", color: "#6cb6eb", italic: true)
      t.resolve
    end

    def neon_doom : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#bbc2cf", bg: "#2b2d37")
      t.set("attribute", "#6cb6eb")
      t.set_extended("attribute.builtin", color: "#6cb6eb", italic: true)
      t.set("character", "#da8548")
      t.set("character.special", "#da8548")
      t.set_extended("comment", color: "#7e8294", italic: true)
      t.set("comment.error", "#ec7279")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#4db5bd", italic: true, bold: true)
      t.set("comment.warning", "#fce094")
      t.set("constant", "#a9a1e1")
      t.set_extended("constant.builtin", color: "#6cb6eb", italic: true)
      t.set_extended("constructor", color: "#6cb6eb", italic: true)
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#6cb6eb")
      t.set_extended("function.builtin", color: "#6cb6eb", italic: true)
      t.set("ibl.indent.char.1", "#3f444a")
      t.set("ibl.scope.char.1", "#676e95")
      t.set("ibl.whitespace.char.1", "#3f444a")
      t.set("keyword", "#6cb6eb")
      t.set("label", "#4db5bd")
      t.set_extended("markup", color: "#6cb6eb", italic: true)
      t.set("markup.heading", "#4db5bd")
      t.set_extended("markup.link", color: "#4db5bd", underline: true)
      t.set("module", "#da8548")
      t.set_extended("module.builtin", color: "#6cb6eb", italic: true)
      t.set("number", "#ec7279")
      t.set("number.float", "#ec7279")
      t.set("operator", "#6cb6eb")
      t.set("property", "#6cb6eb")
      t.set("punctuation", "#ecbe7b")
      t.set_extended("punctuation.special", color: "#6cb6eb", italic: true)
      t.set("string", "#a0c980")
      t.set("string.escape", "#da8548")
      t.set("string.regexp", "#da8548")
      t.set("string.special", "#da8548")
      t.set_extended("string.special.url", color: "#4db5bd", underline: true)
      t.set("tag", "#ec7279")
      t.set_extended("tag.builtin", color: "#6cb6eb", italic: true)
      t.set("type", "#4db5bd")
      t.set_extended("type.builtin", color: "#6cb6eb", italic: true)
      t.set("variable", "#e0e2ea")
      t.set_extended("variable.builtin", color: "#6cb6eb", italic: true)
      t.set_extended("variable.parameter.builtin", color: "#6cb6eb", italic: true)
      t.resolve
    end

    def neon_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c5cdd9", bg: "#282c34")
      t.set("attribute", "#6cb6eb")
      t.set_extended("attribute.builtin", color: "#6cb6eb", italic: true)
      t.set("character", "#da8548")
      t.set("character.special", "#da8548")
      t.set_extended("comment", color: "#7e8294", italic: true)
      t.set("comment.error", "#ec7279")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#4db5bd", italic: true, bold: true)
      t.set("comment.warning", "#fce094")
      t.set("constant", "#a9a1e1")
      t.set_extended("constant.builtin", color: "#6cb6eb", italic: true)
      t.set_extended("constructor", color: "#6cb6eb", italic: true)
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#6cb6eb")
      t.set_extended("function.builtin", color: "#6cb6eb", italic: true)
      t.set("ibl.indent.char.1", "#333644")
      t.set("ibl.scope.char.1", "#676e95")
      t.set("ibl.whitespace.char.1", "#333644")
      t.set("keyword", "#6cb6eb")
      t.set("label", "#4db5bd")
      t.set_extended("markup", color: "#6cb6eb", italic: true)
      t.set("markup.heading", "#4db5bd")
      t.set_extended("markup.link", color: "#4db5bd", underline: true)
      t.set("module", "#da8548")
      t.set_extended("module.builtin", color: "#6cb6eb", italic: true)
      t.set("number", "#ec7279")
      t.set("number.float", "#ec7279")
      t.set("operator", "#6cb6eb")
      t.set("property", "#6cb6eb")
      t.set("punctuation", "#ecbe7b")
      t.set_extended("punctuation.special", color: "#6cb6eb", italic: true)
      t.set("string", "#a0c980")
      t.set("string.escape", "#da8548")
      t.set("string.regexp", "#da8548")
      t.set("string.special", "#da8548")
      t.set_extended("string.special.url", color: "#4db5bd", underline: true)
      t.set("tag", "#ec7279")
      t.set_extended("tag.builtin", color: "#6cb6eb", italic: true)
      t.set("type", "#4db5bd")
      t.set_extended("type.builtin", color: "#6cb6eb", italic: true)
      t.set("variable", "#e0e2ea")
      t.set_extended("variable.builtin", color: "#6cb6eb", italic: true)
      t.set_extended("variable.parameter.builtin", color: "#6cb6eb", italic: true)
      t.resolve
    end

    def neon_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#4c566a", bg: "#0d1117")
      t.set("attribute", "#2257a0")
      t.set_extended("attribute.builtin", color: "#2257a0", italic: true)
      t.set("character", "#da8548")
      t.set("character.special", "#da8548")
      t.set_extended("comment", color: "#7e8294", italic: true)
      t.set("comment.error", "#ff6655")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#0997b3", italic: true, bold: true)
      t.set("comment.warning", "#fce094")
      t.set("constant", "#9370db")
      t.set_extended("constant.builtin", color: "#2257a0", italic: true)
      t.set_extended("constructor", color: "#2257a0", italic: true)
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#2257a0")
      t.set_extended("function.builtin", color: "#2257a0", italic: true)
      t.set("ibl.indent.char.1", "#a0a1a7")
      t.set("ibl.scope.char.1", "#676e95")
      t.set("ibl.whitespace.char.1", "#a0a1a7")
      t.set("keyword", "#2257a0")
      t.set("label", "#0997b3")
      t.set_extended("markup", color: "#2257a0", italic: true)
      t.set("markup.heading", "#0997b3")
      t.set_extended("markup.link", color: "#0997b3", underline: true)
      t.set("module", "#da8548")
      t.set_extended("module.builtin", color: "#2257a0", italic: true)
      t.set("number", "#ff6655")
      t.set("number.float", "#ff6655")
      t.set("operator", "#2257a0")
      t.set("property", "#2257a0")
      t.set("punctuation", "#c18401")
      t.set_extended("punctuation.special", color: "#2257a0", italic: true)
      t.set("string", "#50a14f")
      t.set("string.escape", "#da8548")
      t.set("string.regexp", "#da8548")
      t.set("string.special", "#da8548")
      t.set_extended("string.special.url", color: "#0997b3", underline: true)
      t.set("tag", "#ff6655")
      t.set_extended("tag.builtin", color: "#2257a0", italic: true)
      t.set("type", "#0997b3")
      t.set_extended("type.builtin", color: "#2257a0", italic: true)
      t.set("variable", "#e0e2ea")
      t.set_extended("variable.builtin", color: "#2257a0", italic: true)
      t.set_extended("variable.parameter.builtin", color: "#2257a0", italic: true)
      t.resolve
    end
  end
end
