module TreeSitterManager
  module Themes
    def nightfly_nightfly : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c3ccdc", bg: "#011627")
      t.set("attribute", "#82aaff")
      t.set("attribute.bind.html", "#87bcff")
      t.set("attribute.builtin", "#ff5874")
      t.set("attribute.directive.value.html", "#b0b2f4")
      t.set("attribute.on.html", "#21c7a8")
      t.set("attribute.zig", "#c792ea")
      t.set("boolean", "#ff5874")
      t.set("character", "#ae81ff")
      t.set("character.special", "#ff5874")
      t.set("character.special.vim", "#82aaff")
      t.set_extended("comment", color: "#7c8f8f", italic: true)
      t.set("comment.error", "#fc514e")
      t.set("comment.note", "#7c8f8f")
      t.set("comment.ok", "#a1cd5e")
      t.set("comment.todo", "#e3d18a")
      t.set("comment.warning", "#e3d18a")
      t.set("conditional", "#c792ea")
      t.set("constant", "#7fdbca")
      t.set("constant.builtin", "#a1cd5e")
      t.set("constant.macro", "#c792ea")
      t.set("constructor", "#21c7a8")
      t.set("define", "#ff5874")
      t.set("diff.minus", "#4b6479")
      t.set("error", "#fc514e")
      t.set("exception", "#c792ea")
      t.set("field", "#b0b2f4")
      t.set("field.yaml", "#82aaff")
      t.set("function", "#82aaff")
      t.set("function.builtin", "#82aaff")
      t.set("function.call", "#82aaff")
      t.set("function.macro", "#7fdbca")
      t.set("function.macro.vim", "#82aaff")
      t.set("function.method", "#82aaff")
      t.set("function.method.call", "#82aaff")
      t.set("ibl.indent.char.1", "#0e293f")
      t.set("ibl.scope.char.1", "#c792ea")
      t.set("ibl.whitespace.char.1", "#0e293f")
      t.set("include", "#ff5874")
      t.set("include.rust", "#c792ea")
      t.set("keyword", "#c792ea")
      t.set("keyword.conditional", "#c792ea")
      t.set("keyword.directive", "#ff5874")
      t.set("keyword.directive.define", "#ff5874")
      t.set("keyword.exception", "#c792ea")
      t.set("keyword.gitcommit", "#82aaff")
      t.set("keyword.import", "#ff5874")
      t.set("keyword.import.bash", "#c792ea")
      t.set("keyword.import.rust", "#c792ea")
      t.set("keyword.operator", "#c792ea")
      t.set("keyword.repeat", "#c792ea")
      t.set("keyword.storage", "#c792ea")
      t.set("keyword.storage.rust", "#c792ea")
      t.set("label", "#7fdbca")
      t.set("markup", "#ff5874")
      t.set("markup.environment", "#c792ea")
      t.set("markup.environment.name", "#21c7a8")
      t.set("markup.heading", "#c792ea")
      t.set("markup.heading.1.markdown", "#21c7a8")
      t.set("markup.heading.1.vimdoc", "#82aaff")
      t.set("markup.heading.2.markdown", "#b0b2f4")
      t.set("markup.heading.2.vimdoc", "#82aaff")
      t.set("markup.heading.3.markdown", "#7fdbca")
      t.set("markup.heading.4.markdown", "#f78c6c")
      t.set("markup.heading.5.markdown", "#87bcff")
      t.set("markup.heading.6.markdown", "#c792ea")
      t.set("markup.heading.help", "#87bcff")
      t.set("markup.heading.markdown", "#87bcff")
      t.set_extended("markup.italic", color: "#e39aa6", italic: true)
      t.set("markup.link", "#a1cd5e")
      t.set("markup.link.gitcommit", "#82aaff")
      t.set("markup.link.label", "#a1cd5e")
      t.set_extended("markup.link.url", color: "#ae81ff", underline: true)
      t.set_extended("markup.link.url.astro", color: "#c792ea", italic: true)
      t.set("markup.link.url.gitcommit", "#21c7a8")
      t.set_extended("markup.link.url.html", color: "#c792ea", italic: true)
      t.set_extended("markup.link.url.svelte", color: "#c792ea", italic: true)
      t.set_extended("markup.link.url.vue", color: "#c792ea", italic: true)
      t.set("markup.list", "#ff5874")
      t.set("markup.list.checked", "#7fdbca")
      t.set("markup.list.latex", "#ae81ff")
      t.set("markup.list.unchecked", "#82aaff")
      t.set("markup.math", "#87bcff")
      t.set("markup.quote", "#7c8f8f")
      t.set("markup.raw", "#ecc48d")
      t.set("markup.raw.vimdoc", "#e39aa6")
      t.set("markup.strong", "#e39aa6")
      t.set("method", "#82aaff")
      t.set("module", "#7fdbca")
      t.set("module.builtin", "#a1cd5e")
      t.set("namespace", "#7fdbca")
      t.set("namespace.builtin", "#a1cd5e")
      t.set("namespace.latex", "#b0b2f4")
      t.set("number", "#f78c6c")
      t.set("number.float", "#f78c6c")
      t.set("operator", "#ff5874")
      t.set("parameter", "#e39aa6")
      t.set("parameter.bash", "#7fdbca")
      t.set("parameter.builtin", "#e39aa6")
      t.set("preproc", "#ff5874")
      t.set("property", "#b0b2f4")
      t.set("punctuation", "#c3ccdc")
      t.set("punctuation.delimiter.astro", "#ff5874")
      t.set("punctuation.delimiter.css", "#ff5874")
      t.set("punctuation.delimiter.rust", "#ff5874")
      t.set("punctuation.delimiter.scss", "#ff5874")
      t.set("punctuation.delimiter.yaml", "#ff5874")
      t.set("punctuation.special", "#ff5874")
      t.set("repeat", "#c792ea")
      t.set("storageclass", "#c792ea")
      t.set("storageclass.rust", "#c792ea")
      t.set("string", "#ecc48d")
      t.set("string.documentation", "#7fdbca")
      t.set("string.escape", "#ff5874")
      t.set("string.json", "#85dc85")
      t.set("string.regex", "#7fdbca")
      t.set("string.regexp", "#7fdbca")
      t.set("string.special", "#ff5874")
      t.set("string.special.path", "#e39aa6")
      t.set("string.special.symbol", "#ae81ff")
      t.set("string.special.url", "#ae81ff")
      t.set("symbol", "#ae81ff")
      t.set("tag", "#82aaff")
      t.set("tag.attribute", "#7fdbca")
      t.set("tag.builtin", "#82aaff")
      t.set("tag.delimiter", "#a1cd5e")
      t.set("tag.javascript", "#21c7a8")
      t.set("tag.jsx", "#21c7a8")
      t.set("tag.tsx", "#21c7a8")
      t.set("tag.typescript", "#21c7a8")
      t.set("text.danger", "#fc514e")
      t.set("text.diff.delete", "#4b6479")
      t.set_extended("text.emphasis", color: "#e39aa6", italic: true)
      t.set("text.environment", "#c792ea")
      t.set("text.environment.name", "#21c7a8")
      t.set("text.literal", "#ecc48d")
      t.set("text.literal.vimdoc", "#e39aa6")
      t.set("text.math", "#87bcff")
      t.set("text.note", "#7c8f8f")
      t.set("text.reference", "#a1cd5e")
      t.set("text.reference.gitcommit", "#82aaff")
      t.set("text.reference.markdown_inline", "#a1cd5e")
      t.set("text.strong", "#e39aa6")
      t.set("text.title", "#c792ea")
      t.set("text.title.1.markdown", "#21c7a8")
      t.set("text.title.1.marker.markdown", "#ff5874")
      t.set("text.title.1.vimdoc", "#82aaff")
      t.set("text.title.2.markdown", "#b0b2f4")
      t.set("text.title.2.marker.markdown", "#ff5874")
      t.set("text.title.2.vimdoc", "#82aaff")
      t.set("text.title.3.markdown", "#7fdbca")
      t.set("text.title.3.marker.markdown", "#ff5874")
      t.set("text.title.4.markdown", "#f78c6c")
      t.set("text.title.4.marker.markdown", "#ff5874")
      t.set("text.title.5.markdown", "#87bcff")
      t.set("text.title.5.marker.markdown", "#ff5874")
      t.set("text.title.6.markdown", "#c792ea")
      t.set("text.title.6.marker.markdown", "#ff5874")
      t.set("text.title.help", "#87bcff")
      t.set("text.title.markdown", "#87bcff")
      t.set("text.todo", "#e3d18a")
      t.set_extended("text.uri", color: "#ae81ff", underline: true)
      t.set_extended("text.uri.astro", color: "#c792ea", italic: true)
      t.set("text.uri.gitcommit", "#21c7a8")
      t.set_extended("text.uri.html", color: "#c792ea", italic: true)
      t.set_extended("text.uri.svelte", color: "#c792ea", italic: true)
      t.set_extended("text.uri.vue", color: "#c792ea", italic: true)
      t.set("text.warning", "#e3d18a")
      t.set("type", "#21c7a8")
      t.set("type.builtin", "#21c7a8")
      t.set("type.qualifier", "#c792ea")
      t.set("variable", "#c3ccdc")
      t.set("variable.builtin", "#a1cd5e")
      t.set("variable.builtin.vim", "#21c7a8")
      t.set("variable.member", "#b0b2f4")
      t.set("variable.member.ruby", "#7fdbca")
      t.set("variable.member.yaml", "#82aaff")
      t.set("variable.parameter", "#e39aa6")
      t.set("variable.parameter.bash", "#7fdbca")
      t.set("variable.parameter.builtin", "#ff5874")
      t.set("variable.scss", "#7fdbca")
      t.set("variable.vim", "#7fdbca")
      t.resolve
    end
  end
end
