module TreeSitterManager
  module Themes
    def nord_nord : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#d8dee9", bg: "#2e3440")
      t.set("attribute", "#b48ead")
      t.set("attribute.builtin", "#d8dee9")
      t.set_extended("boolean", color: "#81a1c1", bold: true)
      t.set_extended("character", color: "#a3be8c", italic: true)
      t.set("character.special", "#ebcb8b")
      t.set_extended("comment", color: "#616e88", italic: true)
      t.set("comment.error", "#bf616a")
      t.set("comment.note", "#5e81ac")
      t.set_extended("comment.todo", color: "#ebcb8b", italic: true, bold: true)
      t.set("comment.warning", "#b48ead")
      t.set_extended("conditional", color: "#81a1c1", italic: true)
      t.set("constant", "#ebcb8b")
      t.set_extended("constant.builtin", color: "#8fbcbb", bold: true)
      t.set_extended("constant.macro", color: "#8fbcbb", bold: true)
      t.set("constructor", "#81a1c1")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#bf616a")
      t.set("exception", "#b48ead")
      t.set_extended("field", color: "#d8dee9", italic: true)
      t.set("float", "#b48ead")
      t.set_extended("function", color: "#88c0d0", italic: true)
      t.set_extended("function.builtin", color: "#88c0d0", italic: true)
      t.set("funtion.macro", "#8fbcbb")
      t.set("ibl.indent.char.1", "#3b4252")
      t.set("ibl.scope.char.1", "#616e88")
      t.set("ibl.whitespace.char.1", "#3b4252")
      t.set("include", "#81a1c1")
      t.set_extended("keyword", color: "#81a1c1", italic: true)
      t.set_extended("keyword.function", color: "#88c0d0", italic: true)
      t.set_extended("keyword.operator", color: "#88c0d0", italic: true)
      t.set_extended("keyword.return", color: "#88c0d0", italic: true)
      t.set("label", "#b48ead")
      t.set("markup", "#d8dee9")
      t.set_extended("markup.heading", color: "#a3be8c", bold: true)
      t.set_extended("markup.link", color: "#a3be8c", underline: true)
      t.set_extended("method", color: "#88c0d0", italic: true)
      t.set("module", "#81a1c1")
      t.set("module.builtin", "#d8dee9")
      t.set_extended("namespace", color: "#d8dee9", italic: true)
      t.set("number", "#b48ead")
      t.set("number.float", "#b48ead")
      t.set("operator", "#81a1c1")
      t.set("parameter", "#5e81ac")
      t.set_extended("property", color: "#5e81ac", italic: true)
      t.set("punctuation", "#eceff4")
      t.set("punctuation.bracket", "#88c0d0")
      t.set("punctuation.delimiter", "#88c0d0")
      t.set("punctuation.special", "#88c0d0")
      t.set_extended("repeat", color: "#81a1c1", italic: true)
      t.set_extended("string", color: "#a3be8c", italic: true)
      t.set_extended("string.escape", color: "#b48ead", italic: true)
      t.set_extended("string.regex", color: "#8fbcbb", italic: true)
      t.set("string.regexp", "#ebcb8b")
      t.set("string.special", "#ebcb8b")
      t.set_extended("string.special.url", color: "#a3be8c", underline: true)
      t.set("symbol", "#b48ead")
      t.set("tag", "#d8dee9")
      t.set("tag.builtin", "#d8dee9")
      t.set("tag.delimiter", "#b48ead")
      t.set("text", "#d8dee9")
      t.set_extended("text.emphasis", color: "#5e81ac", italic: true)
      t.set("text.literal", "#d8dee9")
      t.set("text.math", "#8fbcbb")
      t.set_extended("text.reference", color: "#b48ead", bold: true)
      t.set_extended("text.strike", color: "#d8dee9", strikethrough: true)
      t.set_extended("text.strong", color: "#5e81ac", bold: true)
      t.set_extended("text.title", color: "#5e81ac", bold: true)
      t.set_extended("text.underline", color: "#d8dee9", underline: true)
      t.set_extended("text.uri", color: "#a3be8c", underline: true)
      t.set("type", "#81a1c1")
      t.set("type.builtin", "#81a1c1")
      t.set_extended("variable", color: "#d8dee9", bold: true)
      t.set_extended("variable.builtin", color: "#d8dee9", bold: true)
      t.set_extended("variable.global", color: "#d8dee9", bold: true)
      t.set("variable.parameter.builtin", "#d8dee9")
      t.resolve
    end
  end
end
