module TreeSitterManager
  module Themes
    def oceanicnext_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#d8dee9", bg: "#1b2b34")
      t.set("attribute", "#ec5f67")
      t.set("attribute.builtin", "#62b3b2")
      t.set("boolean", "#f99157")
      t.set("character", "#ec5f67")
      t.set("character.special", "#ab7967")
      t.set("comment", "#65737e")
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#fac863")
      t.set("comment.warning", "#fce094")
      t.set("conditional", "#c594c5")
      t.set("constant", "#f99157")
      t.set("constant.builtin", "#62b3b2")
      t.set("constructor", "#d8dee9")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("exception", "#ec5f67")
      t.set("function", "#6699cc")
      t.set("function.builtin", "#62b3b2")
      t.set("ibl.indent.char.1", "#65737e")
      t.set("ibl.scope.char.1", "#65737e")
      t.set("ibl.whitespace.char.1", "#65737e")
      t.set("include", "#c594c5")
      t.set("keyword", "#c594c5")
      t.set("keyword.operator", "#c594c5")
      t.set("label", "#62b3b2")
      t.set("markup", "#62b3b2")
      t.set_extended("markup.heading", color: "#6699cc", bold: true)
      t.set_extended("markup.link", color: "#ec5f67", underline: true)
      t.set("method", "#6699cc")
      t.set("module", "#c594c5")
      t.set("module.builtin", "#62b3b2")
      t.set("namespace", "#d8dee9")
      t.set("number", "#f99157")
      t.set("number.float", "#f99157")
      t.set("operator", "#f99157")
      t.set("parameter", "#fac863")
      t.set("property", "#d8dee9")
      t.set("punctuation", "#ab7967")
      t.set("punctuation.bracket", "#62b3b2")
      t.set("punctuation.delimiter", "#62b3b2")
      t.set("punctuation.special", "#62b3b2")
      t.set("string", "#99c794")
      t.set("string.escape", "#ab7967")
      t.set("string.regexp", "#ab7967")
      t.set("string.special", "#ab7967")
      t.set_extended("string.special.url", color: "#ec5f67", underline: true)
      t.set("symbol", "#99c794")
      t.set("tag", "#d8dee9")
      t.set("tag.builtin", "#62b3b2")
      t.set("tag.delimiter", "#62b3b2")
      t.set("type", "#fac863")
      t.set("type.builtin", "#62b3b2")
      t.set("variable", "#cdd3de")
      t.set("variable.builtin", "#ec5f67")
      t.set("variable.parameter.builtin", "#62b3b2")
      t.resolve
    end

    def oceanicnext_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#1b2b34", bg: "#1b2b34")
      t.set("attribute", "#d0545b")
      t.set("attribute.builtin", "#569e9d")
      t.set("boolean", "#db804d")
      t.set("character", "#d0545b")
      t.set("character.special", "#966a5b")
      t.set("comment", "#a7adba")
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#dcb057")
      t.set("comment.warning", "#fce094")
      t.set("conditional", "#ad82ad")
      t.set("constant", "#db804d")
      t.set("constant.builtin", "#569e9d")
      t.set("constructor", "#1b2b34")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("exception", "#d0545b")
      t.set("function", "#5a87b4")
      t.set("function.builtin", "#569e9d")
      t.set("ibl.indent.char.1", "#a7adba")
      t.set("ibl.scope.char.1", "#a7adba")
      t.set("ibl.whitespace.char.1", "#a7adba")
      t.set("include", "#ad82ad")
      t.set("keyword", "#ad82ad")
      t.set("keyword.operator", "#ad82ad")
      t.set("label", "#569e9d")
      t.set("markup", "#569e9d")
      t.set_extended("markup.heading", color: "#5a87b4", bold: true)
      t.set_extended("markup.link", color: "#d0545b", underline: true)
      t.set("method", "#5a87b4")
      t.set("module", "#ad82ad")
      t.set("module.builtin", "#569e9d")
      t.set("namespace", "#1b2b34")
      t.set("number", "#db804d")
      t.set("number.float", "#db804d")
      t.set("operator", "#db804d")
      t.set("parameter", "#dcb057")
      t.set("property", "#1b2b34")
      t.set("punctuation", "#966a5b")
      t.set("punctuation.bracket", "#569e9d")
      t.set("punctuation.delimiter", "#569e9d")
      t.set("punctuation.special", "#569e9d")
      t.set("string", "#87af82")
      t.set("string.escape", "#966a5b")
      t.set("string.regexp", "#966a5b")
      t.set("string.special", "#966a5b")
      t.set_extended("string.special.url", color: "#d0545b", underline: true)
      t.set("symbol", "#87af82")
      t.set("tag", "#1b2b34")
      t.set("tag.builtin", "#569e9d")
      t.set("tag.delimiter", "#569e9d")
      t.set("type", "#dcb057")
      t.set("type.builtin", "#569e9d")
      t.set("variable", "#343d46")
      t.set("variable.builtin", "#d0545b")
      t.set("variable.parameter.builtin", "#569e9d")
      t.resolve
    end
  end
end
