module TreeSitterManager
  module Themes
    def one_cool : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#a5b0c5", bg: "#242b38")
      t.set("annotation", "#a5b0c5")
      t.set("attribute", "#4dbdcb")
      t.set("attribute.builtin", "#ef5f6b")
      t.set("attribute.typescript", "#5ab0f6")
      t.set("boolean", "#d99a5e")
      t.set("character", "#d99a5e")
      t.set("character.special", "#ef5f6b")
      t.set_extended("comment", color: "#546178", italic: true)
      t.set("comment.error", "#ef5f6b")
      t.set("comment.note", "#4dbdcb")
      t.set_extended("comment.todo", color: "#ef5f6b", italic: true)
      t.set_extended("comment.todo.checked", color: "#97ca72", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#ef5f6b", italic: true)
      t.set("comment.warning", "#ebc275")
      t.set("conditional", "#ca72e4")
      t.set("constant", "#d99a5e")
      t.set("constant.builtin", "#d99a5e")
      t.set("constant.macro", "#d99a5e")
      t.set_extended("constructor", color: "#ebc275", bold: true)
      t.set("danger", "#a5b0c5")
      t.set("diff.add", "#97ca72")
      t.set("diff.delete", "#ef5f6b")
      t.set("diff.delta", "#5ab0f6")
      t.set("diff.minus", "#ef5f6b")
      t.set("diff.plus", "#97ca72")
      t.set("error", "#a5b0c5")
      t.set("exception", "#ca72e4")
      t.set("field", "#4dbdcb")
      t.set("float", "#d99a5e")
      t.set("function", "#5ab0f6")
      t.set("function.builtin", "#4dbdcb")
      t.set("function.macro", "#4dbdcb")
      t.set("function.method", "#5ab0f6")
      t.set("ibl.indent.char.1", "#2d3343")
      t.set("ibl.scope.char.1", "#546178")
      t.set("ibl.whitespace.char.1", "#546178")
      t.set("include", "#ca72e4")
      t.set("keyword", "#ca72e4")
      t.set("keyword.conditional", "#ca72e4")
      t.set("keyword.directive", "#ca72e4")
      t.set("keyword.exception", "#ca72e4")
      t.set("keyword.function", "#ca72e4")
      t.set("keyword.import", "#ca72e4")
      t.set("keyword.operator", "#ca72e4")
      t.set("keyword.repeat", "#ca72e4")
      t.set("label", "#ef5f6b")
      t.set("markup", "#ef5f6b")
      t.set_extended("markup.emphasis", color: "#a5b0c5", italic: true)
      t.set("markup.environment", "#a5b0c5")
      t.set("markup.environment.name", "#a5b0c5")
      t.set_extended("markup.heading", color: "#d99a5e", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#ef5f6b", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#ef5f6b", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#ca72e4", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#ca72e4", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#d99a5e", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#d99a5e", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#ef5f6b", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#ef5f6b", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#ca72e4", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#ca72e4", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#d99a5e", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#d99a5e", bold: true)
      t.set("markup.link", "#5ab0f6")
      t.set_extended("markup.link.url", color: "#4dbdcb", underline: true)
      t.set("markup.list", "#ef5f6b")
      t.set("markup.math", "#a5b0c5")
      t.set("markup.raw", "#97ca72")
      t.set_extended("markup.strike", color: "#a5b0c5", strikethrough: true)
      t.set_extended("markup.strong", color: "#a5b0c5", bold: true)
      t.set_extended("markup.underline", color: "#a5b0c5", underline: true)
      t.set("method", "#5ab0f6")
      t.set("module", "#ebc275")
      t.set("module.builtin", "#ef5f6b")
      t.set("namespace", "#ebc275")
      t.set("none", "#a5b0c5")
      t.set("note", "#a5b0c5")
      t.set("number", "#d99a5e")
      t.set("number.float", "#d99a5e")
      t.set("operator", "#a5b0c5")
      t.set("parameter", "#ef5f6b")
      t.set("parameter.reference", "#a5b0c5")
      t.set("preproc", "#ca72e4")
      t.set("property", "#4dbdcb")
      t.set("punctuation", "#7d899f")
      t.set("punctuation.bracket", "#7d899f")
      t.set("punctuation.delimiter", "#7d899f")
      t.set("punctuation.special", "#ef5f6b")
      t.set("repeat", "#ca72e4")
      t.set("storageclass.lifetime", "#ef5f6b")
      t.set("string", "#97ca72")
      t.set("string.escape", "#ef5f6b")
      t.set("string.regex", "#d99a5e")
      t.set("string.regexp", "#d99a5e")
      t.set("string.special", "#ef5f6b")
      t.set("string.special.symbol", "#4dbdcb")
      t.set("tag", "#ca72e4")
      t.set("tag.attribute", "#ebc275")
      t.set("tag.builtin", "#ef5f6b")
      t.set("tag.delimiter", "#ca72e4")
      t.set("text", "#a5b0c5")
      t.set("text.diff.add", "#97ca72")
      t.set("text.diff.delete", "#ef5f6b")
      t.set_extended("text.emphasis", color: "#a5b0c5", italic: true)
      t.set("text.environment", "#a5b0c5")
      t.set("text.environment.name", "#a5b0c5")
      t.set("text.literal", "#97ca72")
      t.set("text.math", "#a5b0c5")
      t.set("text.reference", "#5ab0f6")
      t.set_extended("text.strike", color: "#a5b0c5", strikethrough: true)
      t.set_extended("text.strong", color: "#a5b0c5", bold: true)
      t.set_extended("text.title", color: "#d99a5e", bold: true)
      t.set_extended("text.todo", color: "#d99a5e", bold: true)
      t.set_extended("text.todo.checked", color: "#97ca72", italic: true)
      t.set_extended("text.todo.unchecked", color: "#ef5f6b", italic: true)
      t.set_extended("text.underline", color: "#a5b0c5", underline: true)
      t.set_extended("text.uri", color: "#4dbdcb", underline: true)
      t.set("type", "#ebc275")
      t.set("type.builtin", "#d99a5e")
      t.set("type.qualifier", "#ca72e4")
      t.set("variable", "#a5b0c5")
      t.set("variable.builtin", "#ef5f6b")
      t.set("variable.member", "#4dbdcb")
      t.set("variable.parameter", "#ef5f6b")
      t.set("variable.parameter.builtin", "#ef5f6b")
      t.set("warning", "#a5b0c5")
      t.resolve
    end

    def one_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#abb2bf", bg: "#242b38")
      t.set("annotation", "#abb2bf")
      t.set("attribute", "#56b6c2")
      t.set("attribute.builtin", "#e86671")
      t.set("attribute.typescript", "#61afef")
      t.set("boolean", "#d19a66")
      t.set("character", "#d19a66")
      t.set("character.special", "#e86671")
      t.set_extended("comment", color: "#5c6370", italic: true)
      t.set("comment.error", "#e86671")
      t.set("comment.note", "#56b6c2")
      t.set_extended("comment.todo", color: "#e86671", italic: true)
      t.set_extended("comment.todo.checked", color: "#98c379", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#e86671", italic: true)
      t.set("comment.warning", "#e5c07b")
      t.set("conditional", "#c678dd")
      t.set("constant", "#d19a66")
      t.set("constant.builtin", "#d19a66")
      t.set("constant.macro", "#d19a66")
      t.set_extended("constructor", color: "#e5c07b", bold: true)
      t.set("danger", "#abb2bf")
      t.set("diff.add", "#98c379")
      t.set("diff.delete", "#e86671")
      t.set("diff.delta", "#61afef")
      t.set("diff.minus", "#e86671")
      t.set("diff.plus", "#98c379")
      t.set("error", "#abb2bf")
      t.set("exception", "#c678dd")
      t.set("field", "#56b6c2")
      t.set("float", "#d19a66")
      t.set("function", "#61afef")
      t.set("function.builtin", "#56b6c2")
      t.set("function.macro", "#56b6c2")
      t.set("function.method", "#61afef")
      t.set("ibl.indent.char.1", "#31353f")
      t.set("ibl.scope.char.1", "#5c6370")
      t.set("ibl.whitespace.char.1", "#5c6370")
      t.set("include", "#c678dd")
      t.set("keyword", "#c678dd")
      t.set("keyword.conditional", "#c678dd")
      t.set("keyword.directive", "#c678dd")
      t.set("keyword.exception", "#c678dd")
      t.set("keyword.function", "#c678dd")
      t.set("keyword.import", "#c678dd")
      t.set("keyword.operator", "#c678dd")
      t.set("keyword.repeat", "#c678dd")
      t.set("label", "#e86671")
      t.set("markup", "#e86671")
      t.set_extended("markup.emphasis", color: "#abb2bf", italic: true)
      t.set("markup.environment", "#abb2bf")
      t.set("markup.environment.name", "#abb2bf")
      t.set_extended("markup.heading", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#e86671", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#c678dd", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#d19a66", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#d19a66", bold: true)
      t.set("markup.link", "#61afef")
      t.set_extended("markup.link.url", color: "#56b6c2", underline: true)
      t.set("markup.list", "#e86671")
      t.set("markup.math", "#abb2bf")
      t.set("markup.raw", "#98c379")
      t.set_extended("markup.strike", color: "#abb2bf", strikethrough: true)
      t.set_extended("markup.strong", color: "#abb2bf", bold: true)
      t.set_extended("markup.underline", color: "#abb2bf", underline: true)
      t.set("method", "#61afef")
      t.set("module", "#e5c07b")
      t.set("module.builtin", "#e86671")
      t.set("namespace", "#e5c07b")
      t.set("none", "#abb2bf")
      t.set("note", "#abb2bf")
      t.set("number", "#d19a66")
      t.set("number.float", "#d19a66")
      t.set("operator", "#abb2bf")
      t.set("parameter", "#e86671")
      t.set("parameter.reference", "#abb2bf")
      t.set("preproc", "#c678dd")
      t.set("property", "#56b6c2")
      t.set("punctuation", "#848b98")
      t.set("punctuation.bracket", "#848b98")
      t.set("punctuation.delimiter", "#848b98")
      t.set("punctuation.special", "#e86671")
      t.set("repeat", "#c678dd")
      t.set("storageclass.lifetime", "#e86671")
      t.set("string", "#98c379")
      t.set("string.escape", "#e86671")
      t.set("string.regex", "#d19a66")
      t.set("string.regexp", "#d19a66")
      t.set("string.special", "#e86671")
      t.set("string.special.symbol", "#56b6c2")
      t.set("tag", "#c678dd")
      t.set("tag.attribute", "#e5c07b")
      t.set("tag.builtin", "#e86671")
      t.set("tag.delimiter", "#c678dd")
      t.set("text", "#abb2bf")
      t.set("text.diff.add", "#98c379")
      t.set("text.diff.delete", "#e86671")
      t.set_extended("text.emphasis", color: "#abb2bf", italic: true)
      t.set("text.environment", "#abb2bf")
      t.set("text.environment.name", "#abb2bf")
      t.set("text.literal", "#98c379")
      t.set("text.math", "#abb2bf")
      t.set("text.reference", "#61afef")
      t.set_extended("text.strike", color: "#abb2bf", strikethrough: true)
      t.set_extended("text.strong", color: "#abb2bf", bold: true)
      t.set_extended("text.title", color: "#d19a66", bold: true)
      t.set_extended("text.todo", color: "#d19a66", bold: true)
      t.set_extended("text.todo.checked", color: "#98c379", italic: true)
      t.set_extended("text.todo.unchecked", color: "#e86671", italic: true)
      t.set_extended("text.underline", color: "#abb2bf", underline: true)
      t.set_extended("text.uri", color: "#56b6c2", underline: true)
      t.set("type", "#e5c07b")
      t.set("type.builtin", "#d19a66")
      t.set("type.qualifier", "#c678dd")
      t.set("variable", "#abb2bf")
      t.set("variable.builtin", "#e86671")
      t.set("variable.member", "#56b6c2")
      t.set("variable.parameter", "#e86671")
      t.set("variable.parameter.builtin", "#e86671")
      t.set("warning", "#abb2bf")
      t.resolve
    end

    def one_darker : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#a0a8b7", bg: "#282c34")
      t.set("annotation", "#a0a8b7")
      t.set("attribute", "#48b0bd")
      t.set("attribute.builtin", "#e55561")
      t.set("attribute.typescript", "#4fa6ed")
      t.set("boolean", "#cc9057")
      t.set("character", "#cc9057")
      t.set("character.special", "#e55561")
      t.set_extended("comment", color: "#535965", italic: true)
      t.set("comment.error", "#e55561")
      t.set("comment.note", "#48b0bd")
      t.set_extended("comment.todo", color: "#e55561", italic: true)
      t.set_extended("comment.todo.checked", color: "#8ebd6b", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#e55561", italic: true)
      t.set("comment.warning", "#e2b86b")
      t.set("conditional", "#bf68d9")
      t.set("constant", "#cc9057")
      t.set("constant.builtin", "#cc9057")
      t.set("constant.macro", "#cc9057")
      t.set_extended("constructor", color: "#e2b86b", bold: true)
      t.set("danger", "#a0a8b7")
      t.set("diff.add", "#8ebd6b")
      t.set("diff.delete", "#e55561")
      t.set("diff.delta", "#4fa6ed")
      t.set("diff.minus", "#e55561")
      t.set("diff.plus", "#8ebd6b")
      t.set("error", "#a0a8b7")
      t.set("exception", "#bf68d9")
      t.set("field", "#48b0bd")
      t.set("float", "#cc9057")
      t.set("function", "#4fa6ed")
      t.set("function.builtin", "#48b0bd")
      t.set("function.macro", "#48b0bd")
      t.set("function.method", "#4fa6ed")
      t.set("ibl.indent.char.1", "#282c34")
      t.set("ibl.scope.char.1", "#535965")
      t.set("ibl.whitespace.char.1", "#535965")
      t.set("include", "#bf68d9")
      t.set("keyword", "#bf68d9")
      t.set("keyword.conditional", "#bf68d9")
      t.set("keyword.directive", "#bf68d9")
      t.set("keyword.exception", "#bf68d9")
      t.set("keyword.function", "#bf68d9")
      t.set("keyword.import", "#bf68d9")
      t.set("keyword.operator", "#bf68d9")
      t.set("keyword.repeat", "#bf68d9")
      t.set("label", "#e55561")
      t.set("markup", "#e55561")
      t.set_extended("markup.emphasis", color: "#a0a8b7", italic: true)
      t.set("markup.environment", "#a0a8b7")
      t.set("markup.environment.name", "#a0a8b7")
      t.set_extended("markup.heading", color: "#cc9057", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#e55561", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#e55561", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#bf68d9", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#bf68d9", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#cc9057", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#cc9057", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#e55561", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#e55561", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#bf68d9", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#bf68d9", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#cc9057", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#cc9057", bold: true)
      t.set("markup.link", "#4fa6ed")
      t.set_extended("markup.link.url", color: "#48b0bd", underline: true)
      t.set("markup.list", "#e55561")
      t.set("markup.math", "#a0a8b7")
      t.set("markup.raw", "#8ebd6b")
      t.set_extended("markup.strike", color: "#a0a8b7", strikethrough: true)
      t.set_extended("markup.strong", color: "#a0a8b7", bold: true)
      t.set_extended("markup.underline", color: "#a0a8b7", underline: true)
      t.set("method", "#4fa6ed")
      t.set("module", "#e2b86b")
      t.set("module.builtin", "#e55561")
      t.set("namespace", "#e2b86b")
      t.set("none", "#a0a8b7")
      t.set("note", "#a0a8b7")
      t.set("number", "#cc9057")
      t.set("number.float", "#cc9057")
      t.set("operator", "#a0a8b7")
      t.set("parameter", "#e55561")
      t.set("parameter.reference", "#a0a8b7")
      t.set("preproc", "#bf68d9")
      t.set("property", "#48b0bd")
      t.set("punctuation", "#7a818e")
      t.set("punctuation.bracket", "#7a818e")
      t.set("punctuation.delimiter", "#7a818e")
      t.set("punctuation.special", "#e55561")
      t.set("repeat", "#bf68d9")
      t.set("storageclass.lifetime", "#e55561")
      t.set("string", "#8ebd6b")
      t.set("string.escape", "#e55561")
      t.set("string.regex", "#cc9057")
      t.set("string.regexp", "#cc9057")
      t.set("string.special", "#e55561")
      t.set("string.special.symbol", "#48b0bd")
      t.set("tag", "#bf68d9")
      t.set("tag.attribute", "#e2b86b")
      t.set("tag.builtin", "#e55561")
      t.set("tag.delimiter", "#bf68d9")
      t.set("text", "#a0a8b7")
      t.set("text.diff.add", "#8ebd6b")
      t.set("text.diff.delete", "#e55561")
      t.set_extended("text.emphasis", color: "#a0a8b7", italic: true)
      t.set("text.environment", "#a0a8b7")
      t.set("text.environment.name", "#a0a8b7")
      t.set("text.literal", "#8ebd6b")
      t.set("text.math", "#a0a8b7")
      t.set("text.reference", "#4fa6ed")
      t.set_extended("text.strike", color: "#a0a8b7", strikethrough: true)
      t.set_extended("text.strong", color: "#a0a8b7", bold: true)
      t.set_extended("text.title", color: "#cc9057", bold: true)
      t.set_extended("text.todo", color: "#cc9057", bold: true)
      t.set_extended("text.todo.checked", color: "#8ebd6b", italic: true)
      t.set_extended("text.todo.unchecked", color: "#e55561", italic: true)
      t.set_extended("text.underline", color: "#a0a8b7", underline: true)
      t.set_extended("text.uri", color: "#48b0bd", underline: true)
      t.set("type", "#e2b86b")
      t.set("type.builtin", "#cc9057")
      t.set("type.qualifier", "#bf68d9")
      t.set("variable", "#a0a8b7")
      t.set("variable.builtin", "#e55561")
      t.set("variable.member", "#48b0bd")
      t.set("variable.parameter", "#e55561")
      t.set("variable.parameter.builtin", "#e55561")
      t.set("warning", "#a0a8b7")
      t.resolve
    end

    def one_deep : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#93a4c3", bg: "#1f2329")
      t.set("annotation", "#93a4c3")
      t.set("attribute", "#34bfd0")
      t.set("attribute.builtin", "#f65866")
      t.set("attribute.typescript", "#41a7fc")
      t.set("boolean", "#dd9046")
      t.set("character", "#dd9046")
      t.set("character.special", "#f65866")
      t.set_extended("comment", color: "#455574", italic: true)
      t.set("comment.error", "#f65866")
      t.set("comment.note", "#34bfd0")
      t.set_extended("comment.todo", color: "#f65866", italic: true)
      t.set_extended("comment.todo.checked", color: "#8bcd5b", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#f65866", italic: true)
      t.set("comment.warning", "#efbd5d")
      t.set("conditional", "#c75ae8")
      t.set("constant", "#dd9046")
      t.set("constant.builtin", "#dd9046")
      t.set("constant.macro", "#dd9046")
      t.set_extended("constructor", color: "#efbd5d", bold: true)
      t.set("danger", "#93a4c3")
      t.set("diff.add", "#8bcd5b")
      t.set("diff.delete", "#f65866")
      t.set("diff.delta", "#41a7fc")
      t.set("diff.minus", "#f65866")
      t.set("diff.plus", "#8bcd5b")
      t.set("error", "#93a4c3")
      t.set("exception", "#c75ae8")
      t.set("field", "#34bfd0")
      t.set("float", "#dd9046")
      t.set("function", "#41a7fc")
      t.set("function.builtin", "#34bfd0")
      t.set("function.macro", "#34bfd0")
      t.set("function.method", "#41a7fc")
      t.set("ibl.indent.char.1", "#21283b")
      t.set("ibl.scope.char.1", "#455574")
      t.set("ibl.whitespace.char.1", "#455574")
      t.set("include", "#c75ae8")
      t.set("keyword", "#c75ae8")
      t.set("keyword.conditional", "#c75ae8")
      t.set("keyword.directive", "#c75ae8")
      t.set("keyword.exception", "#c75ae8")
      t.set("keyword.function", "#c75ae8")
      t.set("keyword.import", "#c75ae8")
      t.set("keyword.operator", "#c75ae8")
      t.set("keyword.repeat", "#c75ae8")
      t.set("label", "#f65866")
      t.set("markup", "#f65866")
      t.set_extended("markup.emphasis", color: "#93a4c3", italic: true)
      t.set("markup.environment", "#93a4c3")
      t.set("markup.environment.name", "#93a4c3")
      t.set_extended("markup.heading", color: "#dd9046", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#f65866", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#f65866", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#c75ae8", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#c75ae8", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#dd9046", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#dd9046", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#f65866", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#f65866", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#c75ae8", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#c75ae8", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#dd9046", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#dd9046", bold: true)
      t.set("markup.link", "#41a7fc")
      t.set_extended("markup.link.url", color: "#34bfd0", underline: true)
      t.set("markup.list", "#f65866")
      t.set("markup.math", "#93a4c3")
      t.set("markup.raw", "#8bcd5b")
      t.set_extended("markup.strike", color: "#93a4c3", strikethrough: true)
      t.set_extended("markup.strong", color: "#93a4c3", bold: true)
      t.set_extended("markup.underline", color: "#93a4c3", underline: true)
      t.set("method", "#41a7fc")
      t.set("module", "#efbd5d")
      t.set("module.builtin", "#f65866")
      t.set("namespace", "#efbd5d")
      t.set("none", "#93a4c3")
      t.set("note", "#93a4c3")
      t.set("number", "#dd9046")
      t.set("number.float", "#dd9046")
      t.set("operator", "#93a4c3")
      t.set("parameter", "#f65866")
      t.set("parameter.reference", "#93a4c3")
      t.set("preproc", "#c75ae8")
      t.set("property", "#34bfd0")
      t.set("punctuation", "#6c7d9c")
      t.set("punctuation.bracket", "#6c7d9c")
      t.set("punctuation.delimiter", "#6c7d9c")
      t.set("punctuation.special", "#f65866")
      t.set("repeat", "#c75ae8")
      t.set("storageclass.lifetime", "#f65866")
      t.set("string", "#8bcd5b")
      t.set("string.escape", "#f65866")
      t.set("string.regex", "#dd9046")
      t.set("string.regexp", "#dd9046")
      t.set("string.special", "#f65866")
      t.set("string.special.symbol", "#34bfd0")
      t.set("tag", "#c75ae8")
      t.set("tag.attribute", "#efbd5d")
      t.set("tag.builtin", "#f65866")
      t.set("tag.delimiter", "#c75ae8")
      t.set("text", "#93a4c3")
      t.set("text.diff.add", "#8bcd5b")
      t.set("text.diff.delete", "#f65866")
      t.set_extended("text.emphasis", color: "#93a4c3", italic: true)
      t.set("text.environment", "#93a4c3")
      t.set("text.environment.name", "#93a4c3")
      t.set("text.literal", "#8bcd5b")
      t.set("text.math", "#93a4c3")
      t.set("text.reference", "#41a7fc")
      t.set_extended("text.strike", color: "#93a4c3", strikethrough: true)
      t.set_extended("text.strong", color: "#93a4c3", bold: true)
      t.set_extended("text.title", color: "#dd9046", bold: true)
      t.set_extended("text.todo", color: "#dd9046", bold: true)
      t.set_extended("text.todo.checked", color: "#8bcd5b", italic: true)
      t.set_extended("text.todo.unchecked", color: "#f65866", italic: true)
      t.set_extended("text.underline", color: "#93a4c3", underline: true)
      t.set_extended("text.uri", color: "#34bfd0", underline: true)
      t.set("type", "#efbd5d")
      t.set("type.builtin", "#dd9046")
      t.set("type.qualifier", "#c75ae8")
      t.set("variable", "#93a4c3")
      t.set("variable.builtin", "#f65866")
      t.set("variable.member", "#34bfd0")
      t.set("variable.parameter", "#f65866")
      t.set("variable.parameter.builtin", "#f65866")
      t.set("warning", "#93a4c3")
      t.resolve
    end

    def one_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#383a42", bg: "#1a212e")
      t.set("annotation", "#383a42")
      t.set("attribute", "#0184bc")
      t.set("attribute.builtin", "#e45649")
      t.set("attribute.typescript", "#4078f2")
      t.set("boolean", "#c18401")
      t.set("character", "#c18401")
      t.set("character.special", "#e45649")
      t.set_extended("comment", color: "#a0a1a7", italic: true)
      t.set("comment.error", "#e45649")
      t.set("comment.note", "#0184bc")
      t.set_extended("comment.todo", color: "#e45649", italic: true)
      t.set_extended("comment.todo.checked", color: "#50a14f", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#e45649", italic: true)
      t.set("comment.warning", "#986801")
      t.set("conditional", "#a626a4")
      t.set("constant", "#c18401")
      t.set("constant.builtin", "#c18401")
      t.set("constant.macro", "#c18401")
      t.set_extended("constructor", color: "#986801", bold: true)
      t.set("danger", "#383a42")
      t.set("diff.add", "#50a14f")
      t.set("diff.delete", "#e45649")
      t.set("diff.delta", "#4078f2")
      t.set("diff.minus", "#e45649")
      t.set("diff.plus", "#50a14f")
      t.set("error", "#383a42")
      t.set("exception", "#a626a4")
      t.set("field", "#0184bc")
      t.set("float", "#c18401")
      t.set("function", "#4078f2")
      t.set("function.builtin", "#0184bc")
      t.set("function.macro", "#0184bc")
      t.set("function.method", "#4078f2")
      t.set("ibl.indent.char.1", "#f0f0f0")
      t.set("ibl.scope.char.1", "#a0a1a7")
      t.set("ibl.whitespace.char.1", "#a0a1a7")
      t.set("include", "#a626a4")
      t.set("keyword", "#a626a4")
      t.set("keyword.conditional", "#a626a4")
      t.set("keyword.directive", "#a626a4")
      t.set("keyword.exception", "#a626a4")
      t.set("keyword.function", "#a626a4")
      t.set("keyword.import", "#a626a4")
      t.set("keyword.operator", "#a626a4")
      t.set("keyword.repeat", "#a626a4")
      t.set("label", "#e45649")
      t.set("markup", "#e45649")
      t.set_extended("markup.emphasis", color: "#383a42", italic: true)
      t.set("markup.environment", "#383a42")
      t.set("markup.environment.name", "#383a42")
      t.set_extended("markup.heading", color: "#c18401", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#e45649", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#e45649", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#a626a4", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#a626a4", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#c18401", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#c18401", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#e45649", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#e45649", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#a626a4", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#a626a4", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#c18401", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#c18401", bold: true)
      t.set("markup.link", "#4078f2")
      t.set_extended("markup.link.url", color: "#0184bc", underline: true)
      t.set("markup.list", "#e45649")
      t.set("markup.math", "#383a42")
      t.set("markup.raw", "#50a14f")
      t.set_extended("markup.strike", color: "#383a42", strikethrough: true)
      t.set_extended("markup.strong", color: "#383a42", bold: true)
      t.set_extended("markup.underline", color: "#383a42", underline: true)
      t.set("method", "#4078f2")
      t.set("module", "#986801")
      t.set("module.builtin", "#e45649")
      t.set("namespace", "#986801")
      t.set("none", "#383a42")
      t.set("note", "#383a42")
      t.set("number", "#c18401")
      t.set("number.float", "#c18401")
      t.set("operator", "#383a42")
      t.set("parameter", "#e45649")
      t.set("parameter.reference", "#383a42")
      t.set("preproc", "#a626a4")
      t.set("property", "#0184bc")
      t.set("punctuation", "#818387")
      t.set("punctuation.bracket", "#818387")
      t.set("punctuation.delimiter", "#818387")
      t.set("punctuation.special", "#e45649")
      t.set("repeat", "#a626a4")
      t.set("storageclass.lifetime", "#e45649")
      t.set("string", "#50a14f")
      t.set("string.escape", "#e45649")
      t.set("string.regex", "#c18401")
      t.set("string.regexp", "#c18401")
      t.set("string.special", "#e45649")
      t.set("string.special.symbol", "#0184bc")
      t.set("tag", "#a626a4")
      t.set("tag.attribute", "#986801")
      t.set("tag.builtin", "#e45649")
      t.set("tag.delimiter", "#a626a4")
      t.set("text", "#383a42")
      t.set("text.diff.add", "#50a14f")
      t.set("text.diff.delete", "#e45649")
      t.set_extended("text.emphasis", color: "#383a42", italic: true)
      t.set("text.environment", "#383a42")
      t.set("text.environment.name", "#383a42")
      t.set("text.literal", "#50a14f")
      t.set("text.math", "#383a42")
      t.set("text.reference", "#4078f2")
      t.set_extended("text.strike", color: "#383a42", strikethrough: true)
      t.set_extended("text.strong", color: "#383a42", bold: true)
      t.set_extended("text.title", color: "#c18401", bold: true)
      t.set_extended("text.todo", color: "#c18401", bold: true)
      t.set_extended("text.todo.checked", color: "#50a14f", italic: true)
      t.set_extended("text.todo.unchecked", color: "#e45649", italic: true)
      t.set_extended("text.underline", color: "#383a42", underline: true)
      t.set_extended("text.uri", color: "#0184bc", underline: true)
      t.set("type", "#986801")
      t.set("type.builtin", "#c18401")
      t.set("type.qualifier", "#a626a4")
      t.set("variable", "#383a42")
      t.set("variable.builtin", "#e45649")
      t.set("variable.member", "#0184bc")
      t.set("variable.parameter", "#e45649")
      t.set("variable.parameter.builtin", "#e45649")
      t.set("warning", "#383a42")
      t.resolve
    end

    def one_warm : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#b1b4b9", bg: "#fafafa")
      t.set("annotation", "#b1b4b9")
      t.set("attribute", "#5fafb9")
      t.set("attribute.builtin", "#e16d77")
      t.set("attribute.typescript", "#68aee8")
      t.set("boolean", "#c99a6e")
      t.set("character", "#c99a6e")
      t.set("character.special", "#e16d77")
      t.set_extended("comment", color: "#646568", italic: true)
      t.set("comment.error", "#e16d77")
      t.set("comment.note", "#5fafb9")
      t.set_extended("comment.todo", color: "#e16d77", italic: true)
      t.set_extended("comment.todo.checked", color: "#99bc80", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#e16d77", italic: true)
      t.set("comment.warning", "#dfbe81")
      t.set("conditional", "#c27fd7")
      t.set("constant", "#c99a6e")
      t.set("constant.builtin", "#c99a6e")
      t.set("constant.macro", "#c99a6e")
      t.set_extended("constructor", color: "#dfbe81", bold: true)
      t.set("danger", "#b1b4b9")
      t.set("diff.add", "#99bc80")
      t.set("diff.delete", "#e16d77")
      t.set("diff.delta", "#68aee8")
      t.set("diff.minus", "#e16d77")
      t.set("diff.plus", "#99bc80")
      t.set("error", "#b1b4b9")
      t.set("exception", "#c27fd7")
      t.set("field", "#5fafb9")
      t.set("float", "#c99a6e")
      t.set("function", "#68aee8")
      t.set("function.builtin", "#5fafb9")
      t.set("function.macro", "#5fafb9")
      t.set("function.method", "#68aee8")
      t.set("ibl.indent.char.1", "#35373b")
      t.set("ibl.scope.char.1", "#646568")
      t.set("ibl.whitespace.char.1", "#646568")
      t.set("include", "#c27fd7")
      t.set("keyword", "#c27fd7")
      t.set("keyword.conditional", "#c27fd7")
      t.set("keyword.directive", "#c27fd7")
      t.set("keyword.exception", "#c27fd7")
      t.set("keyword.function", "#c27fd7")
      t.set("keyword.import", "#c27fd7")
      t.set("keyword.operator", "#c27fd7")
      t.set("keyword.repeat", "#c27fd7")
      t.set("label", "#e16d77")
      t.set("markup", "#e16d77")
      t.set_extended("markup.emphasis", color: "#b1b4b9", italic: true)
      t.set("markup.environment", "#b1b4b9")
      t.set("markup.environment.name", "#b1b4b9")
      t.set_extended("markup.heading", color: "#c99a6e", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#e16d77", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#e16d77", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#c27fd7", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#c27fd7", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#c99a6e", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#c99a6e", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#e16d77", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#e16d77", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#c27fd7", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#c27fd7", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#c99a6e", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#c99a6e", bold: true)
      t.set("markup.link", "#68aee8")
      t.set_extended("markup.link.url", color: "#5fafb9", underline: true)
      t.set("markup.list", "#e16d77")
      t.set("markup.math", "#b1b4b9")
      t.set("markup.raw", "#99bc80")
      t.set_extended("markup.strike", color: "#b1b4b9", strikethrough: true)
      t.set_extended("markup.strong", color: "#b1b4b9", bold: true)
      t.set_extended("markup.underline", color: "#b1b4b9", underline: true)
      t.set("method", "#68aee8")
      t.set("module", "#dfbe81")
      t.set("module.builtin", "#e16d77")
      t.set("namespace", "#dfbe81")
      t.set("none", "#b1b4b9")
      t.set("note", "#b1b4b9")
      t.set("number", "#c99a6e")
      t.set("number.float", "#c99a6e")
      t.set("operator", "#b1b4b9")
      t.set("parameter", "#e16d77")
      t.set("parameter.reference", "#b1b4b9")
      t.set("preproc", "#c27fd7")
      t.set("property", "#5fafb9")
      t.set("punctuation", "#8b8d91")
      t.set("punctuation.bracket", "#8b8d91")
      t.set("punctuation.delimiter", "#8b8d91")
      t.set("punctuation.special", "#e16d77")
      t.set("repeat", "#c27fd7")
      t.set("storageclass.lifetime", "#e16d77")
      t.set("string", "#99bc80")
      t.set("string.escape", "#e16d77")
      t.set("string.regex", "#c99a6e")
      t.set("string.regexp", "#c99a6e")
      t.set("string.special", "#e16d77")
      t.set("string.special.symbol", "#5fafb9")
      t.set("tag", "#c27fd7")
      t.set("tag.attribute", "#dfbe81")
      t.set("tag.builtin", "#e16d77")
      t.set("tag.delimiter", "#c27fd7")
      t.set("text", "#b1b4b9")
      t.set("text.diff.add", "#99bc80")
      t.set("text.diff.delete", "#e16d77")
      t.set_extended("text.emphasis", color: "#b1b4b9", italic: true)
      t.set("text.environment", "#b1b4b9")
      t.set("text.environment.name", "#b1b4b9")
      t.set("text.literal", "#99bc80")
      t.set("text.math", "#b1b4b9")
      t.set("text.reference", "#68aee8")
      t.set_extended("text.strike", color: "#b1b4b9", strikethrough: true)
      t.set_extended("text.strong", color: "#b1b4b9", bold: true)
      t.set_extended("text.title", color: "#c99a6e", bold: true)
      t.set_extended("text.todo", color: "#c99a6e", bold: true)
      t.set_extended("text.todo.checked", color: "#99bc80", italic: true)
      t.set_extended("text.todo.unchecked", color: "#e16d77", italic: true)
      t.set_extended("text.underline", color: "#b1b4b9", underline: true)
      t.set_extended("text.uri", color: "#5fafb9", underline: true)
      t.set("type", "#dfbe81")
      t.set("type.builtin", "#c99a6e")
      t.set("type.qualifier", "#c27fd7")
      t.set("variable", "#b1b4b9")
      t.set("variable.builtin", "#e16d77")
      t.set("variable.member", "#5fafb9")
      t.set("variable.parameter", "#e16d77")
      t.set("variable.parameter.builtin", "#e16d77")
      t.set("warning", "#b1b4b9")
      t.resolve
    end

    def one_warmer : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#a7aab0", bg: "#2c2d30")
      t.set("annotation", "#a7aab0")
      t.set("attribute", "#51a8b3")
      t.set("attribute.builtin", "#de5d68")
      t.set("attribute.typescript", "#57a5e5")
      t.set("boolean", "#c49060")
      t.set("character", "#c49060")
      t.set("character.special", "#de5d68")
      t.set_extended("comment", color: "#5a5b5e", italic: true)
      t.set("comment.error", "#de5d68")
      t.set("comment.note", "#51a8b3")
      t.set_extended("comment.todo", color: "#de5d68", italic: true)
      t.set_extended("comment.todo.checked", color: "#8fb573", italic: true)
      t.set_extended("comment.todo.unchecked", color: "#de5d68", italic: true)
      t.set("comment.warning", "#dbb671")
      t.set("conditional", "#bb70d2")
      t.set("constant", "#c49060")
      t.set("constant.builtin", "#c49060")
      t.set("constant.macro", "#c49060")
      t.set_extended("constructor", color: "#dbb671", bold: true)
      t.set("danger", "#a7aab0")
      t.set("diff.add", "#8fb573")
      t.set("diff.delete", "#de5d68")
      t.set("diff.delta", "#57a5e5")
      t.set("diff.minus", "#de5d68")
      t.set("diff.plus", "#8fb573")
      t.set("error", "#a7aab0")
      t.set("exception", "#bb70d2")
      t.set("field", "#51a8b3")
      t.set("float", "#c49060")
      t.set("function", "#57a5e5")
      t.set("function.builtin", "#51a8b3")
      t.set("function.macro", "#51a8b3")
      t.set("function.method", "#57a5e5")
      t.set("ibl.indent.char.1", "#2c2d31")
      t.set("ibl.scope.char.1", "#5a5b5e")
      t.set("ibl.whitespace.char.1", "#5a5b5e")
      t.set("include", "#bb70d2")
      t.set("keyword", "#bb70d2")
      t.set("keyword.conditional", "#bb70d2")
      t.set("keyword.directive", "#bb70d2")
      t.set("keyword.exception", "#bb70d2")
      t.set("keyword.function", "#bb70d2")
      t.set("keyword.import", "#bb70d2")
      t.set("keyword.operator", "#bb70d2")
      t.set("keyword.repeat", "#bb70d2")
      t.set("label", "#de5d68")
      t.set("markup", "#de5d68")
      t.set_extended("markup.emphasis", color: "#a7aab0", italic: true)
      t.set("markup.environment", "#a7aab0")
      t.set("markup.environment.name", "#a7aab0")
      t.set_extended("markup.heading", color: "#c49060", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#de5d68", bold: true)
      t.set_extended("markup.heading.1.marker.markdown", color: "#de5d68", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#bb70d2", bold: true)
      t.set_extended("markup.heading.2.marker.markdown", color: "#bb70d2", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#c49060", bold: true)
      t.set_extended("markup.heading.3.marker.markdown", color: "#c49060", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#de5d68", bold: true)
      t.set_extended("markup.heading.4.marker.markdown", color: "#de5d68", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#bb70d2", bold: true)
      t.set_extended("markup.heading.5.marker.markdown", color: "#bb70d2", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#c49060", bold: true)
      t.set_extended("markup.heading.6.marker.markdown", color: "#c49060", bold: true)
      t.set("markup.link", "#57a5e5")
      t.set_extended("markup.link.url", color: "#51a8b3", underline: true)
      t.set("markup.list", "#de5d68")
      t.set("markup.math", "#a7aab0")
      t.set("markup.raw", "#8fb573")
      t.set_extended("markup.strike", color: "#a7aab0", strikethrough: true)
      t.set_extended("markup.strong", color: "#a7aab0", bold: true)
      t.set_extended("markup.underline", color: "#a7aab0", underline: true)
      t.set("method", "#57a5e5")
      t.set("module", "#dbb671")
      t.set("module.builtin", "#de5d68")
      t.set("namespace", "#dbb671")
      t.set("none", "#a7aab0")
      t.set("note", "#a7aab0")
      t.set("number", "#c49060")
      t.set("number.float", "#c49060")
      t.set("operator", "#a7aab0")
      t.set("parameter", "#de5d68")
      t.set("parameter.reference", "#a7aab0")
      t.set("preproc", "#bb70d2")
      t.set("property", "#51a8b3")
      t.set("punctuation", "#818387")
      t.set("punctuation.bracket", "#818387")
      t.set("punctuation.delimiter", "#818387")
      t.set("punctuation.special", "#de5d68")
      t.set("repeat", "#bb70d2")
      t.set("storageclass.lifetime", "#de5d68")
      t.set("string", "#8fb573")
      t.set("string.escape", "#de5d68")
      t.set("string.regex", "#c49060")
      t.set("string.regexp", "#c49060")
      t.set("string.special", "#de5d68")
      t.set("string.special.symbol", "#51a8b3")
      t.set("tag", "#bb70d2")
      t.set("tag.attribute", "#dbb671")
      t.set("tag.builtin", "#de5d68")
      t.set("tag.delimiter", "#bb70d2")
      t.set("text", "#a7aab0")
      t.set("text.diff.add", "#8fb573")
      t.set("text.diff.delete", "#de5d68")
      t.set_extended("text.emphasis", color: "#a7aab0", italic: true)
      t.set("text.environment", "#a7aab0")
      t.set("text.environment.name", "#a7aab0")
      t.set("text.literal", "#8fb573")
      t.set("text.math", "#a7aab0")
      t.set("text.reference", "#57a5e5")
      t.set_extended("text.strike", color: "#a7aab0", strikethrough: true)
      t.set_extended("text.strong", color: "#a7aab0", bold: true)
      t.set_extended("text.title", color: "#c49060", bold: true)
      t.set_extended("text.todo", color: "#c49060", bold: true)
      t.set_extended("text.todo.checked", color: "#8fb573", italic: true)
      t.set_extended("text.todo.unchecked", color: "#de5d68", italic: true)
      t.set_extended("text.underline", color: "#a7aab0", underline: true)
      t.set_extended("text.uri", color: "#51a8b3", underline: true)
      t.set("type", "#dbb671")
      t.set("type.builtin", "#c49060")
      t.set("type.qualifier", "#bb70d2")
      t.set("variable", "#a7aab0")
      t.set("variable.builtin", "#de5d68")
      t.set("variable.member", "#51a8b3")
      t.set("variable.parameter", "#de5d68")
      t.set("variable.parameter.builtin", "#de5d68")
      t.set("warning", "#a7aab0")
      t.resolve
    end
  end
end
