module TreeSitterManager
  module Themes
    def oxocarbon_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#d0d0d0", bg: "#161616")
      t.set("attribute", "#82cfff")
      t.set("attribute.builtin", "#d0d0d0")
      t.set("boolean", "#78a9ff")
      t.set("character", "#be95ff")
      t.set("character.special", "#d0d0d0")
      t.set_extended("comment", color: "#525252", italic: true)
      t.set("comment.error", "#ee5396")
      t.set("comment.note", "#78a9ff")
      t.set("comment.todo", "#42be65")
      t.set("comment.warning", "#be95ff")
      t.set("conditional", "#78a9ff")
      t.set("constant", "#be95ff")
      t.set("constant.builtin", "#08bdba")
      t.set("constant.macro", "#08bdba")
      t.set("constructor", "#78a9ff")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("error", "#33b1ff")
      t.set("exception", "#82cfff")
      t.set("field", "#d0d0d0")
      t.set("float", "#82cfff")
      t.set_extended("function", color: "#ff7eb6", bold: true)
      t.set("function.builtin", "#ff7eb6")
      t.set("function.macro", "#08bdba")
      t.set("ibl.indent.char.1", "#393939")
      t.set("ibl.scope.char.1", "#525252")
      t.set("ibl.whitespace.char.1", "#393939")
      t.set("include", "#78a9ff")
      t.set("keyword", "#78a9ff")
      t.set("keyword.function", "#3ddbd9")
      t.set("keyword.operator", "#3ddbd9")
      t.set("label", "#82cfff")
      t.set("markup", "#d0d0d0")
      t.set("markup.heading", "#d0d0d0")
      t.set("method", "#08bdba")
      t.set("module", "#78a9ff")
      t.set("module.builtin", "#d0d0d0")
      t.set("namespace", "#08bdba")
      t.set("number", "#82cfff")
      t.set("number.date", "#3ddbd9")
      t.set("number.date.effective", "#42be65")
      t.set("number.float", "#82cfff")
      t.set("number.interval", "#78a9ff")
      t.set("number.quantity", "#33b1ff")
      t.set("number.quantity.negative", "#ee5396")
      t.set("number.status", "#ff7eb6")
      t.set("operator", "#78a9ff")
      t.set("parameter", "#d0d0d0")
      t.set("property", "#ee5396")
      t.set("punctuation", "#e0e2ea")
      t.set("punctuation.bracket", "#3ddbd9")
      t.set("punctuation.delimiter", "#3ddbd9")
      t.set("punctuation.special", "#3ddbd9")
      t.set("reference", "#d0d0d0")
      t.set("repeat", "#78a9ff")
      t.set("string", "#be95ff")
      t.set("string.escape", "#82cfff")
      t.set("string.regex", "#08bdba")
      t.set("string.regexp", "#d0d0d0")
      t.set("string.special", "#d0d0d0")
      t.set_extended("symbol", color: "#82cfff", bold: true)
      t.set("tag", "#78a9ff")
      t.set("tag.attribute", "#82cfff")
      t.set("tag.builtin", "#d0d0d0")
      t.set("tag.delimiter", "#82cfff")
      t.set("text", "#d0d0d0")
      t.set_extended("text.emphasis", color: "#ee5396", bold: true)
      t.set("text.literal", "#d0d0d0")
      t.set("text.literal.commodity", "#42be65")
      t.set_extended("text.strike", color: "#ee5396", strikethrough: true)
      t.set("text.title", "#ee5396")
      t.set_extended("text.underline", color: "#ee5396", underline: true)
      t.set_extended("text.uri", color: "#be95ff", underline: true)
      t.set("type", "#78a9ff")
      t.set("type.builtin", "#78a9ff")
      t.set("variable", "#d0d0d0")
      t.set("variable.builtin", "#d0d0d0")
      t.set("variable.parameter.builtin", "#d0d0d0")
      t.resolve
    end

    def oxocarbon_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#37474f", bg: "#161616")
      t.set("attribute", "#ffab91")
      t.set("attribute.builtin", "#37474f")
      t.set("boolean", "#ee5396")
      t.set("character", "#be95ff")
      t.set("character.special", "#37474f")
      t.set_extended("comment", color: "#161616", italic: true)
      t.set("comment.error", "#ff6f00")
      t.set("comment.note", "#ee5396")
      t.set("comment.todo", "#42be65")
      t.set("comment.warning", "#be95ff")
      t.set("conditional", "#ee5396")
      t.set("constant", "#be95ff")
      t.set("constant.builtin", "#08bdba")
      t.set("constant.macro", "#08bdba")
      t.set("constructor", "#ee5396")
      t.set("diff.delta", "#007373")
      t.set("diff.minus", "#590008")
      t.set("diff.plus", "#005523")
      t.set("error", "#0f62fe")
      t.set("exception", "#ffab91")
      t.set("field", "#37474f")
      t.set("float", "#ffab91")
      t.set_extended("function", color: "#673ab7", bold: true)
      t.set("function.builtin", "#673ab7")
      t.set("function.macro", "#08bdba")
      t.set("ibl.indent.char.1", "#d0d0d0")
      t.set("ibl.scope.char.1", "#161616")
      t.set("ibl.whitespace.char.1", "#d0d0d0")
      t.set("include", "#ee5396")
      t.set("keyword", "#ee5396")
      t.set("keyword.function", "#ff7eb6")
      t.set("keyword.operator", "#ff7eb6")
      t.set("label", "#ffab91")
      t.set("markup", "#37474f")
      t.set("markup.heading", "#37474f")
      t.set("method", "#08bdba")
      t.set("module", "#ee5396")
      t.set("module.builtin", "#37474f")
      t.set("namespace", "#08bdba")
      t.set("number", "#ffab91")
      t.set("number.date", "#ff7eb6")
      t.set("number.date.effective", "#42be65")
      t.set("number.float", "#ffab91")
      t.set("number.interval", "#ee5396")
      t.set("number.quantity", "#0f62fe")
      t.set("number.quantity.negative", "#ff6f00")
      t.set("number.status", "#673ab7")
      t.set("operator", "#ee5396")
      t.set("parameter", "#37474f")
      t.set("property", "#ff6f00")
      t.set("punctuation", "#14161b")
      t.set("punctuation.bracket", "#ff7eb6")
      t.set("punctuation.delimiter", "#ff7eb6")
      t.set("punctuation.special", "#ff7eb6")
      t.set("reference", "#37474f")
      t.set("repeat", "#ee5396")
      t.set("string", "#be95ff")
      t.set("string.escape", "#ffab91")
      t.set("string.regex", "#08bdba")
      t.set("string.regexp", "#37474f")
      t.set("string.special", "#37474f")
      t.set_extended("symbol", color: "#ffab91", bold: true)
      t.set("tag", "#ee5396")
      t.set("tag.attribute", "#ffab91")
      t.set("tag.builtin", "#37474f")
      t.set("tag.delimiter", "#ffab91")
      t.set("text", "#37474f")
      t.set_extended("text.emphasis", color: "#ff6f00", bold: true)
      t.set("text.literal", "#37474f")
      t.set("text.literal.commodity", "#42be65")
      t.set_extended("text.strike", color: "#ff6f00", strikethrough: true)
      t.set("text.title", "#ff6f00")
      t.set_extended("text.underline", color: "#ff6f00", underline: true)
      t.set_extended("text.uri", color: "#be95ff", underline: true)
      t.set("type", "#ee5396")
      t.set("type.builtin", "#ee5396")
      t.set("variable", "#37474f")
      t.set("variable.builtin", "#37474f")
      t.set("variable.parameter.builtin", "#37474f")
      t.resolve
    end
  end
end
