module TreeSitterManager
  module Themes
    def solarized_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#839496", bg: "#002b36")
      t.set("attribute", "#cb4b16")
      t.set("attribute.builtin", "#dc322f")
      t.set("boolean", "#2aa198")
      t.set("character", "#2aa198")
      t.set("character.special", "#dc322f")
      t.set("comment", "#586e75")
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set_extended("comment.todo", color: "#d33682", bold: true)
      t.set("comment.warning", "#fce094")
      t.set("constant", "#2aa198")
      t.set("constant.builtin", "#dc322f")
      t.set("constructor", "#dc322f")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#8cf8f7")
      t.set("function.builtin", "#dc322f")
      t.set_extended("ibl.indent.char.1", color: "#657b83", bold: true)
      t.set("ibl.scope.char.1", "#586e75")
      t.set_extended("ibl.whitespace.char.1", color: "#657b83", bold: true)
      t.set("keyword", "#719e07")
      t.set("label", "#719e07")
      t.set("markup", "#dc322f")
      t.set_extended("markup.heading", color: "#cb4b16", bold: true)
      t.set("markup.link", "#6c71c4")
      t.set("module", "#b58900")
      t.set("module.builtin", "#dc322f")
      t.set("number", "#2aa198")
      t.set("number.float", "#2aa198")
      t.set("operator", "#e0e2ea")
      t.set("property", "#268bd2")
      t.set("punctuation", "#e0e2ea")
      t.set("punctuation.special", "#dc322f")
      t.set("string", "#b3f6c0")
      t.set("string.escape", "#dc322f")
      t.set("string.regexp", "#dc322f")
      t.set("string.special", "#dc322f")
      t.set("string.special.url", "#6c71c4")
      t.set("tag", "#dc322f")
      t.set("tag.builtin", "#dc322f")
      t.set("type", "#b58900")
      t.set("type.builtin", "#dc322f")
      t.set("variable", "#e0e2ea")
      t.set("variable.builtin", "#dc322f")
      t.set("variable.parameter.builtin", "#dc322f")
      t.resolve
    end

    def solarized_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#657b83", bg: "#002b36")
      t.set("attribute", "#cb4b16")
      t.set("attribute.builtin", "#dc322f")
      t.set("boolean", "#2aa198")
      t.set("character", "#2aa198")
      t.set("character.special", "#dc322f")
      t.set("comment", "#93a1a1")
      t.set("comment.error", "#590008")
      t.set("comment.note", "#007373")
      t.set_extended("comment.todo", color: "#d33682", bold: true)
      t.set("comment.warning", "#6b5300")
      t.set("constant", "#2aa198")
      t.set("constant.builtin", "#dc322f")
      t.set("constructor", "#dc322f")
      t.set("diff.delta", "#007373")
      t.set("diff.minus", "#590008")
      t.set("diff.plus", "#005523")
      t.set("function", "#007373")
      t.set("function.builtin", "#dc322f")
      t.set_extended("ibl.indent.char.1", color: "#839496", bold: true)
      t.set("ibl.scope.char.1", "#93a1a1")
      t.set_extended("ibl.whitespace.char.1", color: "#839496", bold: true)
      t.set("keyword", "#719e07")
      t.set("label", "#719e07")
      t.set("markup", "#dc322f")
      t.set_extended("markup.heading", color: "#cb4b16", bold: true)
      t.set("markup.link", "#6c71c4")
      t.set("module", "#b58900")
      t.set("module.builtin", "#dc322f")
      t.set("number", "#2aa198")
      t.set("number.float", "#2aa198")
      t.set("operator", "#14161b")
      t.set("property", "#268bd2")
      t.set("punctuation", "#14161b")
      t.set("punctuation.special", "#dc322f")
      t.set("string", "#005523")
      t.set("string.escape", "#dc322f")
      t.set("string.regexp", "#dc322f")
      t.set("string.special", "#dc322f")
      t.set("string.special.url", "#6c71c4")
      t.set("tag", "#dc322f")
      t.set("tag.builtin", "#dc322f")
      t.set("type", "#b58900")
      t.set("type.builtin", "#dc322f")
      t.set("variable", "#14161b")
      t.set("variable.builtin", "#dc322f")
      t.set("variable.parameter.builtin", "#dc322f")
      t.resolve
    end
  end
end
