module TreeSitterManager
  module Themes
    def tokyo_storm : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c0caf5", bg: "#24283b")
      t.set("annotation", "#7dcfff")
      t.set("attribute", "#7dcfff")
      t.set("attribute.builtin", "#2ac3de")
      t.set("boolean", "#ff9e64")
      t.set("character", "#9ece6a")
      t.set("character.printf", "#2ac3de")
      t.set("character.special", "#2ac3de")
      t.set_extended("comment", color: "#565f89", italic: true)
      t.set("comment.error", "#db4b4b")
      t.set("comment.hint", "#1abc9c")
      t.set("comment.info", "#0db9d7")
      t.set("comment.note", "#1abc9c")
      t.set("comment.todo", "#7aa2f7")
      t.set("comment.warning", "#e0af68")
      t.set("constant", "#ff9e64")
      t.set("constant.builtin", "#2ac3de")
      t.set("constant.macro", "#7dcfff")
      t.set("constructor", "#bb9af7")
      t.set("constructor.tsx", "#2ac3de")
      t.set("function", "#7aa2f7")
      t.set("function.builtin", "#2ac3de")
      t.set("function.call", "#7aa2f7")
      t.set("function.macro", "#7dcfff")
      t.set("function.method", "#7aa2f7")
      t.set("function.method.call", "#7aa2f7")
      t.set("ibl.indent.char.1", "#3b4261")
      t.set("ibl.scope.char.1", "#2ac3de")
      t.set("ibl.whitespace.char.1", "#3b4261")
      t.set_extended("keyword", color: "#9d7cd8", italic: true)
      t.set("keyword.conditional", "#bb9af7")
      t.set_extended("keyword.coroutine", color: "#9d7cd8", italic: true)
      t.set("keyword.debug", "#ff9e64")
      t.set("keyword.directive", "#7dcfff")
      t.set("keyword.directive.define", "#7dcfff")
      t.set("keyword.exception", "#bb9af7")
      t.set("keyword.function", "#bb9af7")
      t.set("keyword.import", "#7dcfff")
      t.set("keyword.operator", "#89ddff")
      t.set("keyword.repeat", "#bb9af7")
      t.set_extended("keyword.return", color: "#9d7cd8", italic: true)
      t.set("keyword.storage", "#2ac3de")
      t.set("label", "#7aa2f7")
      t.set("markup.environment", "#7dcfff")
      t.set("markup.environment.name", "#2ac3de")
      t.set_extended("markup.heading", color: "#7aa2f7", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#7aa2f7", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#e0af68", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#9ece6a", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#1abc9c", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#bb9af7", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#9d7cd8", bold: true)
      t.set_extended("markup.heading.7.markdown", color: "#ff9e64", bold: true)
      t.set_extended("markup.heading.8.markdown", color: "#f7768e", bold: true)
      t.set("markup.link", "#1abc9c")
      t.set("markup.link.label", "#2ac3de")
      t.set("markup.link.label.symbol", "#bb9af7")
      t.set("markup.list", "#89ddff")
      t.set("markup.list.checked", "#73daca")
      t.set_extended("markup.list.markdown", color: "#ff9e64", bold: true)
      t.set("markup.list.unchecked", "#7aa2f7")
      t.set("markup.math", "#2ac3de")
      t.set("markup.raw", "#9ece6a")
      t.set("markup.raw.markdown_inline", "#7aa2f7")
      t.set("module", "#7dcfff")
      t.set("module.builtin", "#f7768e")
      t.set("namespace.builtin", "#f7768e")
      t.set("number", "#ff9e64")
      t.set("number.float", "#ff9e64")
      t.set("operator", "#89ddff")
      t.set("property", "#73daca")
      t.set("punctuation", "#2ac3de")
      t.set("punctuation.bracket", "#a9b1d6")
      t.set("punctuation.delimiter", "#89ddff")
      t.set("punctuation.special", "#89ddff")
      t.set("punctuation.special.markdown", "#ff9e64")
      t.set("string", "#9ece6a")
      t.set("string.documentation", "#e0af68")
      t.set("string.escape", "#bb9af7")
      t.set("string.regexp", "#b4f9f8")
      t.set("string.special", "#2ac3de")
      t.set("tag", "#bb9af7")
      t.set("tag.attribute", "#73daca")
      t.set("tag.builtin", "#2ac3de")
      t.set("tag.delimiter", "#2ac3de")
      t.set("tag.delimiter.tsx", "#607dbf")
      t.set("tag.javascript", "#f7768e")
      t.set("tag.tsx", "#f7768e")
      t.set("type", "#2ac3de")
      t.set("type.builtin", "#29a4bd")
      t.set("type.definition", "#2ac3de")
      t.set_extended("type.qualifier", color: "#9d7cd8", italic: true)
      t.set("variable", "#c0caf5")
      t.set("variable.builtin", "#f7768e")
      t.set("variable.member", "#73daca")
      t.set("variable.parameter", "#e0af68")
      t.set("variable.parameter.builtin", "#dab484")
      t.resolve
    end

    def tokyo_night : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c0caf5", bg: "#24283b")
      t.set("annotation", "#7dcfff")
      t.set("attribute", "#7dcfff")
      t.set("attribute.builtin", "#2ac3de")
      t.set("boolean", "#ff9e64")
      t.set("character", "#9ece6a")
      t.set("character.printf", "#2ac3de")
      t.set("character.special", "#2ac3de")
      t.set_extended("comment", color: "#565f89", italic: true)
      t.set("comment.error", "#db4b4b")
      t.set("comment.hint", "#1abc9c")
      t.set("comment.info", "#0db9d7")
      t.set("comment.note", "#1abc9c")
      t.set("comment.todo", "#7aa2f7")
      t.set("comment.warning", "#e0af68")
      t.set("constant", "#ff9e64")
      t.set("constant.builtin", "#2ac3de")
      t.set("constant.macro", "#7dcfff")
      t.set("constructor", "#bb9af7")
      t.set("constructor.tsx", "#2ac3de")
      t.set("function", "#7aa2f7")
      t.set("function.builtin", "#2ac3de")
      t.set("function.call", "#7aa2f7")
      t.set("function.macro", "#7dcfff")
      t.set("function.method", "#7aa2f7")
      t.set("function.method.call", "#7aa2f7")
      t.set("ibl.indent.char.1", "#3b4261")
      t.set("ibl.scope.char.1", "#2ac3de")
      t.set("ibl.whitespace.char.1", "#3b4261")
      t.set_extended("keyword", color: "#9d7cd8", italic: true)
      t.set("keyword.conditional", "#bb9af7")
      t.set_extended("keyword.coroutine", color: "#9d7cd8", italic: true)
      t.set("keyword.debug", "#ff9e64")
      t.set("keyword.directive", "#7dcfff")
      t.set("keyword.directive.define", "#7dcfff")
      t.set("keyword.exception", "#bb9af7")
      t.set("keyword.function", "#bb9af7")
      t.set("keyword.import", "#7dcfff")
      t.set("keyword.operator", "#89ddff")
      t.set("keyword.repeat", "#bb9af7")
      t.set_extended("keyword.return", color: "#9d7cd8", italic: true)
      t.set("keyword.storage", "#2ac3de")
      t.set("label", "#7aa2f7")
      t.set("markup.environment", "#7dcfff")
      t.set("markup.environment.name", "#2ac3de")
      t.set_extended("markup.heading", color: "#7aa2f7", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#7aa2f7", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#e0af68", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#9ece6a", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#1abc9c", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#bb9af7", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#9d7cd8", bold: true)
      t.set_extended("markup.heading.7.markdown", color: "#ff9e64", bold: true)
      t.set_extended("markup.heading.8.markdown", color: "#f7768e", bold: true)
      t.set("markup.link", "#1abc9c")
      t.set("markup.link.label", "#2ac3de")
      t.set("markup.link.label.symbol", "#bb9af7")
      t.set("markup.list", "#89ddff")
      t.set("markup.list.checked", "#73daca")
      t.set_extended("markup.list.markdown", color: "#ff9e64", bold: true)
      t.set("markup.list.unchecked", "#7aa2f7")
      t.set("markup.math", "#2ac3de")
      t.set("markup.raw", "#9ece6a")
      t.set("markup.raw.markdown_inline", "#7aa2f7")
      t.set("module", "#7dcfff")
      t.set("module.builtin", "#f7768e")
      t.set("namespace.builtin", "#f7768e")
      t.set("number", "#ff9e64")
      t.set("number.float", "#ff9e64")
      t.set("operator", "#89ddff")
      t.set("property", "#73daca")
      t.set("punctuation", "#2ac3de")
      t.set("punctuation.bracket", "#a9b1d6")
      t.set("punctuation.delimiter", "#89ddff")
      t.set("punctuation.special", "#89ddff")
      t.set("punctuation.special.markdown", "#ff9e64")
      t.set("string", "#9ece6a")
      t.set("string.documentation", "#e0af68")
      t.set("string.escape", "#bb9af7")
      t.set("string.regexp", "#b4f9f8")
      t.set("string.special", "#2ac3de")
      t.set("tag", "#bb9af7")
      t.set("tag.attribute", "#73daca")
      t.set("tag.builtin", "#2ac3de")
      t.set("tag.delimiter", "#2ac3de")
      t.set("tag.delimiter.tsx", "#5d7ab8")
      t.set("tag.javascript", "#f7768e")
      t.set("tag.tsx", "#f7768e")
      t.set("type", "#2ac3de")
      t.set("type.builtin", "#27a1b9")
      t.set("type.definition", "#2ac3de")
      t.set_extended("type.qualifier", color: "#9d7cd8", italic: true)
      t.set("variable", "#c0caf5")
      t.set("variable.builtin", "#f7768e")
      t.set("variable.member", "#73daca")
      t.set("variable.parameter", "#e0af68")
      t.set("variable.parameter.builtin", "#dab484")
      t.resolve
    end

    def tokyo_day : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#3760bf", bg: "#1a1b26")
      t.set("annotation", "#007197")
      t.set("attribute", "#007197")
      t.set("attribute.builtin", "#188092")
      t.set("boolean", "#b15c00")
      t.set("character", "#587539")
      t.set("character.printf", "#188092")
      t.set("character.special", "#188092")
      t.set_extended("comment", color: "#848cb5", italic: true)
      t.set("comment.error", "#c64343")
      t.set("comment.hint", "#118c74")
      t.set("comment.info", "#07879d")
      t.set("comment.note", "#118c74")
      t.set("comment.todo", "#2e7de9")
      t.set("comment.warning", "#8c6c3e")
      t.set("constant", "#b15c00")
      t.set("constant.builtin", "#188092")
      t.set("constant.macro", "#007197")
      t.set("constructor", "#9854f1")
      t.set("constructor.tsx", "#188092")
      t.set("function", "#2e7de9")
      t.set("function.builtin", "#188092")
      t.set("function.call", "#2e7de9")
      t.set("function.macro", "#007197")
      t.set("function.method", "#2e7de9")
      t.set("function.method.call", "#2e7de9")
      t.set("ibl.indent.char.1", "#a8aecb")
      t.set("ibl.scope.char.1", "#188092")
      t.set("ibl.whitespace.char.1", "#a8aecb")
      t.set_extended("keyword", color: "#7847bd", italic: true)
      t.set("keyword.conditional", "#9854f1")
      t.set_extended("keyword.coroutine", color: "#7847bd", italic: true)
      t.set("keyword.debug", "#b15c00")
      t.set("keyword.directive", "#007197")
      t.set("keyword.directive.define", "#007197")
      t.set("keyword.exception", "#9854f1")
      t.set("keyword.function", "#9854f1")
      t.set("keyword.import", "#007197")
      t.set("keyword.operator", "#006a83")
      t.set("keyword.repeat", "#9854f1")
      t.set_extended("keyword.return", color: "#7847bd", italic: true)
      t.set("keyword.storage", "#188092")
      t.set("label", "#2e7de9")
      t.set("markup.environment", "#007197")
      t.set("markup.environment.name", "#188092")
      t.set_extended("markup.heading", color: "#2e7de9", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#2e7de9", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#8c6c3e", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#587539", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#118c74", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#9854f1", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#7847bd", bold: true)
      t.set_extended("markup.heading.7.markdown", color: "#b15c00", bold: true)
      t.set_extended("markup.heading.8.markdown", color: "#f52a65", bold: true)
      t.set("markup.link", "#118c74")
      t.set("markup.link.label", "#188092")
      t.set("markup.link.label.symbol", "#9854f1")
      t.set("markup.list", "#006a83")
      t.set("markup.list.checked", "#387068")
      t.set_extended("markup.list.markdown", color: "#b15c00", bold: true)
      t.set("markup.list.unchecked", "#2e7de9")
      t.set("markup.math", "#188092")
      t.set("markup.raw", "#587539")
      t.set("markup.raw.markdown_inline", "#2e7de9")
      t.set("module", "#007197")
      t.set("module.builtin", "#f52a65")
      t.set("namespace.builtin", "#f52a65")
      t.set("number", "#b15c00")
      t.set("number.float", "#b15c00")
      t.set("operator", "#006a83")
      t.set("property", "#387068")
      t.set("punctuation", "#188092")
      t.set("punctuation.bracket", "#6172b0")
      t.set("punctuation.delimiter", "#006a83")
      t.set("punctuation.special", "#006a83")
      t.set("punctuation.special.markdown", "#b15c00")
      t.set("string", "#587539")
      t.set("string.documentation", "#8c6c3e")
      t.set("string.escape", "#9854f1")
      t.set("string.regexp", "#2e5857")
      t.set("string.special", "#188092")
      t.set("tag", "#9854f1")
      t.set("tag.attribute", "#387068")
      t.set("tag.builtin", "#188092")
      t.set("tag.delimiter", "#188092")
      t.set("tag.delimiter.tsx", "#649be8")
      t.set("tag.javascript", "#f52a65")
      t.set("tag.tsx", "#f52a65")
      t.set("type", "#188092")
      t.set("type.builtin", "#4094a3")
      t.set("type.definition", "#188092")
      t.set_extended("type.qualifier", color: "#7847bd", italic: true)
      t.set("variable", "#3760bf")
      t.set("variable.builtin", "#f52a65")
      t.set("variable.member", "#387068")
      t.set("variable.parameter", "#8c6c3e")
      t.set("variable.parameter.builtin", "#7b6a58")
      t.resolve
    end

    def tokyo_moon : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#c8d3f5", bg: "#e1e2e7")
      t.set("annotation", "#86e1fc")
      t.set("attribute", "#86e1fc")
      t.set("attribute.builtin", "#65bcff")
      t.set("boolean", "#ff966c")
      t.set("character", "#c3e88d")
      t.set("character.printf", "#65bcff")
      t.set("character.special", "#65bcff")
      t.set_extended("comment", color: "#636da6", italic: true)
      t.set("comment.error", "#c53b53")
      t.set("comment.hint", "#4fd6be")
      t.set("comment.info", "#0db9d7")
      t.set("comment.note", "#4fd6be")
      t.set("comment.todo", "#82aaff")
      t.set("comment.warning", "#ffc777")
      t.set("constant", "#ff966c")
      t.set("constant.builtin", "#65bcff")
      t.set("constant.macro", "#86e1fc")
      t.set("constructor", "#c099ff")
      t.set("constructor.tsx", "#65bcff")
      t.set("function", "#82aaff")
      t.set("function.builtin", "#65bcff")
      t.set("function.call", "#82aaff")
      t.set("function.macro", "#86e1fc")
      t.set("function.method", "#82aaff")
      t.set("function.method.call", "#82aaff")
      t.set("ibl.indent.char.1", "#3b4261")
      t.set("ibl.scope.char.1", "#65bcff")
      t.set("ibl.whitespace.char.1", "#3b4261")
      t.set_extended("keyword", color: "#fca7ea", italic: true)
      t.set("keyword.conditional", "#c099ff")
      t.set_extended("keyword.coroutine", color: "#fca7ea", italic: true)
      t.set("keyword.debug", "#ff966c")
      t.set("keyword.directive", "#86e1fc")
      t.set("keyword.directive.define", "#86e1fc")
      t.set("keyword.exception", "#c099ff")
      t.set("keyword.function", "#c099ff")
      t.set("keyword.import", "#86e1fc")
      t.set("keyword.operator", "#89ddff")
      t.set("keyword.repeat", "#c099ff")
      t.set_extended("keyword.return", color: "#fca7ea", italic: true)
      t.set("keyword.storage", "#65bcff")
      t.set("label", "#82aaff")
      t.set("markup.environment", "#86e1fc")
      t.set("markup.environment.name", "#65bcff")
      t.set_extended("markup.heading", color: "#82aaff", bold: true)
      t.set_extended("markup.heading.1.markdown", color: "#82aaff", bold: true)
      t.set_extended("markup.heading.2.markdown", color: "#ffc777", bold: true)
      t.set_extended("markup.heading.3.markdown", color: "#c3e88d", bold: true)
      t.set_extended("markup.heading.4.markdown", color: "#4fd6be", bold: true)
      t.set_extended("markup.heading.5.markdown", color: "#c099ff", bold: true)
      t.set_extended("markup.heading.6.markdown", color: "#fca7ea", bold: true)
      t.set_extended("markup.heading.7.markdown", color: "#ff966c", bold: true)
      t.set_extended("markup.heading.8.markdown", color: "#ff757f", bold: true)
      t.set("markup.link", "#4fd6be")
      t.set("markup.link.label", "#65bcff")
      t.set("markup.link.label.symbol", "#c099ff")
      t.set("markup.list", "#89ddff")
      t.set("markup.list.checked", "#4fd6be")
      t.set_extended("markup.list.markdown", color: "#ff966c", bold: true)
      t.set("markup.list.unchecked", "#82aaff")
      t.set("markup.math", "#65bcff")
      t.set("markup.raw", "#c3e88d")
      t.set("markup.raw.markdown_inline", "#82aaff")
      t.set("module", "#86e1fc")
      t.set("module.builtin", "#ff757f")
      t.set("namespace.builtin", "#ff757f")
      t.set("number", "#ff966c")
      t.set("number.float", "#ff966c")
      t.set("operator", "#89ddff")
      t.set("property", "#4fd6be")
      t.set("punctuation", "#65bcff")
      t.set("punctuation.bracket", "#828bb8")
      t.set("punctuation.delimiter", "#89ddff")
      t.set("punctuation.special", "#89ddff")
      t.set("punctuation.special.markdown", "#ff966c")
      t.set("string", "#c3e88d")
      t.set("string.documentation", "#ffc777")
      t.set("string.escape", "#c099ff")
      t.set("string.regexp", "#b4f9f8")
      t.set("string.special", "#65bcff")
      t.set("tag", "#c099ff")
      t.set("tag.attribute", "#4fd6be")
      t.set("tag.builtin", "#65bcff")
      t.set("tag.delimiter", "#65bcff")
      t.set("tag.delimiter.tsx", "#6582c3")
      t.set("tag.javascript", "#ff757f")
      t.set("tag.tsx", "#ff757f")
      t.set("type", "#65bcff")
      t.set("type.builtin", "#589ed7")
      t.set("type.definition", "#65bcff")
      t.set_extended("type.qualifier", color: "#fca7ea", italic: true)
      t.set("variable", "#c8d3f5")
      t.set("variable.builtin", "#ff757f")
      t.set("variable.member", "#4fd6be")
      t.set("variable.parameter", "#ffc777")
      t.set("variable.parameter.builtin", "#f4c990")
      t.resolve
    end
  end
end
