module TreeSitterManager
  module Themes
    def vscode_dark : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#d4d4d4", bg: "#1f1f1f")
      t.set("annotation", "#dcdcaa")
      t.set("attribute", "#dcdcaa")
      t.set("attribute.builtin", "#4ec9b0")
      t.set("boolean", "#569cd6")
      t.set("character", "#ce9178")
      t.set("character.special", "#d4d4d4")
      t.set("comment", "#6a9955")
      t.set_extended("comment.error", color: "#f44747", bold: true)
      t.set_extended("comment.note", color: "#4ec9b0", bold: true)
      t.set("comment.todo", "#d7ba7d")
      t.set_extended("comment.warning", color: "#d7ba7d", bold: true)
      t.set("conditional", "#c586c0")
      t.set("constant", "#4fc1ff")
      t.set("constant.builtin", "#569cd6")
      t.set("constant.macro", "#4ec9b0")
      t.set("constructor", "#569cd6")
      t.set("constructor.python", "#4ec9b0")
      t.set("decorator", "#9cdcfe")
      t.set("define", "#c586c0")
      t.set("error", "#f44747")
      t.set("event", "#9cdcfe")
      t.set("exception", "#c586c0")
      t.set("field", "#9cdcfe")
      t.set("float", "#b5cea8")
      t.set("function", "#dcdcaa")
      t.set("function.builtin", "#dcdcaa")
      t.set("function.macro", "#dcdcaa")
      t.set("function.method", "#dcdcaa")
      t.set("include", "#c586c0")
      t.set("interface", "#9cdcfe")
      t.set("keyword", "#569cd6")
      t.set("keyword.conditional", "#c586c0")
      t.set("keyword.exception", "#c586c0")
      t.set("keyword.import", "#c586c0")
      t.set("keyword.repeat", "#c586c0")
      t.set("keyword.return", "#c586c0")
      t.set("label", "#9cdcfe")
      t.set("markup", "#d7ba7d")
      t.set_extended("markup.heading", color: "#569cd6", bold: true)
      t.set_extended("markup.italic", color: "#d4d4d4", italic: true)
      t.set("markup.link.label", "#9cdcfe")
      t.set("markup.link.url", "#d4d4d4")
      t.set("markup.list.checked", "#d7ba7d")
      t.set("markup.list.unchecked", "#d7ba7d")
      t.set("markup.raw", "#d4d4d4")
      t.set("markup.raw.markdown", "#ce9178")
      t.set("markup.raw.markdown_inline", "#ce9178")
      t.set_extended("markup.strikethrough", color: "#d4d4d4", strikethrough: true)
      t.set_extended("markup.strong", color: "#569cd6", bold: true)
      t.set_extended("markup.underline", color: "#d7ba7d", underline: true)
      t.set("method", "#dcdcaa")
      t.set("modifier", "#9cdcfe")
      t.set("module", "#4ec9b0")
      t.set("module.builtin", "#d7ba7d")
      t.set("namespace", "#4ec9b0")
      t.set("number", "#b5cea8")
      t.set("number.float", "#b5cea8")
      t.set("operator", "#d4d4d4")
      t.set("parameter", "#9cdcfe")
      t.set("property", "#9cdcfe")
      t.set("punctuation", "#d4d4d4")
      t.set("punctuation.bracket", "#d4d4d4")
      t.set("punctuation.delimiter", "#d4d4d4")
      t.set("punctuation.special", "#d4d4d4")
      t.set("regexp", "#f44747")
      t.set("repeat", "#c586c0")
      t.set("string", "#ce9178")
      t.set("string.escape", "#d4d4d4")
      t.set("string.regex", "#ce9178")
      t.set("string.regexp", "#ce9178")
      t.set("string.special", "#d4d4d4")
      t.set_extended("stringEscape", color: "#ce9178", bold: true)
      t.set("structure", "#9cdcfe")
      t.set("tag", "#569cd6")
      t.set("tag.attribute", "#9cdcfe")
      t.set("tag.builtin", "#569cd6")
      t.set("tag.delimiter", "#808080")
      t.set("text", "#d4d4d4")
      t.set_extended("text.danger", color: "#f44747", bold: true)
      t.set_extended("text.emphasis", color: "#d4d4d4", italic: true)
      t.set("text.literal", "#d4d4d4")
      t.set_extended("text.note", color: "#4ec9b0", bold: true)
      t.set_extended("text.strike", color: "#d4d4d4", strikethrough: true)
      t.set_extended("text.strong", color: "#569cd6", bold: true)
      t.set_extended("text.title", color: "#569cd6", bold: true)
      t.set_extended("text.underline", color: "#d7ba7d", underline: true)
      t.set("text.uri", "#d4d4d4")
      t.set_extended("text.warning", color: "#d7ba7d", bold: true)
      t.set("textReference", "#ce9178")
      t.set("type", "#4ec9b0")
      t.set("type.builtin", "#569cd6")
      t.set("type.builtin.tsx", "#4ec9b0")
      t.set("type.builtin.typescript", "#4ec9b0")
      t.set("type.qualifier", "#569cd6")
      t.set("variable", "#9cdcfe")
      t.set("variable.builtin", "#569cd6")
      t.set("variable.member", "#9cdcfe")
      t.set("variable.parameter", "#9cdcfe")
      t.set("variable.parameter.builtin", "#d7ba7d")
      t.set("variable.parameter.reference", "#9cdcfe")
      t.resolve
    end

    def vscode_light : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#343434", bg: "#1f1f1f")
      t.set("annotation", "#795e26")
      t.set("attribute", "#795e26")
      t.set("attribute.builtin", "#16825d")
      t.set("boolean", "#0000ff")
      t.set("character", "#c72e0f")
      t.set("character.special", "#343434")
      t.set("comment", "#008000")
      t.set_extended("comment.error", color: "#ff0000", bold: true)
      t.set_extended("comment.note", color: "#16825d", bold: true)
      t.set("comment.todo", "#800000")
      t.set_extended("comment.warning", color: "#800000", bold: true)
      t.set("conditional", "#af00db")
      t.set("constant.builtin", "#0000ff")
      t.set("constant.macro", "#16825d")
      t.set("constructor", "#0000ff")
      t.set("constructor.python", "#16825d")
      t.set("decorator", "#0451a5")
      t.set("define", "#af00db")
      t.set("error", "#ff0000")
      t.set("event", "#0451a5")
      t.set("exception", "#af00db")
      t.set("field", "#0451a5")
      t.set("float", "#098658")
      t.set("function", "#795e26")
      t.set("function.builtin", "#795e26")
      t.set("function.macro", "#795e26")
      t.set("function.method", "#795e26")
      t.set("ibl.indent.char.1", "#cecece")
      t.set("ibl.scope.char.1", "#098658")
      t.set("ibl.whitespace.char.1", "#cecece")
      t.set("include", "#af00db")
      t.set("interface", "#0451a5")
      t.set("keyword", "#0000ff")
      t.set("keyword.conditional", "#af00db")
      t.set("keyword.exception", "#af00db")
      t.set("keyword.import", "#af00db")
      t.set("keyword.repeat", "#af00db")
      t.set("keyword.return", "#af00db")
      t.set("label", "#0451a5")
      t.set("markup", "#800000")
      t.set_extended("markup.heading", color: "#800000", bold: true)
      t.set_extended("markup.italic", color: "#343434", italic: true)
      t.set("markup.link.label", "#0451a5")
      t.set("markup.link.url", "#343434")
      t.set("markup.list.checked", "#800000")
      t.set("markup.list.unchecked", "#800000")
      t.set("markup.raw", "#343434")
      t.set("markup.raw.markdown", "#c72e0f")
      t.set("markup.raw.markdown_inline", "#c72e0f")
      t.set_extended("markup.strikethrough", color: "#343434", strikethrough: true)
      t.set_extended("markup.strong", color: "#000080", bold: true)
      t.set_extended("markup.underline", color: "#800000", underline: true)
      t.set("method", "#795e26")
      t.set("modifier", "#0451a5")
      t.set("module", "#16825d")
      t.set("module.builtin", "#800000")
      t.set("namespace", "#16825d")
      t.set("number", "#098658")
      t.set("number.float", "#098658")
      t.set("operator", "#343434")
      t.set("parameter", "#0451a5")
      t.set("property", "#0451a5")
      t.set("punctuation", "#343434")
      t.set("punctuation.bracket", "#343434")
      t.set("punctuation.delimiter", "#343434")
      t.set("punctuation.special", "#343434")
      t.set("regexp", "#ff0000")
      t.set("repeat", "#af00db")
      t.set("string", "#c72e0f")
      t.set("string.escape", "#343434")
      t.set("string.regex", "#c72e0f")
      t.set("string.regexp", "#c72e0f")
      t.set("string.special", "#343434")
      t.set_extended("stringEscape", color: "#800000", bold: true)
      t.set("structure", "#0451a5")
      t.set("tag", "#0000ff")
      t.set("tag.attribute", "#0451a5")
      t.set("tag.builtin", "#0000ff")
      t.set("tag.delimiter", "#000000")
      t.set("text", "#343434")
      t.set_extended("text.danger", color: "#ff0000", bold: true)
      t.set_extended("text.emphasis", color: "#343434", italic: true)
      t.set("text.literal", "#343434")
      t.set_extended("text.note", color: "#16825d", bold: true)
      t.set_extended("text.strike", color: "#343434", strikethrough: true)
      t.set_extended("text.strong", color: "#000080", bold: true)
      t.set_extended("text.title", color: "#800000", bold: true)
      t.set_extended("text.underline", color: "#800000", underline: true)
      t.set("text.uri", "#343434")
      t.set_extended("text.warning", color: "#800000", bold: true)
      t.set("textReference", "#800000")
      t.set("type", "#16825d")
      t.set("type.builtin", "#0000ff")
      t.set("type.builtin.tsx", "#16825d")
      t.set("type.builtin.typescript", "#16825d")
      t.set("type.qualifier", "#0000ff")
      t.set("variable", "#0451a5")
      t.set("variable.builtin", "#0000ff")
      t.set("variable.member", "#0451a5")
      t.set("variable.parameter", "#0451a5")
      t.set("variable.parameter.builtin", "#800000")
      t.set("variable.parameter.reference", "#0451a5")
      t.resolve
    end
  end
end
