module TreeSitterManager
  module Themes
    def zephyr_zephyr : ResolvedTheme
      t = Theme.new
      t.set_extended("_normal", color: "#bbc2cf", bg: "#262a33")
      t.set("attribute", "#36d0e0")
      t.set("attribute.builtin", "#f7bb3b")
      t.set("boolean", "#ff8700")
      t.set("character", "#afd700")
      t.set("character.special", "#f7bb3b")
      t.set_extended("comment", color: "#73797e", italic: true)
      t.set("comment.error", "#ffc0b9")
      t.set("comment.note", "#8cf8f7")
      t.set("comment.todo", "#cba6f7")
      t.set("comment.warning", "#fce094")
      t.set("constant", "#36d0e0")
      t.set("constant.builtin", "#f7bb3b")
      t.set("constructor", "#f7bb3b")
      t.set("diff.delta", "#8cf8f7")
      t.set("diff.minus", "#ffc0b9")
      t.set("diff.plus", "#b3f6c0")
      t.set("function", "#f7bb3b")
      t.set("function.builtin", "#f7bb3b")
      t.set("ibl.indent.char.1", "#3f444a")
      t.set("ibl.scope.char.1", "#3f444a")
      t.set("ibl.whitespace.char.1", "#3f444a")
      t.set("keyword", "#afd700")
      t.set("label", "#ff8700")
      t.set("markup", "#f7bb3b")
      t.set_extended("markup.heading", color: "#ff8700", bold: true)
      t.set("module", "#ff8700")
      t.set("module.builtin", "#f7bb3b")
      t.set("number", "#c78665")
      t.set("number.float", "#c78665")
      t.set("operator", "#d16d9e")
      t.set("property", "#61afef")
      t.set("punctuation", "#bbc2cf")
      t.set("punctuation.special", "#f7bb3b")
      t.set("string", "#fab795")
      t.set("string.escape", "#f7bb3b")
      t.set("string.regexp", "#f7bb3b")
      t.set("string.special", "#f7bb3b")
      t.set("tag", "#ff8700")
      t.set("tag.builtin", "#f7bb3b")
      t.set("type", "#1abc9c")
      t.set("type.builtin", "#f7bb3b")
      t.set("variable", "#e0e2ea")
      t.set("variable.builtin", "#f7bb3b")
      t.set("variable.parameter.builtin", "#f7bb3b")
      t.resolve
    end
  end
end
