# Byte-level renderer comparison harness.
#
# Compares our terminal renderer output against syntastica's reference
# output byte-by-byte for the same input, language, and theme.
#
# Reference output is generated by `tools/syntastica_compare/` (Rust):
#   cargo run --release -- <lang> <file> <theme> <output_file>
#
# Then run this spec to compare:
#   crystal spec spec/renderer_byte_comparison_spec.cr
#
# If the reference output file doesn't exist, the test is skipped.

require "./spec_helper"

module RendererComparison
  extend self

  # Path where syntastica reference outputs are stored
  REFERENCE_DIR = File.join(__DIR__, "..", "tmp", "reference_outputs")

  # Generate reference output path for (lang, theme)
  def reference_path(lang : String, theme : String) : String
    Dir.mkdir_p(REFERENCE_DIR)
    File.join(REFERENCE_DIR, "#{lang}_#{theme.gsub("::", "_")}.txt")
  end

  # Generate our renderer output for the same input
  def our_output(source : String, lang : String, theme_name : String) : String
    theme = TreeSitterManager::Themes.from_str(theme_name) ||
            TreeSitterManager::Themes.get(theme_name)
    raise "Unknown theme: #{theme_name}" unless theme

    hl = TreeSitterManager::SourceHighlighter.new(lang)
    hl.theme = theme
    hl.highlight_to_terminal(source)
  end

  # Compare: returns nil if outputs match, or a diff message
  def compare(source : String, lang : String, theme_name : String) : String?
    ref_path = reference_path(lang, theme_name)
    return "Reference output not found at #{ref_path}" unless File.exists?(ref_path)

    expected = File.read(ref_path)
    actual = our_output(source, lang, theme_name)

    if expected == actual
      nil
    else
      # Find first byte difference
      min_len = Math.min(expected.size, actual.size)
      diff_pos = (0...min_len).find { |i| expected[i] != actual[i] }
      if diff_pos
        context_start = [0, diff_pos - 20].max
        "Byte difference at position #{diff_pos}:\n" \
        "  expected: #{expected.bytes[diff_pos].inspect} '#{expected[diff_pos]?.inspect}'\n" \
        "  actual:   #{actual.bytes[diff_pos].inspect} '#{actual[diff_pos]?.inspect}'\n" \
        "  context expected: #{expected[context_start, 40].inspect}\n" \
        "  context actual:   #{actual[context_start, 40].inspect}"
      else
        "Size mismatch: expected #{expected.size} bytes, actual #{actual.size} bytes"
      end
    end
  end
end

# To generate reference output for a Crystal file:
#   cargo run --release --manifest-path tools/syntastica_compare/Cargo.toml \
#     -- crystal path/to/file.cr "dracula::dracula" \
#     tmp/reference_outputs/crystal_dracula_dracula.txt
#
# Then run these tests to compare.

describe "Renderer byte-level comparison" do
  sample_crystal = "x = 1\nputs x\n"

  it "skips when reference output not found" do
    result = RendererComparison.compare(sample_crystal, "crystal", "dracula::dracula")
    # Should skip (no reference file) rather than fail
    if result
      result.should contain("Reference output not found")
    end
  end

  it "generates our output without error" do
    output = RendererComparison.our_output(sample_crystal, "crystal", "dracula::dracula")
    output.should_not be_nil
    output.size.should be > 0
  end

  it "produces correct ANSI structure" do
    output = RendererComparison.our_output(sample_crystal, "crystal", "dracula::dracula")
    # Every \e[... should have a matching m terminator
    output.scan(/\e\[/).size.should be > 0
    # The output should contain the original source text
    plain = output.gsub(/\e\[[0-9;]*[a-zA-Z]/, "")
    plain.should contain("x = 1")
    plain.should contain("puts x")
  end
end
